<?php
//TEXTOS EN INFORMES
define("STR_PIE_INFORMES", "és una marca registrada per Psicólogos Empresariales. La reproducció total o parcial d'aquest Informe per qualsevol mitjà, infringeix els drets de Copyright.");
define("STR_NOMBRE_APELLIDOS", "Nom i Cognoms");
define("STR_FECHA_INFORME", "Data de l'Informe");
define("STR_FECHA_INFORME_DIAN", "Finish date");
define("STR_IDENTIFICADOR", "Número de Cédula");
define("STR_INTRODUCCION", "Introducció");
define("STR_INTRODUCCION_CAPS", "INTRODUCCIÓ");
define("STR_PUNTUACION_DIRECTA", "Puntuació Directa");
define("STR_PUNTUACION_PERCENTIL", "Puntuació Percentil");
define("STR_INDICE_RAPIDEZ", "Índex de Rapidesa");
define("STR_INDICE_PRECISION", "Índex de Precisió");
define("STR_PRODUCTO_RENDIMIENTO", "Producte Rendiment");
define("STR_ESTILO_PROCESAMIENTO_MENTAL", "Estil de Processament Mental");
define("STR_NUM_TOTAL_PREGUNTAS", "Nombre total de preguntes del Test");
define("STR_NUM_PREGUNTAS_ACERTADAS", "Nombre de preguntes encertades");
define("STR_PUNT_INFORMES", "Puntuació");
define("STR_BAJO_POTENCIAL", "SOTA POTENCIAL");
define("STR_MEDIO_POTENCIAL", "MEDI POTENCIAL");
define("STR_ALTO_POTENCIAL", "ALT POTENCIAL");
define("STR_ESTE_INFORME_REPRESENTA", "Aquest informe presenta la següent informació sobre la base dels resultats obtinguts després de la realització del Test:");
define("STR_EXP_PUNT_PECENTIL", "Indica el percentatge de subjectes que ha obtingut una puntuació inferior. Per exemple, el percentil 35 és la puntuació que deixa per sota el 35% dels subjectes del grup.");
define("STR_EXP_PUNT_DIRECTA", "Es refereix al nombre de preguntes contestades correctament.");
define("STR_EXP_INDICE_RAPIDEZ", "La rapidesa és a la base de l'aprenentatge i de l'aptitud. Aquest índex s'obté en base al nombre de preguntes contestades en un espai de temps limitat.");
define("STR_EXP_INDICE_PRECISION", "Representa la qualitat davant la quantitat que seria la rapidesa. Aquest índex s'obté en funció del nombre de preguntes encertades en un espai de temps limitat.");
define("STR_EXP_PRODUCTO_RENDIMIENTO", "Representa la interacció entre rapidesa-precisió o precisió-rapidesa, posant l'èmfasi en una o altra segons l'estil o l'actitud de cada un.");
define("STR_EXP_ESTILO_PROCESAMIENTO_MENTAL", "En base a l'anàlisi dels índexs de rapidesa i precisió, es pot determinar quin és l'estil o mapa mental de la persona. Conèixer el seu estil de processament ajuda a determinar en quin tipus de tasques o activitats serà tenir un major rendiment. ");
define("STR_PRISMA_INTRO_P1", "Aquest informe està basat en les respostes de la persona que ha contestat al PRISM@. Ha estat generat de manera automàtica mitjançant la Plataforma Test Station de Psicólogos Empresariales.");
define("STR_PRISMA_INTRO_P2", "Psicólogos Empresariales només es fa responsable de la seva versió original i no de possibles modificacions o annexos que d'altres usuaris puguin realitzar com a versió posterior o puntualitzacions segons altres percepcions sobre la persona que ha realitzat el qüestionari.");
define("STR_PRISMA_INTRO_P3", "El Perfil General té 32 escales. Aquestes escales s'agrupen en 9 factors que corresponen a 4 grans àrees de la personalitat laboral:");
define("STR_PRISMA_INTRO_P4", "- ENERGIES I EMOCIONS.");
define("STR_PRISMA_INTRO_P5", "- CONTROL EMOCIONAL I TOLERÀNCIA A L'ESTRÈS.");
define("STR_PRISMA_INTRO_P6", "- ESTILS DE RELACIÓ (Orientació a la relació, a les persones i influència, ascendència i comandament).");
define("STR_PRISMA_INTRO_P7", "- ESTILS DE PROCESAMENT MENTAL (Competències Analítiques, Potencial de Recursos Mentals, Flexibilitat i Estil de Treball).");
define("STR_PRISMA_INTRO_P8", "Els informes Experts de Competències i Perfils derivats, són opcionals i es descriuen de manera independent.");
define("STR_PRISMA_INTRO_P9", "Recomanem que, a l'hora d'interpretar els resultats dels informes, sempre es tingui en consideració les puntuacions de consistència obtingudes.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA", "INTERPRETACIÓ DE L'ESCALA DE CONSISTÈNCIA");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P1", "L'Escala de Consistència ens proporciona informació sobre l'estil de resposta o actitud del professional que ha contestat el qüestionari . Al ser-hi un Qüestionari de \"resposta obligada\", es redueix la possible \"distorsió motivacional\" o tendència a donar un perfil desitjat o convenient.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P2", "Per tant, la puntuació a l'escala de Consistència expressa el grau en què la persona s'ha esforçat per mantenir la coherència o congruència entre unes i d'altres respostes de Qüestionari.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P3A", "Consistència Alta (9-10)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P3B", "Tan alta congruència pot indicar possible manipulació o desig de donar una imatge determinada de sí mateix/a.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P4A", "Consistència Baixa (1-2)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P4B", "Una congruència tan baixa pot indicar que la persona ha donat moltes respostes a l'atzar, per no entendre les instruccions, falta d'implicació o falta d'autoanàlisi.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P5A", "Consistències Lleugerament Mitges (3-4 y 7-8)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P5B", "Es desvien lleugerament dels valor ideals per la qual cosa pot existir distorsió en alguna escala, encara que no afecti al Perfil General.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P6A", "Consistència Mitja (5-6)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P6B", "Generalment indica que s'ha contestat amb motivació o interès i no s'ha trobat dificultats per a realitzar o entendre el qüestionari.");
define("STR_PRISMA_PERFIL_DE_PERSONALIDAD_LABORAL", "PERFIL DE PERSONALITAT LABORAL");
define("STR_PRISMA_BAJO", "Baix");
define("STR_PRISMA_ME_BA", "Mig.-Ba.");
define("STR_PRISMA_MEDIO", "Mig");
define("STR_PRISMA_ME_AL", "Mig.-Al.");
define("STR_PRISMA_ALTO", "Alt");
define("STR_PRISMA_DINAMISMO_Y_ACTIVIDAD", "Dinamisme i activitat");
define("STR_PRISMA_DINAMISMO_Y_ACTIVIDAD_TXT", "Li agraden les activitats que exigeixen esforços i alt grau d'activitat. Es mantenen sempre ocupats/des.");
define("STR_PRISMA_CONSTANCIA_PERSEVERANCIA", "Constància / perseverança");
define("STR_PRISMA_CONSTANCIA_PERSEVERANCIA_TXT", "S'esforcen per finalitzar les tasques a temps. Finalitzen el que comencen. Són constants i compleixen els terminis.");
define("STR_PRISMA_AMBICION_DE_METAS_Y_LOGROS", "Ambició de metes i èxits");
define("STR_PRISMA_AMBICION_DE_METAS_Y_LOGROS_TXT", "S'autoexigeixen. Busquen objectiu i metes difícils. Ambiciosos/es per superar-se i millorar.");
define("STR_PRISMA_COMPETITIVIDAD", "Competitivitat");
define("STR_PRISMA_COMPETITIVIDAD_TXT", "Gaudeixen amb activitats competitives. Participen per guanyar i ser els millors quan es comparin amb els demés. No toleren perdre.");
define("STR_PRISMA_DECISION", "Decisió");
define("STR_PRISMA_DECISION_TXT", "Sospesen les alternatives i prenen les decisions amb rapidesa. Disposat a actuar.");
define("STR_PRISMA_TENSION_INTERNA", "Tensió interna");
define("STR_PRISMA_TENSION_INTERNA_TXT", "Internament tensos/es. Difícilment es relaxen. Amb ansietat davant de pressions o situacions difícils.");
define("STR_PRISMA_AUTODOMINIO", "Autodomini");
define("STR_PRISMA_AUTODOMINIO_TXT", "Serens/es. Mantenen el domini de sí mateixos en situacions importants o davant de problemes. La pressió i/o preocupacions no els afecten. Regulen la seva ansietat.");
define("STR_PRISMA_RESISTENCIA_EMOCIONAL", "Resistència emocional");
define("STR_PRISMA_RESISTENCIA_EMOCIONAL_TXT", "No els preocupa el que opinin els altres. No reaccionen ni s'ofenen davant crítiques personals. No se solen sentir ofendidios / es.");
define("STR_PRISMA_CONTROL_EXTERNO", "Control extern");
define("STR_PRISMA_CONTROL_EXTERNO_TXT", "Controlen les seves emocions i no mostren als altres els seus sentiments, bé siguin de entusiasme o de malestar.");
define("STR_PRISMA_CONFIANZA_EN_LOS_DEMAS", "Confiança en els altres");
define("STR_PRISMA_CONFIANZA_EN_LOS_DEMAS_TXT", "Vine als altres com honestos i fiables Creuen en la paraula i bondat de les persones.");
define("STR_PRISMA_ACTITUD_POSITIVA", "Actitud positiva");
define("STR_PRISMA_ACTITUD_POSITIVA_TXT", "Confien en que el futur sigui favorable. Tendeixen a veure el positiu en cada situació. Positius / es.");
define("STR_PRISMA_EXTROVERSION", "Extraversió");
define("STR_PRISMA_EXTROVERSION_TXT", "Gaudeixen animant els grups o les reunions. Parladors / es. Bons conversadors. Els agrada el protagonisme social en les relacions.");
define("STR_PRISMA_AFILIACION_SOCIABILIDAD", "Afiliació / sociabilitat");
define("STR_PRISMA_AFILIACION_SOCIABILIDAD_TXT", "Necessiten estar amb gent. Gaudeix en companyia d'altres encara que no siguin protagonistes. No els agrada la soledat. Col · laboren i són servicials amb els altres.");
define("STR_PRISMA_HABILIDAD_RELACIONAL", "Habilitat relacional");
define("STR_PRISMA_HABILIDAD_RELACIONAL_TXT", "Actuen amb seguretat en les reunions i en públic. Se saben relacionar en públic i controlar les situacions. Creen impacte.");
define("STR_PRISMA_EMPATIA", "Empatia");
define("STR_PRISMA_EMPATIA_TXT", "Es interessen i preocupen pels altres. Són tolerants, comprensius / es i considerats / es. Preocupats per solucionar els problemes de la gent.");
define("STR_PRISMA_MODESTIA", "Modèstia");
define("STR_PRISMA_MODESTIA_TXT", "Prefereixen no presumir dels seus èxits i qualitats. Es mostren prudents i humils. No els agrada parlar de si mateixos.");
define("STR_PRISMA_CONSENSUADOR", "consensuat / a");
define("STR_PRISMA_CONSENSUADOR_TXT", "Consulten i escolten als altres. Busquen el suport per decidir. Prefereixen decidir per acord.");
define("STR_PRISMA_PERSUASION", "Persuasió");
define("STR_PRISMA_PERSUASION_TXT", "Influents. Eloqüents. Intenten convèncer els altres perquè acceptin els seus punts de vista. Poden ser excel · lents venedors o negociadors eficaços.");
define("STR_PRISMA_VOLUNTAD_DE_MANDO_Y_DIRECCION", "Voluntat de comandament i direcció");
define("STR_PRISMA_VOLUNTAD_DE_MANDO_Y_DIRECCION_TXT", "Prefereixen assumir el lideratge en els grups. Els agrada dirigir, organitzar i supervisar els projectes i / oa les persones.");
define("STR_PRISMA_AUTONOMIA_AUTODETERMINACION", "Autonomia / Autodeterminació");
define("STR_PRISMA_AUTONOMIA_AUTODETERMINACION_TXT", "Actuen i pensen pel seu compte. No segueixen les opinions de la majoria. Prefereixen fer les coses a la seva manera. Autosuficients.");
define("STR_PRISMA_DIRECTO_ESPONTANEO", "Directe / Espontani");
define("STR_PRISMA_DIRECTO_ESPONTANEO_TXT", "Solen dir el que pensen clara i directament. Són directes / es i expressen les seves crítiques amb seguretat.");
define("STR_PRISMA_ANALISIS_OBJETIVO", "Anàlisi objectiu");
define("STR_PRISMA_ANALISIS_OBJETIVO_TXT", "Basen les seves decisions i propostes en dades i fets objectius. Les informacions que més valoren són les xifres i dades quantitatives.");
define("STR_PRISMA_ANALISIS_DE_RIESGOS", "Anàlisi de riscos");
define("STR_PRISMA_ANALISIS_DE_RIESGOS_TXT", "Analitzen la informació críticament, buscant els riscos o problemes potencials de cada situació.");
define("STR_PRISMA_ANALISIS_DE_PERSONAS", "Anàlisi de persones");
define("STR_PRISMA_ANALISIS_DE_PERSONAS_TXT", "Quan s'analitzen situacions o prenen decisions, s'interessen per les raons i / o motius del comportament de les persones.");
define("STR_PRISMA_PROFUNDIDAD_CONCEPTUAL", "Profunditat conceptual");
define("STR_PRISMA_PROFUNDIDAD_CONCEPTUAL_TXT", "Els agrada treballar amb models i bases teòriques. Es documenten. Analitzen amb profunditat els assumptes. Curiosos / es mentals.");
define("STR_PRISMA_INNOVACION_Y_SOLUCIONES", "Innovació i solucions");
define("STR_PRISMA_INNOVACION_Y_SOLUCIONES_TXT", "Aporten noves idees i solucions originals. Proposen millores i idees creatives. Gaudeixen creant més que realitzant.");
define("STR_PRISMA_PREVISION_Y_PLANIFICACION", "Previsió i planificació");
define("STR_PRISMA_PREVISION_Y_PLANIFICACION_TXT", "Tenen visió a mig i llarg termini. Amb perspectiva. S'orienten al futur. Preveuen antecedents i conseqüències.");
define("STR_PRISMA_ADAPTABILIDAD_FLEXIBILIDAD", "Adaptabilitat / flexibilitat");
define("STR_PRISMA_ADAPTABILIDAD_FLEXIBILIDAD_TXT", "S'adapten fàcilment a les diverses persones i circumstàncies. Oberts a canvis i innovacions.");
define("STR_PRISMA_PRO_CAMBIOS", "Pro-canvis");
define("STR_PRISMA_PRO_CAMBIOS_TXT", "Prefereixen canviar sovint. Busquen la varietat de tasques i activitats. Els agrada provar coses noves. Li avorreix la rutina.");
define("STR_PRISMA_PRAGMATISMO", "Pragmatisme");
define("STR_PRISMA_PRAGMATISMO_TXT", "Se centren en l'operatiu i viable. Concreta i s'até al que és possible. Va directament a buscar i aplicar solucions pràctiques.");
define("STR_PRISMA_ORDEN_ORGANIZACION", "Ordre / Organització");
define("STR_PRISMA_ORDEN_ORGANIZACION_TXT", "Realitzen les tasques amb minuciositat i detall. Són organitzats i sistemàtics / es. No toleren el desordre.");
define("STR_PRISMA_DISCIPLINA", "Disciplina");
define("STR_PRISMA_DISCIPLINA_TXT", "Respecten les normes i segueixen els procediments establerts. Són molt rigorosos / es en el compliment de les normes.");
define("STR_PRISMA_G_C", "G.C.");
define("STR_PRISMA_STR_PRISMA_G_C_TXT", "Grau de congruència en les respostes");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL", "PERFIL GENERAL DE PERSONALITAT LABORAL");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL_P1", "A partir de les respostes donades pel / per la candidat / a al qüestionari, s'obté el perfil general de les 12 escales en què s'integren les 32 que conté el qüestionari.");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL_P2", "Per tant, ofereix un resum de la tendència habitual de comportament de la persona que ha contestat al qüestionari, obtenint una visió ràpida i global del seu perfil professional.");
define("STR_PRISMA_NIVEL_GENERAL_DE", "NIVELL GENERAL DE");
define("STR_PRISMA_ENERGIA_Y_MOTIVACIONES", "Energies i Motivacions");
define("STR_PRISMA_EXTROVERSION_Y_PROTAGONISMO_SOCIAL", "Extraversió i <br /> Protagonisme social");
define("STR_PRISMA_INFLUENCIA_MANDO_O_ASCENDENCIA", "Influència, comandament o <br /> ascendència");
define("STR_PRISMA_EMPATIA_Y_ORIENTACION_A_LAS_PERSONAS", "Empatia i Orientació <br /> a les persones");
define("STR_PRISMA_ORIENTACION_A_TAREAS_Y_OBJETIVOS", "Orientació a tasques i objectius");
define("STR_PRISMA_POTENCIA_ANALITICA_Y_SOLUCIAON_DE_PROBLEMAS", "Potència analític i Solució de <br /> problemes");
define("STR_PRISMA_FLEXIBILIDAD_MENTAL", "Flexibilitat mental");
define("STR_PRISMA_DISCIPLINA_Y_ORDEN", "Disciplina i ordre");
define("STR_PRISMA_PRECISION_Y_CALIDAD", "Precisió i Qualitat");
define("STR_PRISMA_RAPIDEZ_Y_OPERATIVIDAD", "Rapidesa i Operativitat");
define("STR_PRISMA_CONTROL_EMOCIONAL", "Control Emocional");
define("STR_PRISMA_TOLERANCIA_AL_ESTRES", "Tolerància al l'estrès");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS", "INFORME ORIENTAT A COMPETÈNCIES");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1", "A continuació es presenta informació més detallada sobre el perfil de competéncies.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P2", "La columna de l'esquerra indica la competència. Els comportaments que apareixen a la columna central són aspectes clau que contribueixen positivament o negativament en cada competència.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P3", "El nivell de desenvolupament de la competència i l'impacte de cadascuna en el perfil general es mostren a la columna de la dreta.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P4", "La columna de l'esquerra indica la competència. Els comportaments que apareixen a la columna central són aspectes clau que contribueixen positivament o negativament en cada competència.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P5", "El nivell de desenvolupament de la competència i l'impacte de cadascuna en el perfil general es mostren a la columna de la dreta.");
define("STR_PRISMA_COMPETENCIAS_PARA_LA_GESTION", "COMPETÈNCIES PER A LA GESTIÓ");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_BR", "DIRIGIR <br /> I <br /> LIDERAR");
define("STR_PRISMA_A_VECES", "DE VEGADES");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_A_VECES_TXT", "Assumeix la responsabilitat i el control als equips i / o projectes. Es responsabilitza de l'assignació d'objectius a persones o equips. Impulsa a altres perquè aconsegueixin objectius. Aconsegueix dirigir eficaçment a les persones / equips. ");
define("STR_PRISMA_AREA_EN_DESARROLLO", "ÀREA EN DESENVOLUPAMENT");
define("STR_PRISMA_PLANIFICACION", "PLANIFICACIÓ");
define("STR_PRISMA_CASI_NUNCA", "GAIREBÉ MAI");
define("STR_PRISMA_STR_PRISMA_PLANIFICACION_CASI_NUNCA_TXT", "Organitza i distribueix els treballs de les persones o els projectes. Dedica temps, recursos o esforços a planificar eficaçment. Realitza previsions realistes tant en temps com en terminis de lliurament.");
define("STR_PRISMA_AREA_POTENCIAL_DESARROLLO", "ÀREA POTENCIAL DESENVOLUPAMENT");
define("STR_PRISMA_COMUNICACION_SOCIAL_BR", "COMUNICACIÓ <br /> SOCIAL");
define("STR_PRISMA_NUNCA", "MAI");
define("STR_PRISMA_COMUNICACION_SOCIAL_NUNCA_TXT", "S'expressa amb claredat i eficàcia en reunions o esdeveniments. Realitza discursos i / o comunicacions amb fluïdesa i eficàcia. Aconsegueix captar l'atenció del públic en xerrades o presentaciones.Se sent segur / ai còmode / a en intervenir en públic. ");
define("STR_PRISMA_AREA_CLAVE_DE_MEJORA", "ÀREA CLAU DE MILLORA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_BR", "PERSUASIU <br /> I <br /> INFLUÈNCIA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_A_VECES_TXT", "Convenç i persuadeix amb eficàcia a altres persones. Negocia amb èxit i eficàcia davant els seus interlocutors o competidors. Aconsegueix que altres acceptin els seus projectes, opinions i suggeriments, amb facilitat. Indueix amb eficàcia a altres a que canviïn d'opinió . ");
define("STR_PRISMA_COMPETENCIAS_TECNICAS", "COMPETÈNCIES TÈCNIQUES");
define("STR_PRISMA_DOMINIO_DE_SU_ESPECIALIDAD", "DOMINI <br /> DEL SEU <br /> ESPECIALITAT");
define("STR_PRISMA_STR_PRISMA_DOMINIO_DE_SU_ESPECIALIDAD_A_VECES_TXT", "Demostra un alt domini en la seva àrea d'especialització. Procura mantenir actualitzat / a en coneixements tècnics especialitzats. Assimila ràpidament noves tècniques o coneixements específics. Domina els aspectes tècnics del seu treball o àrea.");
define("STR_PRISMA_ANALISIS", "ANÀLISI");
define("STR_PRISMA_ANALISIS_A_VECES_TXT", "Analitza en profunditat o detingudament els fets, dades o informacions. Demostra eficàcia solucionant problemes. Estableix mètodes i / o processos que amplien i / o faciliten solucions. Analitza les causes, detalls o conseqüències en els problemes o assumptes . ");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_2BR", "GARANTIA <br /> I PROMOCIÓ <br /> DE LA QUALITAT");
define("STR_PRISMA_CASI_SIEMPRE", "GAIREBÉ SEMPRE");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_CASI_SIEMPRE_TXT", "Assumeix i / o promociona la importància de la qualitat. Es compromet activament en l'assoliment d'objectius de qualitat. S'exigeix, en les seves tasques, alta qualitat. Es mostra estricte / a en mantenir normes i / o estàndards de qualitat. ");
define("STR_PRISMA_AREA_POTENCIAL_FORTALEZA", "ÀREA POTENCIAL FORTALESA");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_BR", "ORDRE <br /> I SISTEMÀTICA <");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_A_VECES_TXT", "Realitza les tasques amb minuciositat prestant atenció als detalls. Procura mantenir ordenat el seu entorn de treball. Segueix una estructura i sistemàtica a l'hora d'afrontar les seves tasques.");
define("STR_PRISMA_COMPETENCIAS_PARA_EL_DESARROLLO_DEL_NEGOCIO", "COMPETÈNCIES PER AL DESENVOLUPAMENT DEL NEGOCI");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_BR", "ORIENTACIÓ <br /> AL ASSOLIMENT");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_CASI_NUNCA_TXT", "Se centra amb energia en l'assoliment d'objectius / resultats. Enfoca els seus treballs i activitats cap al creixement del negoci. Demostra un fort sentit o enfocament cap al comercial. Està atent a les vendes, facturació i / o rendibilitat de l'organització. ");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_2BR", "INNOVACIÓ <br /> I <br /> CREATIVITAT");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_A_VECES_TXT", "Es mostra capaç de produir idees o enfocaments originals. Es mostra innovador / a introduint millores. Aporta noves idees o punts de vista. Proposa noves idees, productes, serveis o procediments.");
define("STR_PRISMA_ORIENTACIÓN_A_LA_ACCION_Y_DECISION", "ORIENTACIÓ <br /> A L'ACCIÓ <br /> I DECISIÓ");
define("STR_PRISMA_ORIENTACIÓN_A_LA_ACCION_Y_DECISION_CASI_NUNCA_TXT", "Pren decisions amb facilitat o rapidesa. Demuesta energia o determinació en el treball. Pren la iniciativa en les decisions. Impulsa amb energia la realització dels treballs.");
define("STR_PRISMA_VISION_ESTRATEGICA_BR", "VISIÓ <br /> ESTRATÈGICA");
define("STR_PRISMA_VISION_ESTRATEGICA_CASI_NUNCA_TXT", "Té en compte els objectius generals de l'empresa / negoci. Pensa i actua amb visió a mitjà / llarg termini. Pren decisions que suposen canvis estratègics en l'empresa. Elabora o estableix objectius d'empresa a llarg termini. ");
define("STR_PRISMA_COMPETENCIAS_INTERPERSONALES", "COMPETÈNCIES INTERPERSONALS");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_BR", "HABILITAT <br /> INTERPERSONAL");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_CASI_NUNCA_TXT", "Demostra habilitat per relacionar-se amb els altres i fer equip. Ajuda i facilita el treball als altres. Demostra interès i sensibilitat cap als altres. Demostra ser capaç d'obtenir el millor de cada col · laborador / ao company / a . ");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_BR", "FLEXIBILITAT <br /> I <br /> ADAPTACIÓ");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_NUNCA_TXT", "Accepta positivament els canvis. S'adapta fàcilment a les noves persones o situacions. Demostra bona disposició per acceptar nous mètodes o procediments. Dóna suport a les iniciatives de canvis o millores.");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_2BR", "RESISTÈNCIA <br /> A LA FATIGA <br /> I AL ESTRÈS");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_CASI_SIEMPRE_TXT", "'Manté la calma en situacions de tensió. Es recupera amb facilitat després dels contratemps. Tolera fàcilment les crítiques o menyspreus. Es sobreposa o es controla davant exigències o pressions.");
define("STR_PRISMA_MOTIVACION_PERSONAL_POR_EL_TRABAJO", "MOTIVACIÓ <br /> PERSONAL <br /> PEL TREBALL");
define("STR_PRISMA_MOTIVACION_PERSONAL_POR_EL_TRABAJO_CASI_NUNCA_TXT", "Assumeix amb intensitat les seves responsabilitats laborals. Cerca promoció professional a l'empresa. Supera els errors passats posant ànim o energia. Demostra alta voluntat per fer les coses progressivament millor.");
define("STR_PRISMA_AREA_CLAVE_DE_MEJORA_BR", "Àrea <br /> Clau <br /> de Millora");
define("STR_PRISMA_AREA_DE_POTENCIAL_DESARROLLO", "Àrea <br /> de Potencial <br /> Desenvolupament");
define("STR_PRISMA_AREA_DE_DESARROLLO_2BR", "Àrea <br /> de <br /> Desenvolupament");
define("STR_PRISMA_AREA_DE_POTENCIAL_FORTALEZA", "Àrea <br /> de Potencial <br /> Fortalesa");
define("STR_PRISMA_AREA_DE_FORTALEZA_2BR", "Àrea <br /> de <br /> Fortalesa");
define("STR_PRISMA_NUNCA_SE_COMPORTA_ASI", "<strong> Mai </ strong> <br /> es comporta així");
define("STR_PRISMA_CASI_NUNCA_SE_COMPORTA_ASI", "<strong> Gairebé Mai </ strong> <br /> es comporta així");
define("STR_PRISMA_A_VECES_SE_COMPORTA_ASI", "<strong> De Vegades </ strong> <br /> es comporta així");
define("STR_PRISMA_CASI_SIEMPRE_SE_COMPORTA_ASI", "<strong> Gairebé Sempre </ strong> <br /> es comporta així");
define("STR_PRISMA_SIEMPRE_SE_COMPORTA_ASI", "<strong> Sempre </ strong> <br /> es comporta així");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR", "DIRIGIR I LIDERAR");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_TXT", "Coordina i guia als altres per aconseguir els objectius de l'organització.");
define("STR_PRISMA_PLANIFICACION_TXT", "Planifica les activitats, projectes, etc., tenint els recursos disponibles i els terminis establerts, estant atent als possibles imprevistos.");
define("STR_PRISMA_COMUNICACION_SOCIAL", "COMUNICACIÓ SOCIAL");
define("STR_PRISMA_COMUNICACION_SOCIAL_TXT", "Parla amb claredat, fluïdesa i convicció, tant individualment com en grups.");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA", "PERSUASIÓ I INFLUÈNCIA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_TXT", "Influeix, convenç, impacta en els altres per millorar o canviar resultats, punts de vista o comportaments.");
define("STR_PRISMA_DOMINIO_DE_LA_ESPECIALIDAD", "DOMINI DE L'ESPECIALITAT");
define("STR_PRISMA_DOMINIO_DE_LA_ESPECIALIDAD_TXT", "Domini tècnic o professional del treball. Curiositat o interès en la seva actualització.");
define("STR_PRISMA_ANALISIS_TXT", "Analitza aspectes i problemes en detall, de manera sistemàtica, emetent judicis sòlids basats en informació rellevant.");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_1BR", "GARANTIA I PROMOCIÓ <br /> DE LA QUALITAT");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_TXT", "Demostra interès pels objectius i criteris de qualitat, garantint l'compliment dels procediments i normes establerts.");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA", "ORDRE I SISTEMÀTICA");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_TXT", "Realitza les tasques de forma estructurada i organitzada, procurant mantenir el seu entorn de treball ordenat.");
define("STR_PRISMA_ORIENTACION_AL_LOGRO", "ORIENTACIÓ A L'ASSOLIMENT");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_TXT", "Es marca objectius i metes complexes i treballa de forma constant i amb perseverança en la consecució.");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_CAMBIOS_Y_MEJORAS", "INNOVACIÓ I CREATIVITAT");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_CAMBIOS_Y_MEJORAS_TXT", "Aporta nous i creatius punts de vista en el treball. Identifica aspectes originals i tendeix a superar les resistències tradicionals.");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION_BR", "ORIENTACIÓ A L'ACCIÓ <br /> I DECISIÓ");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION_TXT", "Pren decisions àgils, busquen la practicitat i operativitat de les coses.");
define("STR_PRISMA_VISION_ESTRATEGICA", "VISIÓ ESTRATÈGICA");
define("STR_PRISMA_VISION_ESTRATEGICA_TXT", "Actua amb visió de futur, marcant objectius a mig i llarg termini i identificant les possibles conseqüències de les seves propostes.");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL", "HABILITAT INTERPERSONAL");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_TXT", "Es relaciona positiva i constructivament amb els altres. És considerat i treballa eficaçment en equip.");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION", "FLEXIBILITAT I ADAPTACIÓ");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_TXT", "S'adapta amb facilitat a les demandes de canvis laborals, a contextos variats.");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_1BR", "RESISTÈNCIA A LA FATIGA <br /> I A L'ESTRÈS");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_TXT", "Manté pautes de conducta estables davant dificultats i pressions. Té un eficaç control de si mateix.");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO_BR", "ENERGIA INTERNA");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO_TXT", "Motivació interna per afrontar els reptes amb energia, optimisme, perseverança i ambició.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA", "SÍNTESI DEL PERFIL DE COMPETÈNCIES PRISM @");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P1", "Aquest Perfil descriu com es comporta un / a candidat / a en les principals situacions laborals, d'acord amb una sèrie de competències.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P2", "El tipus de qüestionari de Personalitat Laboral al qual el / la candidat / a ha respost, obliga a triar entre 3 frases que reflecteixen conductes o situacions laborals, la que millor i la que pitjor li descriu. Amb aquest mètode, no pot aconseguir altes puntuacions en totes les competències. ");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P3", "El perfil que presentem a continuació ha de ser considerat com un indicador orientatiu de les seves competències més forts i les que podria desenvolupar, en base a les prioritzacions que ha anat realitzant en les seves respostes.");
define("STR_PRISMA_CLAVE_DE_MEJORA", "CLAU DE <br /> MILLORA");
define("STR_PRISMA_POTENCIAL_DESARROLLO", "POTENCIAL <br /> DESENVOLUPAMENT");
define("STR_PRISMA_AREA_DE_DESARROLLO_BR", "ÀREA DE <br /> DESENVOLUPAMENT");
define("STR_PRISMA_POTENCIAL_FORTALEZA", "POTENCIAL <br /> FORTALESA");
define("STR_PRISMA_AREA_DE_FORTALEZA", "ÀREA DE <br /> FORTALESA");
define("STR_PRISMA_AREA_DE_BR_FORTALEZA", "ÀREA DE <br /> FORTALESA");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD", "GARANTIA I PROMOCIÓ DE LA QUALITAT");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD", "INNOVACIÓ I CREATIVITAT");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION", "ORIENTACIÓ A L'ACCIÓ I DECISIÓ");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES", "RESISTÈNCIA A LA FATIGA I AL ESTRÈS");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO", "ENERGIA INTERNA");
define("STR_PRISMA_PERFIL_DE_ESTILOS", "PERFIL D'ESTILS");
define("STR_PRISMA_PERFIL_DE_ESTILOS_TXT", "Aquest informe recull l'estil o els estils predominants de la persona que ha respost el qüestionari, quan dirigeix ​​un equip, quan es relaciona amb el seu cap i quan treballa en grup, d'acord amb el perfil de personalitat obtingut . ");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO", "ESTILS DE LIDERATGE");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO_P1", "Kenneth Blanchard a partir de l'estudi de la conducta dels líders en situacions diverses, crea la teoria del lideratge situacional. Aquesta teoria es basa en dues dimensions crítiques del comportament del líder: quantitat de direcció (conducta de tasca ) i quantitat de suport socioemocional (conducta de relació) que el líder ha de proporcionar en una situació arran del \"nivell de maduresa dels seus col · laboradors \".");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO_P2", "Aquest informe, mostra quins són els estils preferents de comandament a partir del perfil de personalitat laboral obtingut. S'identifiquen els estils que solen adoptar per manar, coordinar o dirigir als seus col · laboradors. A més explica en què consisteix cada un d'aquests estils predominants, tenint en compte altres casos similars, especialment en els que pot ser més eficaç. ");
define("STR_PRISMA_ESTILOS_DE_COLABORACION", "ESTILS DE COL · LABORACIÓ");
define("STR_PRISMA_ESTILOS_DE_COLABORACION_P1", "Per a cada un dels estils de lideratge és possible definir un estil de col · laboració complementari. Per exemple, un col · laborador submís probablement s'adequarà en major grau a un Líder directiu, que algú que és més autosuficient.") ;
define("STR_PRISMA_ESTILOS_DE_COLABORACION_P2", "Aquest informe descriu el o els estils preferits o més freqüents de col · laboració basats en el perfil de personalitat laboral obtingut. També identifica els estils amb menys preferència o freqüència quan és dirigit per altres o sota certes circumstàncies.") ;
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO", "ESTILS DE COMPORTAMENT EN EQUIP");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO_P1", "Dins dels equips, es poden adoptar diferents rols o estils de comportament, sent cada un d'ells important per garantir un bon acompliment grupal.");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO_P2", "Aquest informe reflecteix el o els estils preferits o més freqüents de comportament en equip basats en el perfil laboral obtingut pel / per la candidat / a. També identifica els estils amb menys preferència quan treballa amb altres o sota certes circumstàncies. ");
define("STR_PRISMA_LIDERAZGO", "LIDERATGE");
define("STR_PRISMA_CASI_NUNCA_SERA", "Gairebé <br /> mai <br /> serà");
define("STR_PRISMA_RARAS_VECES_SERA", "Rares <br /> vegades <br /> serà");
define("STR_PRISMA_PUEDE_SER", "Pot <br /> ser");
define("STR_PRISMA_ALGUNAS_VECES_SERA", "Algunes <br /> vegades <br /> serà");
define("STR_PRISMA_CASI_SIEMPRE_SERA", "Gairebé <br /> sempre <br /> serà");
define("STR_PRISMA_DIRECTIVO", "Directiu");
define("STR_PRISMA_DIRECTIVO_P1", "- Assumeix tota la responsabilitat de la presa de decisions.");
define("STR_PRISMA_DIRECTIVO_P2", "- Planifica estableix prioritats, distribueix les tasques i controla.");
define("STR_PRISMA_DIRECTIVO_P3", "- Orientat a metes i resultats.");
define("STR_PRISMA_DELEGADOR", "Delegat");
define("STR_PRISMA_DELEGADOR_P1", "- Delega en el seu equip les tasques i la presa de decisions.");
define("STR_PRISMA_DELEGADOR_P2", "- Lliurament dels treballs i deixa que el seu equip assumeixi la resposabilidad.");
define("STR_PRISMA_DELEGADOR_P3", "- Només supervisa resultats.");
define("STR_PRISMA_NEGOCIADOR", "Negociador");
define("STR_PRISMA_NEGOCIADOR_P1", "- Negociació i persuadeix als seus col · laboradors per aconseguir compromisos i col · laboració.");
define("STR_PRISMA_NEGOCIADOR_P2", "- Ofereix contraprestacions per aconseguir acords.");
define("STR_PRISMA_NEGOCIADOR_P3", "- Ven les decisions al seu equip.");
define("STR_PRISMA_CONSULTIVO", "Consultiu");
define("STR_PRISMA_CONSULTIVO_P1", "- Consulta i sondeja les opinions dels altres, però decideix amb independència i seguretat.");
define("STR_PRISMA_CONSULTIVO_P2", "- Té en compte les aportacions del seu equip però no delega la presa de decisions.");
define("STR_PRISMA_DEMOCRATICO", "Democràtic");
define("STR_PRISMA_DEMOCRATICO_P1", "- Orientat / a al grup. Dóna cohesió, dóna suport i motiva els seus col · laboradors.");
define("STR_PRISMA_DEMOCRATICO_P2", "- Fomenta la participión de l'equip en la presa de decisions.");
define("STR_PRISMA_DEMOCRATICO_P3", "- Prefereix el consens a prendre decisions per si mateix / a.");
define("STR_PRISMA_COLABORACION", "COL · LABORACIÓ");
define("STR_PRISMA_AUTOSUFICIENTE", "Autosuficient");
define("STR_PRISMA_AUTOSUFICIENTE_P1", "- Li agrada treballar amb autonomia i alt grau de llibertat.");
define("STR_PRISMA_AUTOSUFICIENTE_P2", "- Té les seves pròpies idees i li agrada posar-les en pràctica.");
define("STR_PRISMA_AUTOSUFICIENTE_P3", "- Actua sense necessitat de consultar a altres.");
define("STR_PRISMA_SUMISO", "Submís");
define("STR_PRISMA_SUMISO_P1", "- Li agrada que li marquin directrius, procediments i instruccions concretes per realitzar-la.");
define("STR_PRISMA_SUMISO_P2", "- Prefereix que decideixin per ell / a.");
define("STR_PRISMA_SUMISO_P3", "- Es s'até a les normes, la disciplina i el manat.");
define("STR_PRISMA_COMPLICE", "Còmplice");
define("STR_PRISMA_COMPLICE_P1", "- Per fer la seva feina necessita arguments que li convencin.");
define("STR_PRISMA_COMPLICE_P2", "- Respon amb seguretat a les propostes que li fan.");
define("STR_PRISMA_COMPLICE_P3", "- Negocia amb els seus caps les alternatives i solucions buscant la situació més avantatjosa.");
define("STR_PRISMA_INFORMADOR", "Informador");
define("STR_PRISMA_INFORMADOR_P1", "- Li agrada ser consultat / ai ser considerat / a com a expert / a, encara que no busca prendre la decisió final.");
define("STR_PRISMA_INFORMADOR_P2", "- Analitza críticament, aportant el seu assessorament amb independència.");
define("STR_PRISMA_PARTICIPATIVO", "Participatiu");
define("STR_PRISMA_PARTICIPATIVO_P1", "- Li agrada aportar idees al grup i col · laborar amb els seus caps quan se'ls requereix o consulta.");
define("STR_PRISMA_PARTICIPATIVO_P2", "- S'implica en la solució de problemes i en la presa de decisions.");
define("STR_PRISMA_COMPORTAMIENTO_EN_EQUIPO", "COMPORTAMENT EN EQUIP");
define("STR_PRISMA_COORDINADOR", "Coordinador");
define("STR_PRISMA_COORDINADOR_P1", "- Calmat / a, segur / a de si mateix / a, controlat / a, madur / ai confiat / a.");
define("STR_PRISMA_COORDINADOR_P2", "- Estableix objectius i defineix tasques. Coordina els esforços i contribucions de l'equip, promovent la presa de decisions i aclarint les metes.");
define("STR_PRISMA_COORDINADOR_P3", "- Tendeix a delegar les tasques i pot ser considerat una mica manipulador o ineficient.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS", "Constructor <br /> d'Equips");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P1", "- Cooperador / a, afable, perceptiu / a, diplomàtic / a, orientat / a socialment, sensible.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P2", "- Promou l'harmonia entre els equips. Hàbil per respondre a les persones i situacions. Promou l'esperit d'equip.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P3", "- Pot mostrar indecís / a en situacions de crisi. Pot demostrar poca autoafirmació.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS", "Investigador <br /> de Recursos");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P1", "- extravertit / a, entusiasta, comercial, curiós / a, comunicatiu / a.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P2", "- Cerca noves oportunitats i desenvolupa contactes. Alta capacitat per relacionar-se amb la gent i per explorar el nou. Habilitat per respondre als reptes.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P3", "- Perd fàcilment l'interès quan l'entusiasme inicial ha desaparegut.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P4", "- Pot arribar a ser massa optimista.");
define("STR_PRISMA_IMPULSOR_ENERGETICO", "Impulsor <br /> Energètic");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P1", "- Dinàmic / a, energètic / a, tens / a, amb empenta, simpàtic / a.");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P2", "- Repta a les persones i treballa bé sota pressió. Té empenta i coratge per superar els obstacles. Qüestiona la inèrcia i la ineficiència.");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P3", "- Pot ser provocador / a, mancat de tacte o amb duresa. Pot demostrar irritació o impaciència. Pot ser considerat / a com a persona autocrítica.");
define("STR_PRISMA_APLICADOR", "Aplicador");
define("STR_PRISMA_APLICADOR_P1", "- Metòdic / a, constant, complidor / a del deure, conservador / a, predictible.");
define("STR_PRISMA_APLICADOR_P2", "- Converteix les decisions o polítiques en objectius concrets, realitza seguiment per assolir els objectius.");
define("STR_PRISMA_APLICADOR_P3", "- Una cosa inflexible. Pot tenir lentitud a l'hora de respondre als canvis o innovacions.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR", "Analitzador <br /> Avaluador");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P1", "- Sobri / a, flegmàtic / a, prudent, seriós / a, perspicaç, estrateg.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P2", "- Ofereix ponderació, reflexió i anàlisi, criteri i discreció. Pot percebre les diverses opcions i jutjar amb més exactitud.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P3", "- Pot no tenir iniciativa o d'habilitat per inspirar o motivar els altres. És gairebé crític / a.");
define("STR_PRISMA_CREATIVO", "Creatiu");
define("STR_PRISMA_CREATIVO_P1", "- Imaginatiu / a, independent, heterodox / a, generador / a d'idees.");
define("STR_PRISMA_CREATIVO_P2", "- Pot ser brillant i profund / a en els seus enfocaments. Resol problemes difícils amb genialitat i / o intel · ligència.");
define("STR_PRISMA_CREATIVO_P3", "- Pot descuidar amb facilitat els detalls i / o el protocol. Pot ser dispers / ao poc constant.");
define("STR_PRISMA_PERFECCIONISTA", "Perfeccionista");
define("STR_PRISMA_PERFECCIONISTA_P1", "- Detallista, minuciós / a, complidor / a del deure, dedicat / a, conscienciós / a.");
define("STR_PRISMA_PERFECCIONISTA_P2", "- Sol aplicar coneixements i tècniques especialitzades. Alta capacitat i interès per completar les coses. Intolerant amb la desídia o manca de qualitat.");
define("STR_PRISMA_PERFECCIONISTA_P3", "- Es preocupa molt quan les coses no van bé. bastate reticent / aa delegar.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL", "PERFIL COMPETÈNCIA EMOCIONAL");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P1", "La tolerància general de l'estrès i la gestió eficaç d'emocions, són dos elements crítics en les relacions professionals i per tant, en l'adaptació d'un professional al seu lloc o entorn professional.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P2", "Les negociacions, les relacions amb clients, col · laboradors, la gestió de conflictes, les possibles pressions normals del treball requereixen d'una sèrie de competències i controls emocionals, que, depenent del perfil personal laboral poden ser-hi més o menys efectius. ");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P3", "En el gràfic, les zones ombrejades ens indiquen la necessitat de fer una anàlisi més profunda del perfil i context del lloc.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P4", "Les combinacions entre puntuacions extremes (zones ombrejades), ens indiquen la necessitat d'aprofundir en l'entrevista de selecció i / o desenvolupament professional per analitzar possibles repercussions segons les exigències del context laboral o de les responsabilitats del lloc o funció. ");
define("STR_PRISMA_CONFIANZA_EN_OTROS", "Confiança en altres");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES", "PERFIL D'ESTRESORS POTENCIALS");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P1", "Aquest informe ens orienta sobre les possibles activitats, circumstàncies o condicions específiques que poden suposar una font més important d'estrès per al professional que ha contestat al qüestionari.");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P2", "En el perfil, apareixeran els factors que poden generar més probabilitat d'estrès (9-10), o probabilitat relativament alta (7-8 ).");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P3", "Les puntuacions mitjanes (4,5,6) o baixes (1,2) no impliquen indiferència per part del professional. Simplement no semblen ser en l'actualitat font probable d'estrès.");
define("STR_PRISMA_FACTORES_ORGANIZATIVOS", "FACTORS ORGANITZATIUS");
define("STR_PRISMA_TRABAJO_RUTINARIO_Y_REPETITIVO", "TREBALL RUTINARI I REPETITIU");
define("STR_PRISMA_CAMBIOS_FRECUENTES", "CANVIS FREQÜENTS");
define("STR_PRISMA_ESTRUCTURAS_BUROCRATICAS", "ESTRUCTURES BUROCRÀTIQUES");
define("STR_PRISMA_ENTORNOS_REACTIVOS", "ENTORNS REACTIUS");
define("STR_PRISMA_FACTORES_RELACIONALES", "FACTORS RELACIONALS");
define("STR_PRISMA_HABLAR_EN_PUBLICO", "PARLAR EN PÚBLIC");
define("STR_PRISMA_VENDER_NEGOCIAR", "VENDRE / NEGOCIAR");
define("STR_PRISMA_DAR_MALAS_NOTICIAS", "DONAR MALES NOTÍCIES");
define("STR_PRISMA_FACTORES_MOTIVACIONALES", "FACTORS MOTIVACIONALS");
define("STR_PRISMA_FALTA_DE_PODER", "MANCA DE PODER");
define("STR_PRISMA_FALTA_DE_APOYO_SOCIAL", "MANCA DE SUPORT SOCIAL");
define("STR_PRISMA_FALTA_DE_AUTONOMIA", "MANCA D'AUTONOMIA");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL", "MANCA DE PROGRÉS PROFESSIONAL");
define("STR_PRISMA_ESCASOS_RETOS_INTELECTUALES", "ESCASSOS REPTES INTEL · LECTUALS");
define("STR_PRISMA_FALTA_DE_RECONOCIMIENTO", "MANCA DE RECONEIXEMENT");
define("STR_PRISMA_FACTORES_DEL_PUESTO_DE_TRABAJO", "FACTORS DEL LLOC DE TREBALL");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES", "PRESA DE DECISIONS RÀPIDES / DIFÍCILS");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS", "SOLUCIÓ DE PROBLEMES COMPLEXOS");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO", "FORTES RESTRICCIONS DE TEMPS");
define("STR_PRISMA_AMBIENTE_COMPETITIVO", "AMBIENT COMPETITIU");
define("STR_PRISMA_DIRIGIR_A_OTROS", "DIRIGIR A ALTRES");
define("STR_PRISMA_DEFINICION_DE_LOS_FACTORES_ESTRESORES", "DEFINICIÓ DELS FACTORS ESTRESSORS");
define("STR_PRISMA_TRABAJO_RUTINARIO_Y_REPETITIVO_DEF", "Treballs sense varietat de tasques predictibles, sense canvis, en el que sempre es fa el mateix o de la mateixa manera.");
define("STR_PRISMA_CAMBIOS_FRECUENTES_DEF", "Canvis freqüents o inesperats en els continguts, sistemes o pràctiques de treball. Incertesa associada a canvis en responsabilitats, en funcions o requeriments del lloc de treball.");
define("STR_PRISMA_ESTRUCTURAS_BUROCRATICAS_DEF", "Excés de normes i / o procediments. Normatives exigents, controls, burocràcia o paperassa exigits.");
define("STR_PRISMA_ENTORNOS_REACTIVOS_DEF", "Necessitat de resposta urgent o reacció immediata, sense oportunitat de planificació prèvia. Entorns impredictibles o que exigeixen solució de problemes a mesura que sorgeixen. Canvis constants en les prioritats.");
define("STR_PRISMA_HABLAR_EN_PUBLICO_DEF", "Haver de comunicar o realitzar presentacions davant d'un públic o auditori. Situacions que exigeixin manejar-se o relacionar-se davant gent desconeguda o davant grups grans.");
define("STR_PRISMA_VENDER_NEGOCIAR_DEF", "Situacions que exigeixin vendre idees, productes o serveis. Haver de defensar o convèncer als altres o portar negociacions difícils amb clients, proveïdors, sindicats, etc.");
define("STR_PRISMA_DAR_MALAS_NOTICIAS_DEF", "Haver de donar males notícies, informacions negatives o desagradables (a clients, col · legues o col · laboradors). Haver de comunicar o implementar programes amb els que les persones poden sentir-se o reaccionar malament.");
define("STR_PRISMA_CONFLICTOS_INTERPERSONALES", "CONFLICTES INTERPERSONALS");
define("STR_PRISMA_CONFLICTOS_INTERPERSONALES_DEF", "Situacions de discussió o desacuerdo.Ambientes en què hi hagin relacions conflictives o de difícil convivència. Situacions en les qeu hagi denfrontar-se o resoldre conflictes o desacords amb altres persones.");
define("STR_PRISMA_FALTA_DE_PODER_DEF", "Manca de poder o autoritat per fer que les coses es facin o per aconseguir els objectius del grup. Carència de responsabilitats sobre projectes o persones.");
define("STR_PRISMA_FALTA_DE_APOYO_SOCIAL_DEF", "Situacions en les que hagi de prendre decisions o iniciar accions discutibles, impopulars o en les quals no hi ha acord, aprovació del grup o consens amb altres persones.");
define("STR_PRISMA_FALTA_DE_AUTONOMIA_DEF", "Manca de llibertat per actuar i / o decidir criteris personals. Situacions en les quals no es pot actuar per un mateix, havent de dependre d'altres.");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL_BR", "MANCA DE PROGRÉS <br /> PROFESSIONAL");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL_BR_DEF", "Lloc de treball en el que no s'afavoreix havent de i desenvolupament de carrera. Absència de promoció i de carrera professional. Manca d'oportunitats de superació.");
define("STR_PRISMA_ESCASOS_RETOS_INTELECTUALES_DEF", "Treball lineal on no s'exigeix un esforç intel · lectual. Poques possibilitats d'aprofundiment en els temes, llocs sense especialització o poc tècnics.");
define("STR_PRISMA_FALTA_DE_RECONOCIMIENTO_DEF", "Inexistència del reconeixement o absència de reconeixement formal. Absència de premis o recompenses encara que s'aconsegueixin èxits.");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES_BR", "PRESA DE DECISIONS <br /> RÀPIDES / DIFÍCILS");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES_BR_DEF", "Situacions que exigeixen prendre decisions immediates o actuar amb gran rapidesa. Temps limitat per reflexionar.");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS_BR", "SOLUCIÓ DE PROBLEMES <br /> COMPLEXOS");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS_BR_DEF", "Llocs amb alta exigència intel · lectual, amb molta informació o anàlisi de dades, ràtios o informes exhaustius.");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO_BR", "FORTES RESTRICCIONS <br /> DE TEMPS");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO_BR_DEF", "Llocs que requereixen un ritme molt alt d'activitat, amb paralitzacions o interrupcions que dificulten l'acompliment dels terminis o compromisos.");
define("STR_PRISMA_AMBIENTE_COMPETITIVO_DEF", "Treballs on s'hagi de competir amb altres companys, situacions de venda agressiva, o bè on hi hagi comparació contínua de resultats.");
define("STR_PRISMA_DIRIGIR_A_OTROS_DEF", "Funcions i / o llocs que requereixen tenir persones a càrrec i a les quals s'ha de manar, controlar i / o supervisar.");
define("STR_PRISMA_INDICADORES_DE_AJUSTE_A_LAS_COMPETENCIAS", "INDICADORS D'AJUST A LES COMPETÈNCIES");
define("STR_PRISMA_DEFINICION_DE_LAS_COMPETENCIAS", "DEFINICIÓ DE LES COMPETÈNCIES");
define ("STR_PRISMA_NOMBRE_INFORME_TXT", "Perfil de<br /><strong>personalitat<br />laboral</ strong>");
define("STR_PRISMA_NOMBRE_INFORME_NARRATIVO_TXT", "Informe Narratiu Expert");
define("PRISMA_NARRATIVO_INTP1", "Aquest informe està basat en les respostes de el / la Sr / Sra. @ usuari @ a un qüestionari d'autoavaluació: el qüestionari de competències i personalitat laboral Prisma. Aquest qüestionari el convida a descriure el seu comportament, preferències i actituds en relació a diferents aspectes de la seva vida laboral. ");
define("PRISMA_NARRATIVO_INTP2", "Durant el mateix, ha hagut de triar l'afirmació que més s'ajusta, i la que menys, entre blocs de tres comportaments possibles. Les seves respostes s'han comparat amb les d'un grup ampli i rellevant per obtenir un perfil de les preferències percebudes del / la Sr / Sra. @ usuari @ respecte a les diferents maneres de comportar-se en el treball, agrupades en 4 àrees principals: Energies i motivacions, control emocional i Tolerància al Estrès, Orientació a la relació ia les persones, Estil de pensament i potencial de recursos mentals. ");
define("PRISMA_NARRATIVO_INTP3", "Aquest informe descriu el perfil de personalitat del / la Sr / Sra. @ usuari @ i s'ha de tractar com a confidencial. En considerar els resultats del qüestionari, és important tenir en compte que representa la seva pròpia visió i el manera com percep les seves pròpies conductes, en lloc de la manera com terceres persones podrien descriure la seva personalitat. La precisió d'aquest informe depèn de la franquesa i sinceritat amb la que es va completar el qüestionari, així com del seu propi autoconeixement. Per tant , els comentaris que es realitzen en aquest informe s'han de considerar com una cosa orientatiu, fiable, encara que no infal · lible. Aquest autoinforme pot proporcionar importants indicadors sobre l'estil propi del / de la Sr / Sra. @ usuari @ a la feina, i és probable que ens permeti predir en gran manera el seu comportament en diferents situacions. ");
define("PRISMA_NARRATIVO_INTP4", "Tingueu en compte que el qüestionari descriu l'estil de conducta que prefereix el / la Sr / Sra. @ usuari @, però no les seves capacitats. Els comentaris aporta una descripció àmplia del seu estil actual i, per tant, l'informe és necessàriament general. La vida útil de les dades contingudes en l'informe es considera que està entre 18 i 24 mesos, en funció de les circumstàncies personals i el lloc de treball. Si s'han produït canvis significatius en la seva vida o si hi ha un canvi significatiu en el lloc, hauria de tornar a completar el qüestionari. ");
define("PRISMA_NARRATIVO_INTP5", "Si el preocupa alguna cosa amb relació al contingut d'aquest informe, aneu a algú que hagi rebut una formació completa en l'ús del qüestionari Prisma.");
define("STR_ESTILO_ORENTACION_NARR_PRISMA", "ESTIL D'ORIENTACIÓ A LA RELACIÓ IA LES PERSONES");
define("STR_ESTILO_PENSAMIENTO_NARR_PRISMA", "ESTIL DE PENSAMENT I RECURSOS MENTALS");
define("STR_NUM_PREGUNTAS_ERRONEAS", "Nombre de preguntes errònies");
define("STR_NUM_PREGUNTAS_BLANCO", "Nombre de preguntes en blanc");
define("STR_VOCABULARIO", "VOCABULARI");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_AL_VOCABULARIO", "Nombre total de preguntes referents al vocabulari");
define("STR_GRAMATICA", "GRAMÀTICA");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_GRAMATICA", "Nombre total de preguntes referents a gramàtica");
define("STR_COMPRENSION", "COMPRENSIÓ");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_COMPRENSION", "Nombre total de preguntes referents al comprensió");
define("STR_PRISMA_ESCALAS_DIFERENCIALES", "ESCALES DIFERENCIALS");
define("STR_CIP_NOMBRE_INFORME_TXT", "<strong> Inventari de <br /> Orientació <br /> Professional CIP </ strong>");
define("STR_CIP_BIENVENIDO_INFORME_ORIENTACION_PROFESIONAL_TXT", "Benvingut / a a l'Informe d'Orientació Professional");
define("STR_CIP_INTRO_P1", "Aquest informe ha estat elaborat a partir de les respostes i exercicis realitzats per @ candidato_prueba @. <br /> <br /> L'objectiu essencial d'aquest informe és donar suport al procés d'orientació per @ candidato_prueba @ sobre les professions i / o carreres professionals en les quals ha demostrat especial interès i / o preferència al llarg de les respostes donades al qüestionari CIP, i ajudar-lo a conèixer millor les capacitats que podrien afavorir l'èxit en la seva elecció o que, pel contrari, podrien implicar algun grau de dificultat. ");
define("STR_CONTENIDO_DEL_INFORME", "Continguts de l'informe");
define("STR_APARTADO_1", "Apartat 1: ÀREES PROFESSIONALS PREFERENTS");
define("STR_CIP_INTRO_P2", "A la primera part de l'informe, es representa el gràfic que identifica el grau d'interès (en percentatge) que ha mostrat la persona cap als camps professionals i / o carreres professionals generals associades que s'han valorat. < br /> <br /> Aquest gràfic s'acompanya d'una breu síntesi escrita identificant, segons les dades quantitatives obtingudes, les carreres i / o activitats que serien prioritàries i més motivants per @ candidato_prueba @. ");
define("STR_APARTADO_2", "Apartat 2: ÀREA APTITUDS");
define("STR_CIP_INTRO_P3", "En aquest apartat, apareixen representades les puntuacions obtingudes en els tests d'aptituds realitzats pel / la estudiant (rendiment a la prova) en una escala de percentils. Aquesta puntuació final representa el percentil obtingut (representat de 0 a 100) o el que és el mateix, la comparativa dels resultats obtinguts amb una mostra significativa d'estudiants de similar edat i característiques acadèmiques. ");
define("STR_APARTADO_3", "Apartat 3: ORIENTACIÓ PROFESSIONAL");
define("STR_CIP_INTRO_P4", "En aquest apartat s'integra la informació relativa a les carreres o activitats associades a les capacitats en què @ candidato_prueba @ ha demostrat tenir especial fortalesa i aquelles que, pel rendiment obtingut, podrien indicar algun tipus de dificultat . <br /> <br /> La motivació per un àmbit concret d'activitat professional constitueix un element essencial per a l'èxit posterior. Tanmateix, el que la persona tingui determinades capacitats o aptituds, afavoreix i incrementa les possibilitats de ràpida assimilació i aprenentatge de conceptes i / o habilitats associades a les carreres i professions en les que voldria treballar a futur. <br /> <br /> La integració entre ambdós aspectes permet una visió molt rica per poder prendre decisions adequades. Per això, l'informe ens aporta una interpretació qualitativa que associa ambdós paràmetres (Interès + Capacitat) per conèixer amb més exactitud les potencialitats de @ candidato_prueba @. ");
define("STR_INTEGRACION", "Integració");
define("STR_CIP_INTRO_P5", "Amb vista a l'orientació, és important tenir sempre en compte que la motivació o interès (vocació) per un àmbit concret d'activitat professional constitueix un element essencial per a l'èxit posterior (1 ª part de l'Informe o Gràfic de Àrees Professionals preferents del CIP). <br /> <br /> Però el que la persona tingui determinades capacitats o aptituds, afavoreix i incrementa les possibilitats de ràpida assimilació i aprenentatge de conceptes i / o habilitats associades a les carreres i professions en les que s'han d'aplicar. <br /> <br /> La integració entre els dos aspectes, ens pot donar una orientació molt rica per poder prendre decisions adequades. Per això, l'informe ens aporta una interpretació qualitativa que associa ambdós paràmetres ( Interès + Capacitat) per conèixer amb més exactitud les potencialitats de @ candidato_prueba @. ");
define("STR_PRUEBAS_ADMISION_NIVEL_GRADO"						, "Pruebas Admisión Nivel Grado");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_105"			, "Perfil de Competències");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_128"			, "Perfil de Competències");
define("STR_105_DETALLE DIMENSIONES_COMPETENCIAS"					, "DETALLE DIMENSIONES POR CADA UNA DE LAS COMPETENCIAS");
define("STR_105_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "A continuación, se muestra el detalle de las puntuaciones obtenidas en cada una de las dimensiones que componen a su vez las Competencias de Banco Hipotecario.");

define("STR_128_DETALLE DIMENSIONES_COMPETENCIAS"					, "DETALLE DIMENSIONES POR CADA UNA DE LAS COMPETENCIAS");
define("STR_128_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "A continuación, se muestra el detalle de las puntuaciones obtenidas en cada una de las dimensiones que componen a su vez las Competencias de Asitur.");

define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario CEL16 con respecto a los comportamientos del CEL16 asociados a la definición de las Competencias de Banco Hipotecario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P2"	, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P3"	, "El cuestionario CEL16 obliga a la persona que lo responde a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no se puede lograr altas puntuaciones en todas las competencias.");

define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario CEL16 con respecto a los comportamientos del CEL16 asociados a la definición de las Competencias de Asitur.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P2"	, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P3"	, "El cuestionario CEL16 obliga a la persona que lo responde a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no se puede lograr altas puntuaciones en todas las competencias.");
define("STR_SR_A"                         , "Sr/a");
?>
