<?php
//TEXTOS EN INFORMES
define("STR_PIE_INFORMES" 												, "La reproducción total o parcial de este Informe por cualquier medio, infringe los derechos de Copyright.");
define("STR_PIE_INFORMES_PASCUAL" 										, "Psicólogos Empresariales y Asociados SA.");
define("STR_NOMBRE_APELLIDOS"											, "Nombre y Apellidos");
define("STR_FECHA_INFORME"												, "Fecha del Informe");
define("STR_FECHA_INFORME_DIAN"											, "Fecha finalización");
define("STR_IDENTIFICADOR"												, "Número de Cédula");
define("STR_INTRODUCCION" 												, "Introducción");
define("STR_INTRODUCCION_CAPS" 											, "INTRODUCCIÓN");
define("STR_PUNTUACION_DIRECTA" 										, "Puntuación Directa");
define("STR_PUNTUACION_PERCENTIL" 										, "Puntuación Percentil");
define("STR_INDICE_RAPIDEZ" 											, "Índice de Rapidez");
define("STR_INDICE_PRECISION" 											, "Índice de Precisión");
if (!defined('STR_PRODUCTO_RENDIMIENTO')) {
	define("STR_PRODUCTO_RENDIMIENTO"						, "Producto Rendimiento");
}
define("STR_ESTILO_PROCESAMIENTO_MENTAL" 								, "Estilo de Procesamiento Mental");
define("STR_NUM_TOTAL_PREGUNTAS" 										, "Número total de preguntas del Test");
define("STR_NUM_PREGUNTAS_ACERTADAS" 									, "Número de preguntas acertadas (P.D.)");
define("STR_PUNT_INFORMES" 												, "Puntuación");
define("STR_BAJO_POTENCIAL" 											, "BAJO POTENCIAL");
define("STR_MEDIO_POTENCIAL" 											, "MEDIO POTENCIAL");
define("STR_ALTO_POTENCIAL" 											, "ALTO POTENCIAL");
define("STR_ESTE_INFORME_REPRESENTA" 									, "Este informe presenta la siguiente información en base a los resultados obtenidos tras la realización del Test:");
define("STR_EXP_PUNT_PECENTIL" 											, "Indica el porcentaje de sujetos que ha obtenido una puntuación inferior. Por ejemplo, el percentil 35 es la puntuación que deja por debajo el 35% de los sujetos del grupo.");
define("STR_EXP_PUNT_DIRECTA" 											, "Se refiere al número de preguntas contestadas correctamente.");
define("STR_EXP_INDICE_RAPIDEZ" 										, "La rapidez está en la base del aprendizaje y de la aptitud. Este índice se obtiene en base al número de preguntas contestadas en un espacio de tiempo limitado.");
define("STR_EXP_INDICE_PRECISION" 										, "Representa la calidad frente a la cantidad que sería la rapidez. Este índice se obtiene en función del número de preguntas acertadas en un espacio de tiempo limitado.");
define("STR_EXP_PRODUCTO_RENDIMIENTO" 									, "Representa la interacción entre rapidez-precisión o precisión-rapidez, poniendo el énfasis en una u otra según el estilo o la actitud de cada uno.");
define("STR_EXP_ESTILO_PROCESAMIENTO_MENTAL"		 					, "En base al análisis de los índices de rapidez y precisión, se puede determinar cuál es el estilo o mapa mental de la persona. Conocer su estilo de procesamiento ayuda a determinar en qué tipo de tareas o actividades va a tener un mayor rendimiento.");
define("STR_PRISMA_INTRO_P1" 											, "Este informe está basado en las respuestas de la persona que ha respondido a PRISM@. Ha sido generado automáticamente desde la Plataforma Test Station de Psicólogos Empresariales.");
define("STR_PRISMA_INTRO_P2" 											, "Psicólogos Empresariales sólo se hace responsable de su versión original y no de posibles modificaciones o anexos que se puedan realizar como versión o informes posteriores derivados de otras percepciones sobre la persona que ha realizado el cuestionario.");
define("STR_PRISMA_INTRO_P3" 											, "El Perfil General tiene 32 escalas. Estas escalas se agrupan en 9 factores que corresponden a 4 grandes áreas de la personalidad laboral:");
define("STR_PRISMA_INTRO_P4" 											, "- ENERGÍAS Y MOTIVACIONES.");
define("STR_PRISMA_INTRO_P5" 											, "- CONTROL EMOCIONAL Y TOLERANCIA AL ESTRÉS.");
define("STR_PRISMA_INTRO_P6" 											, "- ESTILOS DE RELACIÓN (Orientación a la relación, a las personas e Influencia, ascendencia y mando).");
define("STR_PRISMA_INTRO_P7" 											, "- ESTILOS DE PROCESAMIENTO MENTAL (Competencias analíticas, Potencial de Recursos Mentales, Flexibilidad y Estilo de Trabajo).");
define("STR_PRISMA_INTRO_P8" 											, "Los demás informes expertos de Competencia y Perfiles derivados, son opcionales y se describen de manera independiente.");
define("STR_PRISMA_INTRO_P9" 											, "Recomendamos que, a la hora de interpretar los resultados de los informes, siempre se tengan en consideración las puntuaciones de consistencia obtenidas.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA"					, "INTERPRETACIÓN DE LA ESCALA DE CONSISTENCIA");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P1"				, "La Escala de Consistencia nos proporciona información sobre el estilo de respuesta o actitud del profesional que ha respondido al cuestionario. Al ser un cuestionario de \"respuesta obligada\", se reduce la posible \"distorsión motivacional\" o tendencia a dar un perfil deseado o conveniente.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P2"				, "Por tanto, la puntuación en la escala Consistencia expresa \"el grado en que la persona se ha esforzado por mantener la coherencia\" al responder al cuestionario.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P3A"				, "Consistencia Alta (9-10)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P3B"				, " Tan alta congruencia puede indicar posible manipulaci&oacute;n o deseo de dar una imagen determinada de s&iacute; mismo/a.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P4A"				, "Consistencia Baja (1-2)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P4B"				, " Tan baja congruencia puede indicar que la persona ha dado muchas respuestas al azar por no comprender las instrucciones, falta de implicación o de autoanálisis.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P5A"				, "Consistencias Ligeramente medias (3-4 y 7-8)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P5B"				, " Se desvían ligeramente de los valores ideales por lo que puede existir distorsión en alguna escala, aunque no afecte al perfil general.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P6A"				, "Consistencia Media (5-6)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P6B"				, " Indica que se ha respondido con motivación o interés y no se han encontrado dificultades para realizar o comprender el cuestionario.");
define("STR_PRISMA_PERFIL_DE_PERSONALIDAD_LABORAL"						, "PERFIL DE PERSONALIDAD LABORAL");
define("STR_PRISMA_BAJO"												, "Bajo");
define("STR_PRISMA_ME_BA"												, "Me.-Ba.");
define("STR_PRISMA_MEDIO"												, "Medio");
define("STR_PRISMA_ME_AL"												, "Me.-Al.");
define("STR_PRISMA_ALTO"												, "Alto");
define("STR_PRISMA_DINAMISMO_Y_ACTIVIDAD"								, "Dinamismo y actividad");
define("STR_PRISMA_DINAMISMO_Y_ACTIVIDAD_TXT"							, "Les gustan las actividades que exigen esfuerzo y alto grado de actividad. Se mantienen siempre ocupados/as.");
define("STR_PRISMA_CONSTANCIA_PERSEVERANCIA"							, "Constancia / Perseverancia");
define("STR_PRISMA_CONSTANCIA_PERSEVERANCIA_TXT"						, "Se esfuerzan por terminar las tareas a tiempo. Acaban lo empezado. Son constantes y cumplen plazos.");
define("STR_PRISMA_AMBICION_DE_METAS_Y_LOGROS"							, "Ambición de metas y logros");
define("STR_PRISMA_AMBICION_DE_METAS_Y_LOGROS_TXT"						, "Se autoexigen. Buscan objetivos y metas dificiles. Ambiciosos/as por superarse y mejorar.");
define("STR_PRISMA_COMPETITIVIDAD"										, "Competitividad");
define("STR_PRISMA_COMPETITIVIDAD_TXT"									, "Disfrutan con actividades competitivas. Participan para ganar y ser los mejores cuando se comparan con los demás. No toleran perder.");
define("STR_PRISMA_DECISION"											, "Decisión");
define("STR_PRISMA_DECISION_TXT"										, "Sopesan las alternativas y toman las decisiones con rapidez. Dispuestos a actuar.");
define("STR_PRISMA_TENSION_INTERNA"										, "Tensión interna");
define("STR_PRISMA_TENSION_INTERNA_TXT"									, "Internamente tensos/as. Dificilmente se relajan. Con ansiedad ante presiones o situaciones dificiles.");
define("STR_PRISMA_AUTODOMINIO"											, "Autodominio");
define("STR_PRISMA_AUTODOMINIO_TXT"										, "Serenos/as. Mantienen el dominio de si mismos en situaciones importantes o ante problemas. La presión o preocupaciones no les afecta. Regulan su ansiedad.");
define("STR_PRISMA_RESISTENCIA_EMOCIONAL"								, "Resistencia emocional");
define("STR_PRISMA_RESISTENCIA_EMOCIONAL_TXT"							, "No les preocupa lo que opinen los dem&aacute;s. No reaccionan ni se ofenden ante criticas personales. No se suelen sentir ofendidios/as.");
define("STR_PRISMA_CONTROL_EXTERNO"										, "Control externo");
define("STR_PRISMA_CONTROL_EXTERNO_TXT"									, "Controlan sus emociones y no muestran a los demás sus sentimientos, bien sean de entusiamo o de malestar.");
define("STR_PRISMA_CONFIANZA_EN_LOS_DEMAS"								, "Confianza en los demás");
define("STR_PRISMA_CONFIANZA_EN_LOS_DEMAS_TXT"							, "Ven a los demas como honestos y fiables Creen en la palabra y bondad de las personas.");
define("STR_PRISMA_ACTITUD_POSITIVA"									, "Actitud positiva");
define("STR_PRISMA_ACTITUD_POSITIVA_TXT"								, "Confian en que el futuro sea favorable. Tienden a ver lo positivo en cada situación. Positivos/as.");
define("STR_PRISMA_EXTROVERSION"										, "Extroversión");
define("STR_PRISMA_EXTROVERSION_TXT"									, "Disfrutan animando los grupos o las reuniones. Habladores/as. Buenos conversadores. Les gusta el protagonismo social en las relaciones.");
define("STR_PRISMA_AFILIACION_SOCIABILIDAD"								, "Afiliación / sociabilidad");
define("STR_PRISMA_AFILIACION_SOCIABILIDAD_TXT"							, "Necesitan estar con gente. Disfutan en compañia de otros aunque no sean protagonistas. No les gusta la soledad. Colaboran y son serviciales con los demás.");
define("STR_PRISMA_HABILIDAD_RELACIONAL"								, "Habilidad relacional");
define("STR_PRISMA_HABILIDAD_RELACIONAL_TXT"							, "Actúan con seguridad en las reuniones y en público. Se saben relacionar en público y controlar las situaciones. Crean impacto.");
define("STR_PRISMA_EMPATIA"												, "Empatía");
define("STR_PRISMA_EMPATIA_TXT"											, "Se interesan y preocupan por los demás. Son tolerantes, comprensivos/as y considerados/as. Preocupados por solucionar los problemas de la gente.");
define("STR_PRISMA_MODESTIA"											, "Modestia");
define("STR_PRISMA_MODESTIA_TXT"										, "Prefieren no presumir de sus éxitos y cualidades. Se muestran prudentes y humildes. No les gusta hablar de si mismos.");
define("STR_PRISMA_CONSENSUADOR"										, "Consensuador/a");
define("STR_PRISMA_CONSENSUADOR_TXT"									, "Consultan y escuchan a los demás. Buscan el apoyo para decidir. Prefieren decidir por acuerdo.");
define("STR_PRISMA_PERSUASION"											, "Persuasión");
define("STR_PRISMA_PERSUASION_TXT"										, "Influyentes. Elocuentes. Intentan convencer a los demás para que acepten sus puntos de vista. Pueden ser excelentes vendedores o negociadores eficaces.");
define("STR_PRISMA_VOLUNTAD_DE_MANDO_Y_DIRECCION"						, "Voluntad de mando y dirección");
define("STR_PRISMA_VOLUNTAD_DE_MANDO_Y_DIRECCION_TXT"					, "Prefieren asumir el liderazgo en los grupos. Les gusta dirigir, organizar y supervisar los proyectos y/o a las personas.");
define("STR_PRISMA_AUTONOMIA_AUTODETERMINACION"							, "Autonomía / Autodeterminación");
define("STR_PRISMA_AUTONOMIA_AUTODETERMINACION_TXT"						, "Actúan y piensan por su cuenta. No siguen las opiniones de la mayoría. Prefieren hacer las cosas a su manera. Autosuficientes.");
define("STR_PRISMA_DIRECTO_ESPONTANEO"									, "Directo / Espontáneo");
define("STR_PRISMA_DIRECTO_ESPONTANEO_TXT"								, "Suelen decir lo que piensan clara y directamente. Son directos/as y expresan sus críticas con seguridad.");
define("STR_PRISMA_ANALISIS_OBJETIVO"									, "Análisis objetivo");
define("STR_PRISMA_ANALISIS_OBJETIVO_TXT"								, "Basan sus decisiones y propuestas en datos y hechos objetivos. Las informaciones que más valoran son las cifras y datos cuantitativos.");
define("STR_PRISMA_ANALISIS_DE_RIESGOS"									, "Análisis de riesgos");
define("STR_PRISMA_ANALISIS_DE_RIESGOS_TXT"								, "Analizan la información críticamente, buscando los riesgos o problemas potenciales de cada situación.");
define("STR_PRISMA_ANALISIS_DE_PERSONAS"								, "Análisis de personas");
define("STR_PRISMA_ANALISIS_DE_PERSONAS_TXT"							, "Cuando analizan situaciones o toman decisiones, se interesan por las razones y/o motivos del comportamiento de las personas.");
define("STR_PRISMA_PROFUNDIDAD_CONCEPTUAL"								, "Profundidad conceptual");
define("STR_PRISMA_PROFUNDIDAD_CONCEPTUAL_TXT"							, "Les gusta trabajar con modelos y bases teóricas. Se documentan. Analizan con profundidad los asuntos. Curiosos/as mentales.");
define("STR_PRISMA_INNOVACION_Y_SOLUCIONES"								, "Innovación y soluciones");
define("STR_PRISMA_INNOVACION_Y_SOLUCIONES_TXT"							, "Aportan nuevas ideas y soluciones originales. Proponen mejoras e ideas creativas. Disfrutan creando más que realizando.");
define("STR_PRISMA_PREVISION_Y_PLANIFICACION"							, "Previsión y planificación");
define("STR_PRISMA_PREVISION_Y_PLANIFICACION_TXT"						, "Tienen visión a medio y largo plazo. Con perspectiva. Se orientan al futuro. Prevén antecedentes y consecuencias.");
define("STR_PRISMA_ADAPTABILIDAD_FLEXIBILIDAD"							, "Adaptabilidad / Flexibilidad");
define("STR_PRISMA_ADAPTABILIDAD_FLEXIBILIDAD_TXT"						, "Se adaptan fácilmente a las diversas personas y circunstancias. Abiertos a cambios e innovaciones.");
define("STR_PRISMA_PRO_CAMBIOS"											, "Pro-cambios");
define("STR_PRISMA_PRO_CAMBIOS_TXT"										, "Prefieren cambiar a menudo. Buscan la variedad de tareas y actividades. Les gusta probar cosas nuevas. Le aburre la rutina.");
define("STR_PRISMA_PRAGMATISMO"											, "Pragmatismo");
define("STR_PRISMA_PRAGMATISMO_TXT"										, "Se centran en lo operativo y viable. Concreta y se atiene a lo posible. Va directamente a buscar y aplicar soluciones prácticas.");
define("STR_PRISMA_ORDEN_ORGANIZACION"									, "Orden / Organización");
define("STR_PRISMA_ORDEN_ORGANIZACION_TXT"								, "Realizan las tareas con minuciosidad y detalle. Son organizados y sistemáticos/as. No toleran el desorden.");
define("STR_PRISMA_DISCIPLINA"											, "Disciplina");
define("STR_PRISMA_DISCIPLINA_TXT"										, "Respetan las normas y siguen los procedimientos establecidos. Son muy rigurosos/as en el cumplimiento de las normas.");
define("STR_PRISMA_G_C"													, "G.C.");
define("STR_PRISMA_STR_PRISMA_G_C_TXT"									, "Grado de congruencia en las respuestas");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL"				, "PERFIL GENERAL DE PERSONALIDAD LABORAL");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL_P1"			, "A partir de las respuestas dadas por el/la candidato/a al cuestionario, se obtiene el perfil general de las 12 escalas en las que se integran las 32 que contiene el cuestionario.");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL_P2"			, "Por tanto, ofrece un resumen de la tendencia habitual de comportamiento de la persona que ha respondido al cuestionario, permitiendo obtener una visión rápida y global de su perfil profesional.");
define("STR_PRISMA_NIVEL_GENERAL_DE"									, "NIVEL GENERAL DE");
define("STR_PRISMA_ENERGIA_Y_MOTIVACIONES"								, "Energía y Motivaciones");
define("STR_PRISMA_EXTROVERSION_Y_PROTAGONISMO_SOCIAL"					, "Extroversión y<br />Protagonismo Social");
define("STR_PRISMA_INFLUENCIA_MANDO_O_ASCENDENCIA"						, "Influencia, Mando o<br /> Ascendencia");
define("STR_PRISMA_EMPATIA_Y_ORIENTACION_A_LAS_PERSONAS"				, "Empatía y Orientación<br /> a las Personas");
define("STR_PRISMA_ORIENTACION_A_TAREAS_Y_OBJETIVOS"					, "Orientación a tareas y objetivos");
define("STR_PRISMA_POTENCIA_ANALITICA_Y_SOLUCIAON_DE_PROBLEMAS"			, "Potencia Analítica y Solución de<br /> Problemas");
define("STR_PRISMA_FLEXIBILIDAD_MENTAL"									, "Flexibilidad Mental");
define("STR_PRISMA_DISCIPLINA_Y_ORDEN"									, "Disciplina y Orden");
define("STR_PRISMA_PRECISION_Y_CALIDAD"									, "Precisión y Calidad");
define("STR_PRISMA_RAPIDEZ_Y_OPERATIVIDAD"								, "Rapidez y Operatividad");
define("STR_PRISMA_CONTROL_EMOCIONAL"									, "Control Emocional");
define("STR_PRISMA_TOLERANCIA_AL_ESTRES"								, "Tolerancia al Estrés");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS"					, "INFORME ORIENTADO A COMPETENCIAS");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "A continuación, se presenta información más detallada sobre el perfil de competencias.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P2"			, "El tipo de Cuestionario de Personalidad Laboral al que el/la candidato/a ha respondido, obliga a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y la que peor le describe. Con este método, no puede lograr altas puntuaciones en todas las competencias.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P3"			, "El perfil que presentamos a continuación deberá ser considerado como un indicador orientativo de sus competencias más fuertes y aquellas que podría desarrollar, en base a las priorizaciones que ha ido realizando en sus respuestas.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P4"			, "La columna de la izquierda indica la competencia. Los comportamientos que aparecen en la columna central son aspectos clave que contribuyen positivamente o negativamente en cada competencia.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P5"			, "El nivel de desarrollo de la competencia y el impacto de cada una en el perfil general se muestran en la columna de la derecha.");
define("STR_PRISMA_COMPETENCIAS_PARA_LA_GESTION"						, "COMPETENCIAS PARA LA GESTIÓN");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_BR"								, "DIRIGIR<br /> Y<br /> LIDERAR");
define("STR_PRISMA_A_VECES"												, "A VECES");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_A_VECES_TXT"						, "Asume la responsabilidad y el control en los equipos y/o proyectos. Se responsabiliza de la asignación de objetivos a personas o equipos. Impulsa a otros para que logren objetivos. Consigue dirigir eficazmente a las personas/equipos.");
define("STR_PRISMA_AREA_EN_DESARROLLO"									, "ÁREA EN DESARROLLO");
define("STR_PRISMA_PLANIFICACION"										, "PLANIFICACIÓN");
define("STR_PRISMA_CASI_NUNCA"											, "CASI NUNCA");
define("STR_PRISMA_STR_PRISMA_PLANIFICACION_CASI_NUNCA_TXT"				, "Organiza y distribuye los trabajos de las personas o los proyectos. Dedica tiempo, recursos o esfuerzos a planificar eficazmente. Realiza previsiones realistas tanto en tiempos como en plazos de entrega.");
define("STR_PRISMA_AREA_POTENCIAL_DESARROLLO"							, "ÁREA POTENCIAL DESARROLLO");
define("STR_PRISMA_COMUNICACION_SOCIAL_BR"								, "COMUNICACIÓN<br /> SOCIAL");
define("STR_PRISMA_NUNCA"												, "NUNCA");
define("STR_PRISMA_COMUNICACION_SOCIAL_NUNCA_TXT"						, "Se expresa con claridad y eficacia en reuniones o eventos. Realiza discursos y/o comunicaciones con fluidez y eficacia. Logra captar la atención del público en charlas o presentaciones.Se siente seguro/a y cómodo/a al intervenir en público.");
define("STR_PRISMA_AREA_CLAVE_DE_MEJORA"								, "ÁREA CLAVE DE MEJORA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_BR"						, "PERSUASIVIDAD<br /> E<br /> INFLUENCIA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_A_VECES_TXT"				, "Convence y persuade con eficacia a otras personas. Negocia con éxito y eficacia ante sus interlocutores o competidores. Logra que otros acepten sus proyectos, opiniones o sugerencias con facilidad. Induce con eficacia a otros a que cambien su opinión.");
define("STR_PRISMA_COMPETENCIAS_TECNICAS"								, "COMPETENCIAS TÉCNICAS");
define("STR_PRISMA_DOMINIO_DE_SU_ESPECIALIDAD"							, "DOMINIO<br /> DE SU<br /> ESPECIALIDAD");
define("STR_PRISMA_STR_PRISMA_DOMINIO_DE_SU_ESPECIALIDAD_A_VECES_TXT"	, "Demuestra un alto dominio en su área de especialización. Procura mantenerse actualizado/a en conocimientos técnicos especializados. Asimila rápidamente nuevas técnicas o conocimientos específicos. Domina los aspectos técnicos de su trabajo o área.");
define("STR_PRISMA_ANALISIS"											, "ANÁLISIS");
define("STR_PRISMA_ANALISIS_A_VECES_TXT"								, "Analiza en profundidad o detenidamente los hechos, datos o informaciones. Demuestra eficacia solucionando problemas. Establece métodos y/o procesos que amplían y/o facilitan soluciones. Analiza las causas, detalles o consecuencias en los problemas o asuntos.");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_2BR"				, "GARANTÍA<br /> Y PROMOCIÓN<br /> DE LA CALIDAD");
define("STR_PRISMA_CASI_SIEMPRE"										, "CASI SIEMPRE");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_CASI_SIEMPRE_TXT"	, "Asume y/o promociona la importancia de la calidad. Se compromete activamente en el logro de objetivos de calidad. Se exige, en sus tareas, alta calidad. Se muestra estricto/a en mantener normas y/o estándares de calidad.");
define("STR_PRISMA_AREA_POTENCIAL_FORTALEZA"							, "ÁREA POTENCIAL FORTALEZA");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_BR"								, "ORDEN<br /> Y SISTEMÁTICA<");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_A_VECES_TXT"						, "Realiza las tareas con minuciosidad prestando atención a los detalles. Procura mantener ordenado su entorno de trabajo. Sigue una estructura y sistemática a la hora de afrontar sus tareas.");
define("STR_PRISMA_COMPETENCIAS_PARA_EL_DESARROLLO_DEL_NEGOCIO"			, "COMPETENCIAS PARA EL DESARROLLO DEL NEGOCIO");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_BR"								, "ORIENTACIÓN<br /> AL LOGRO");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_CASI_NUNCA_TXT"					, "Se centra con energía en el logro de objetivos / resultados. Enfoca sus trabajos y actividades hacia el crecimiento del negocio. Demuestra un fuerte sentido o enfoque hacia lo comercial. Está atento a las ventas, facturación y/o rentabilidad de la organización.");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_2BR"							, "INNOVACIÓN<br /> Y<br /> CREATIVIDAD");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_A_VECES_TXT"				, "Se muestra capaz de producir ideas o enfoques originales. Se muestra innovador/a introduciendo mejoras. Aporta nuevas ideas o puntos de vista. Propone nuevas ideas, productos, servicios o procedimientos.");
define("STR_PRISMA_ORIENTACIÓN_A_LA_ACCION_Y_DECISION"					, "ORIENTACIÓN<br /> A LA ACCIÓN<br /> Y DECISIÓN");
define("STR_PRISMA_ORIENTACIÓN_A_LA_ACCION_Y_DECISION_CASI_NUNCA_TXT"	, "Toma decisiones con facilidad o rapidez. Demuesta energía o determinación en el trabajo. Toma la iniciativa en las decisiones. Impulsa con energía la realización de los trabajos.");
define("STR_PRISMA_VISION_ESTRATEGICA_BR"								, "VISIÓN<br /> ESTRATÉGICA");
define("STR_PRISMA_VISION_ESTRATEGICA_CASI_NUNCA_TXT"					, "Tiene en cuenta los objetivos generales de la empresa/negocio. Piensa y actúa con visión a medio/largo plazo. Toma decisiones que suponen cambios estratégicos en la empresa. Elabora o establece objetivos de empresa a largo plazo.");
define("STR_PRISMA_COMPETENCIAS_INTERPERSONALES"						, "COMPETENCIAS INTERPERSONALES");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_BR"							, "HABILIDAD<br /> INTERPERSONAL");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_CASI_NUNCA_TXT"				, "Demuestra habilidad para relacionarse con los demás y hacer equipo. Ayuda y facilita el trabajo a los demás. Demuestra interés y sensibilidad hacia los demás. Demuestra ser capaz de obtener lo mejor de cada colaborador/a o compañero/a.");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_BR"						, "FLEXIBILIDAD<br /> Y<br /> ADAPTACIÓN");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_NUNCA_TXT"					, "Acepta positivamente los cambios. Se adapta fácilmente a las nuevas personas o situaciones. Demuestra buena disposición para aceptar nuevos métodos o procedimientos. Apoya las iniciativas de cambios o mejoras.");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_2BR"				, "RESISTENCIA<br /> A LA FATIGA<br /> Y AL ESTRÉS");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_CASI_SIEMPRE_TXT", "'Mantiene la calma en situaciones de tensión. Se recupera con facilidad después de los contratiempos. Tolera fácilmente las críticas o desplantes. Se sobrepone o se controla ante exigencias o presiones.");
define("STR_PRISMA_MOTIVACION_PERSONAL_POR_EL_TRABAJO"					, "MOTIVACIÓN<br /> PERSONAL<br /> POR EL TRABAJO");
define("STR_PRISMA_MOTIVACION_PERSONAL_POR_EL_TRABAJO_CASI_NUNCA_TXT"	, "Asume con intensidad sus responsabilidades laborales. Busca promoción profesional en la empresa. Supera los errores pasados poniendo ánimo o energía. Demuestra alta voluntad por hacer las cosas progresivamente mejor.");
define("STR_PRISMA_AREA_CLAVE_DE_MEJORA_BR"								, "Área<br /> Clave<br /> de Mejora");
define("STR_PRISMA_AREA_DE_POTENCIAL_DESARROLLO"						, "Área<br /> de Potencial<br />Desarrollo");
define("STR_PRISMA_AREA_DE_DESARROLLO_2BR"								, "Área<br /> de<br /> Desarrollo");
define("STR_PRISMA_AREA_DE_POTENCIAL_FORTALEZA"							, "Área<br /> de Potencial<br /> Fortaleza");
define("STR_PRISMA_AREA_DE_FORTALEZA_2BR"								, "Área<br />de<br /> Fortaleza");
define("STR_PRISMA_NUNCA_SE_COMPORTA_ASI"								, "<strong>Nunca</strong><br />se comporta así");
define("STR_PRISMA_CASI_NUNCA_SE_COMPORTA_ASI"							, "<strong>Casi Nunca</strong><br />se comporta así");
define("STR_PRISMA_A_VECES_SE_COMPORTA_ASI"								, "<strong>A Veces</strong><br />se comporta así");
define("STR_PRISMA_CASI_SIEMPRE_SE_COMPORTA_ASI"						, "<strong>Casi Siempre</strong><br />se comporta así");
define("STR_PRISMA_SIEMPRE_SE_COMPORTA_ASI"								, "<strong>Siempre</strong><br />se comporta así");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR"									, "DIRIGIR Y LIDERAR");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_TXT"								, "Coordina y guía a los demás para alcanzar los objetivos de la organización.");
define("STR_PRISMA_PLANIFICACION_TXT"									, "Planifica las actividades, proyectos, etc., teniendo los recursos disponibles y los plazos estimados, estando atento a los posibles imprevistos.");
define("STR_PRISMA_COMUNICACION_SOCIAL"									, "COMUNICACIÓN SOCIAL");
define("STR_PRISMA_COMUNICACION_SOCIAL_TXT"								, "Habla con claridad, fluidez y convicción, tanto individualmente como en grupos.");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA"							, "PERSUASIVIDAD E INFLUENCIA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_TXT"						, "Influye, convence, impacta en los demás para mejorar o cambiar resultados, puntos de vista o comportamientos.");
define("STR_PRISMA_DOMINIO_DE_LA_ESPECIALIDAD"							, "DOMINIO DE LA ESPECIALIDAD");
define("STR_PRISMA_DOMINIO_DE_LA_ESPECIALIDAD_TXT"						, "Dominio técnico o profesional del trabajo. Curiosidad o interés en su actualización.");
define("STR_PRISMA_ANALISIS_TXT"										, "Analiza aspectos y problemas en detalle, de manera sistemática, emitiendo juicios sólidos basados en información relevante.");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_1BR"				, "GARANTÍA Y PROMOCIÓN<br /> DE LA CALIDAD");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_TXT"				, "Demuestra interés por los objetivos y criterios de calidad, garantizando el cumplimiento de los procedimientos y normas establecidos.");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA"									, "ORDEN Y SISTEMÁTICA");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_TXT"								, "Realiza las tareas de forma estructurada y organizada, procurando mantener su entorno de trabajo ordenado.");
define("STR_PRISMA_ORIENTACION_AL_LOGRO"								, "ORIENTACIÓN AL LOGRO");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_TXT"							, "Se marca objetivos y metas retadoras y trabaja de forma constante y con perseverancia en su consecución.");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_CAMBIOS_Y_MEJORAS"			, "INNOVACIÓN Y CREATIVIDAD");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_CAMBIOS_Y_MEJORAS_TXT"		, "Aporta nuevos y creativos puntos de vista en el trabajo. Identifica aspectos originales y tiende a superar las resistencias tradicionales.");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION_BR"					, "ORIENTACIÓN A LA ACCIÓN<br /> Y DECISIÓN");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION_TXT"				, "Toma decisiones ágiles, buscan la practicidad y operatividad de las cosas.");
define("STR_PRISMA_VISION_ESTRATEGICA"									, "VISIÓN ESTRATÉGICA");
define("STR_PRISMA_VISION_ESTRATEGICA_TXT"								, "Actúa con visión de futuro, marcando objetivos a medio y largo plazo e identificando las posibles consecuencias de sus propuestas.");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL"								, "HABILIDAD INTERPERSONAL");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_TXT"							, "Se relaciona positiva y constructivamente con los demás. Es considerado y trabaja eficazmente en equipo.");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION"							, "FLEXIBILIDAD Y ADAPTACIÓN");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_TXT"						, "Se adapta con facilidad a las demandas de cambios laborales, a contextos variados.");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_1BR"				, "RESISTENCIA A LA FATIGA <br />Y AL ESTRÉS");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_TXT"				, "Mantiene pautas de conducta estables ante dificultades y presiones. Tiene un eficaz control de sí mismo.");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO_BR"				, "ENERGÍA INTERNA");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO_TXT"				, "Motivación interna para afrontar los retos con energía, optimismo, perseverancia y ambición.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA"			, "SÍNTESIS DEL PERFIL DE COMPETENCIAS PRISM@");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P1"	, "Este Perfil describe cómo se comporta un/a candidato/a en las principales situaciones laborales, en base a una serie de competencias.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P2"	, "El tipo de Cuestionario de Personalidad Laboral al que el/la candidato/a ha respondido, obliga a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y la que peor le describe. Con este método, no puede lograr altas puntuaciones en todas las competencias.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P3"	, "El perfil que presentamos a continuación deberá ser considerado como un indicador orientativo de sus competencias más fuertes y aquellas que podría desarrollar, en base a las priorizaciones que ha ido realizando en sus respuestas.");
define("STR_PRISMA_CLAVE_DE_MEJORA"										, "CLAVE DE<br />MEJORA");
define("STR_PRISMA_POTENCIAL_DESARROLLO"								, "POTENCIAL<br />DESARROLLO");
define("STR_PRISMA_AREA_DE_DESARROLLO_BR"								, "AREA DE<br />DESARROLLO");
define("STR_PRISMA_POTENCIAL_FORTALEZA"									, "POTENCIAL<br />FORTALEZA");
define("STR_PRISMA_AREA_DE_BR_FORTALEZA"								, "AREA DE<br />FORTALEZA");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD"					, "GARANTÍA Y PROMOCIÓN DE LA CALIDAD");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD"							, "INNOVACIÓN Y CREATIVIDAD");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION"					, "ORIENTACIÓN A LA ACCIÓN Y DECISIÓN");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES"					, "RESISTENCIA A LA FATIGA Y AL ESTRÉS");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO"					, "ENERGÍA INTERNA");
define("STR_PRISMA_PERFIL_DE_ESTILOS"									, "PERFIL DE ESTILOS");
define("STR_PRISMA_PERFIL_DE_ESTILOS_TXT"								, "Este informe recoge el estilo o los estilos predominantes de la persona que ha respondido el cuestionario, cuando dirige un equipo, cuando se relaciona con su jefe y cuando trabaja en grupo, de acuerdo con el perfil de personalidad obtenido.");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO"								, "ESTILOS DE LIDERAZGO");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO_P1"								, "Kenneth Blanchard a partir del estudio de la conducta de los líderes en situaciones diversas, crea la teorÍa del liderazgo situacional. Esta teoría se basa en dos dimensiones críticas del comportamiento del líder: cantidad de dirección (conducta de tarea) y cantidad de apoyo socioemocional (conducta de relación) que el líder debe proporcionar en una situación a raíz del \"nivel de madurez de sus colaboradores\".");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO_P2"								, "Este informe, muestra cuáles son los estilos preferentes de mando a partir del perfil de personalidad laboral obtenido. Se identifican los estilos que suelen adoptar para mandar, coordinar o dirigir a sus colaboradores. Además explica en qué consiste cada uno de estos estilos predominantes, teniendo en cuenta otros casos similares, especialmente en los que puede ser más eficaz.");
define("STR_PRISMA_ESTILOS_DE_COLABORACION"								, "ESTILOS DE COLABORACIÓN");
define("STR_PRISMA_ESTILOS_DE_COLABORACION_P1"							, "Para cada uno de los estilos de liderazgo es posible definir un estilo de colaboración complementario. Por ejemplo, un colaborador sumiso probablemente se adecuará en mayor grado a un Líder directivo, que alguien que es más autosuficiente.");
define("STR_PRISMA_ESTILOS_DE_COLABORACION_P2"							, "Este informe describe el o los estilos preferidos o más frecuentes de colaboración basados en el perfil de personalidad laboral obtenido. También identifica los estilos con menos preferencia o frecuencia cuando es dirigido por otros o bajo ciertas circunstancias.");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO"					, "ESTILOS DE COMPORTAMIENTO EN EQUIPO");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO_P1"				, "Dentro de los equipos, se pueden adoptar diferentes roles o estilos de comportamiento, siendo cada uno de ellos importante para garantizar un buen desempeño grupal.");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO_P2"				, "Este informe refleja el o los estilos preferidos o más frecuentes de comportamiento en equipo basados en el perfil laboral obtenido por el/la candidato/a. También identifica los estilos con menos preferencia cuando trabaja con otros o bajo ciertas circunstancias.");
define("STR_PRISMA_LIDERAZGO"											, "LIDERAZGO");
define("STR_PRISMA_CASI_NUNCA_SERA"										, "Casi<br />nunca<br />será");
define("STR_PRISMA_RARAS_VECES_SERA"									, "Raras<br />veces<br />será");
define("STR_PRISMA_PUEDE_SER"											, "Puede<br />ser");
define("STR_PRISMA_ALGUNAS_VECES_SERA"									, "Algunas<br />veces<br />será");
define("STR_PRISMA_CASI_SIEMPRE_SERA"									, "Casi<br />siempre<br />será");
define("STR_PRISMA_DIRECTIVO"											, "Directivo");
define("STR_PRISMA_DIRECTIVO_P1"										, "- Asume toda la responsabilidad de la toma de decisiones.");
define("STR_PRISMA_DIRECTIVO_P2"										, "- Planifica establece prioridades, distribuye las tareas y controla.");
define("STR_PRISMA_DIRECTIVO_P3"										, "- Orientado a metas y resultados.");
define("STR_PRISMA_DELEGADOR"											, "Delegador");
define("STR_PRISMA_DELEGADOR_P1"										, "- Delega en su equipo las tareas y la toma de decisiones.");
define("STR_PRISMA_DELEGADOR_P2"										, "- Entrega los trabajos y deja que su equipo asuma la resposabilidad.");
define("STR_PRISMA_DELEGADOR_P3"										, "- Sólo supervisa resultados.");
define("STR_PRISMA_NEGOCIADOR"											, "Negociador");
define("STR_PRISMA_NEGOCIADOR_P1"										, "- Negocia y persuade a sus colaboradores para conseguir compromisos y colaboración.");
define("STR_PRISMA_NEGOCIADOR_P2"										, "- Ofrece contraprestaciones para lograr acuerdos.");
define("STR_PRISMA_NEGOCIADOR_P3"										, "- Vende las decisiones a su equipo.");
define("STR_PRISMA_CONSULTIVO"											, "Consultivo");
define("STR_PRISMA_CONSULTIVO_P1"										, "- Consulta y sondea las opiniones de los demás, pero decide con independencia y seguridad.");
define("STR_PRISMA_CONSULTIVO_P2"										, "- Tiene en cuenta las aportaciones de su equipo pero no delega la toma de decisiones.");
define("STR_PRISMA_DEMOCRATICO"											, "Democrático");
define("STR_PRISMA_DEMOCRATICO_P1"										, "- Orientado/a al grupo. Da cohesión, apoya y motiva a sus colaboradores.");
define("STR_PRISMA_DEMOCRATICO_P2"										, "- Fomenta la participión del equipo en la toma de decisiones.");
define("STR_PRISMA_DEMOCRATICO_P3"										, "- Prefiere el consenso a tomar decisiones por si mismo/a.");
define("STR_PRISMA_COLABORACION"										, "COLABORACIÓN");
define("STR_PRISMA_AUTOSUFICIENTE"										, "Autosuficiente");
define("STR_PRISMA_AUTOSUFICIENTE_P1"									, "- Le gusta trabajar con autonomía y alto grado de libertad.");
define("STR_PRISMA_AUTOSUFICIENTE_P2"									, "- Tiene sus propias ideas y le gusta ponerlas en práctica.");
define("STR_PRISMA_AUTOSUFICIENTE_P3"									, "- Actúa sin necesidad de consultar a otros.");
define("STR_PRISMA_SUMISO"												, "Sumiso");
define("STR_PRISMA_SUMISO_P1"											, "- Le gusta que le marquen directrices, procedimientos e instrucciones concretas para realizar su trabajo.");
define("STR_PRISMA_SUMISO_P2"											, "- Prefiere que decidan por el/ella.");
define("STR_PRISMA_SUMISO_P3"											, "- Se atiene a las normas, la disciplina y lo mandado.");
define("STR_PRISMA_COMPLICE"											, "Cómplice");
define("STR_PRISMA_COMPLICE_P1"											, "- Para hacer su trabajo necesita argumentos que le convenzan.");
define("STR_PRISMA_COMPLICE_P2"											, "- Responde con seguridad a las propuestas que le hacen.");
define("STR_PRISMA_COMPLICE_P3"											, "- Negocia con sus jefes las alternativas y soluciones buscando la situación más ventajosa.");
define("STR_PRISMA_INFORMADOR"											, "Informador");
define("STR_PRISMA_INFORMADOR_P1"										, "- Le gusta ser consultado/a y ser considerado/a como experto/a, aunque no busca tomar la decisión final.");
define("STR_PRISMA_INFORMADOR_P2"										, "- Analiza críticamente, aportando su asesoramiento con independencia.");
define("STR_PRISMA_PARTICIPATIVO"										, "Participativo");
define("STR_PRISMA_PARTICIPATIVO_P1"									, "- Le gusta aportar ideas al grupo y colaborar con sus jefes cuando se les requiere o consulta.");
define("STR_PRISMA_PARTICIPATIVO_P2"									, "- Se implica en la solución de problemas y en la toma de decisiones.");
define("STR_PRISMA_COMPORTAMIENTO_EN_EQUIPO"							, "COMPORTAMIENTO EN EQUIPO");
define("STR_PRISMA_COORDINADOR"											, "Coordinador");
define("STR_PRISMA_COORDINADOR_P1"										, "- Calmado/a, seguro/a de sí mismo/a, controlado/a, maduro/a y confiado/a.");
define("STR_PRISMA_COORDINADOR_P2"										, "- Establece objetivos y define tareas. Coordina los esfuerzos y contribuciones del equipo, promoviendo la toma de decisiones y aclarando las metas.");
define("STR_PRISMA_COORDINADOR_P3"										, "- Tiende a delegar las tareas y puede ser considerado algo manipulador o ineficiente.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS"								, "Constructor<br />de Equipos");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P1"							, "- Cooperador/a, apacible, perceptivo/a, diplomático/a, orientado/a socialmente, sensible.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P2"							, "- Promueve la armonía entre los equipos. Hábil para responder a las personas y situaciones. Promueve el espíritu de equipo.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P3"							, "- Puede mostrarse indeciso/a en situaciones de crisis. Puede demostrar poca autoafirmación.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS"							, "Investigador<br />de Recursos");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P1"							, "- Extrovertido/a, entusiasta, comercial, curioso/a, comunicativo/a.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P2"							, "- Busca nuevas oportunidades y desarrolla contactos. Alta capacidad para relacionarse con la gente y para explorar lo nuevo. Habilidad para responder a los retos.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P3"							, "- Pierde fácilmente el interés cuando el entusiasmo inicial ha desaparecido.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P4"							, "- Puede llegar a ser demasiado optimista.");
define("STR_PRISMA_IMPULSOR_ENERGETICO"									, "Impulsor<br />Energético");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P1"								, "- Dinámico/a, energético/a, tenso/a, con empuje, simpático/a.");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P2"								, "- Reta a las personas y trabaja bien bajo presión. Tiene empuje y coraje para superar los obstáculos. Cuestiona la inercia y la ineficiencia.");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P3"								, "- Puede ser provocador/a, falto de tacto o con dureza. Puede demostrar irritación o impaciencia. Puede ser considerado/a como persona autocrítica.");
define("STR_PRISMA_APLICADOR"											, "Aplicador");
define("STR_PRISMA_APLICADOR_P1"										, "- Metódico/a, constante, cumplidor/a del deber, conservador/a, predecible.");
define("STR_PRISMA_APLICADOR_P2"										, "- Convierte las decisiones o políticas en objetivos concretos, realiza seguimiento para lograr los objetivos.");
define("STR_PRISMA_APLICADOR_P3"										, "- Algo inflexible. Puede tener lentitud a la hora de responder a los cambios o innovaciones.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR"								, "Analizador<br />Evaluador");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P1"								, "- Sobrio/a, flemático/a, prudente, serio/a, perspicaz, estratega.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P2"								, "- Ofrece ponderación, reflexión y análisis, criterio y discreción. Puede percibir las diversas opciones y juzgar con mayor exactitud.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P3"								, "- Puede carecer de iniciativa o de habilidad para inspirar o motivar a los demás. Puede ser demasiado crítico/a.");
define("STR_PRISMA_CREATIVO"											, "Creativo");
define("STR_PRISMA_CREATIVO_P1"											, "- Imaginativo/a, independiente, heterodoxo/a, generador/a de ideas.");
define("STR_PRISMA_CREATIVO_P2"											, "- Puede ser brillante y profundo/a en sus enfoques. Resuelve problemas difíciles con genialidad y/o inteligencia.");
define("STR_PRISMA_CREATIVO_P3"											, "- Puede descuidar con facilidad los detalles y/o el protocolo. Puede ser disperso/a o poco constante.");
define("STR_PRISMA_PERFECCIONISTA"										, "Perfeccionista");
define("STR_PRISMA_PERFECCIONISTA_P1"									, "- Detallista, minucioso/a, cumplidor/a del deber, dedicado/a, concienzudo/a.");
define("STR_PRISMA_PERFECCIONISTA_P2"									, "- Suele aplicar conocimientos y técnicas especializadas. Alta capacidad e interés por completar las cosas. Intolerante	con la desidia o falta de calidad.");
define("STR_PRISMA_PERFECCIONISTA_P3"									, "- Se preocupa mucho cuando las cosas no van bien. Bastate reacio/a a delegar.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL"						, "PERFIL COMPETENCIA EMOCIONAL");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P1"						, "La tolerancia general del estrés y la gestión eficaz de emociones, son dos elementos críticos en las relaciones profesionales y por tanto, en la adaptación de un profesional a su puesto o entorno profesional.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P2"						, "Las negociaciones, las relaciones con clientes, colaboradores, la gestión de conflictos, las posibles presiones normales del trabajo requieren de una serie de competencias y controles emocionales, que, en dependecia del perfil personal laboral ser más o menos efectivos.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P3"						, "En el gráfico, las zonas sombreadas nos indican la necesidad de hacer un análisis más profundo del perfil y contexto del puesto.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P4"						, "Las combinaciones entre puntuaciones extremas (zonas sombreadas), nos indican la necesidad de profundizar en la entrevista de selección y/o desarrollo profesional para analizar posibles repercusiones según las exigencias del contexto laboral o de las responsabilidades del puesto o función.");
define("STR_PRISMA_CONFIANZA_EN_OTROS"									, "Confianza en otros");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES"					, "PERFIL DE ESTRESORES POTENCIALES");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P1"					, "Este informe nos orienta acerca de las posibles actividades, circunstancias o condiciones específicas que pueden suponer una fuente más importante de estrés para el profesional que ha respondido al cuestionario Prism@.");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P2"					, "En el perfil, aparecerán los factores que pueden generar mayor probabilidad de estrés (9-10), o probabilidad relativamente alta (7-8).");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P3"					, "Las puntuaciones medias (4,5,6) o bajas (1,2) no implican indiferencia por parte del profesional. Simplemente no parecen ser en la actualidad fuente probable de estrés.");
define("STR_PRISMA_FACTORES_ORGANIZATIVOS"								, "FACTORES ORGANIZATIVOS");
define("STR_PRISMA_TRABAJO_RUTINARIO_Y_REPETITIVO"						, "TRABAJO RUTINARIO Y REPETITIVO");
define("STR_PRISMA_CAMBIOS_FRECUENTES"									, "CAMBIOS FRECUENTES");
define("STR_PRISMA_ESTRUCTURAS_BUROCRATICAS"							, "ESTRUCTURAS BUROCRÁTICAS");
define("STR_PRISMA_ENTORNOS_REACTIVOS"									, "ENTORNOS REACTIVOS");
define("STR_PRISMA_FACTORES_RELACIONALES"								, "FACTORES RELACIONALES");
define("STR_PRISMA_HABLAR_EN_PUBLICO"									, "HABLAR EN PÚBLICO");
define("STR_PRISMA_VENDER_NEGOCIAR"										, "VENDER / NEGOCIAR");
define("STR_PRISMA_DAR_MALAS_NOTICIAS"									, "DAR MALAS NOTICIAS");
define("STR_PRISMA_FACTORES_MOTIVACIONALES"								, "FACTORES MOTIVACIONALES");
define("STR_PRISMA_FALTA_DE_PODER"										, "FALTA DE PODER");
define("STR_PRISMA_FALTA_DE_APOYO_SOCIAL"								, "FALTA DE APOYO SOCIAL");
define("STR_PRISMA_FALTA_DE_AUTONOMIA"									, "FALTA DE AUTONOMÍA");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL"						, "FALTA DE PROGRESO PROFESIONAL");
define("STR_PRISMA_ESCASOS_RETOS_INTELECTUALES"							, "ESCASOS RETOS INTELECTUALES");
define("STR_PRISMA_FALTA_DE_RECONOCIMIENTO"								, "FALTA DE RECONOCIMIENTO");
define("STR_PRISMA_FACTORES_DEL_PUESTO_DE_TRABAJO"						, "FACTORES DEL PUESTO DE TRABAJO");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES"				, "TOMA DE DECISIONES RÁPIDAS/DIFÍCILES");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS"						, "SOLUCIÓN DE PROBLEMAS COMPLEJOS");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO"						, "FUERTES RESTRICCIONES DE TIEMPO");
define("STR_PRISMA_AMBIENTE_COMPETITIVO"								, "AMBIENTE COMPETITIVO");
define("STR_PRISMA_DIRIGIR_A_OTROS"										, "DIRIGIR A OTROS");
define("STR_PRISMA_DEFINICION_DE_LOS_FACTORES_ESTRESORES"				, "DEFINICIÓN DE LOS FACTORES ESTRESORES");
define("STR_PRISMA_TRABAJO_RUTINARIO_Y_REPETITIVO_DEF"					, "Trabajos sin variedad de tareas, predecible, sin cambios, en el que siempre se hace lo mismo o de la misma manera.");
define("STR_PRISMA_CAMBIOS_FRECUENTES_DEF"								, "Cambios frecuentes o inesperados en los contenidos, sistemas o prácticas de trabajo. Incertidumbre asociada a cambios en responsabilidades, en funciones o requerimientos del puesto de trabajo.");
define("STR_PRISMA_ESTRUCTURAS_BUROCRATICAS_DEF"						, "Exceso de normas y/o procedimientos. Normativas exigentes, controles, burocracia o papeleos exigidos.");
define("STR_PRISMA_ENTORNOS_REACTIVOS_DEF"								, "Necesidad de respuesta urgente o reacción inmediata, sin oportunidad de planificación previa. Entornos impredecibles o que exigen solución de problemas conforme surgen. Cambios constantes en las prioridades.");
define("STR_PRISMA_HABLAR_EN_PUBLICO_DEF"								, "Tener que comunicar o realizar presentaciones ante un público o auditorio. Situaciones que exijan manejarse o relacionarse ante gente desconocida o ante grupos grandes.");
define("STR_PRISMA_VENDER_NEGOCIAR_DEF"									, "Situaciones que exijan vender ideas, productos o servicios. Tener que defender o convencer a otros o llevar a cabo negociaciones difíciles con clientes, proveedores, sindicatos, etc.");
define("STR_PRISMA_DAR_MALAS_NOTICIAS_DEF"								, "Tener que dar malas noticias, informaciones negativas o desagradables(a clientes, colegas o colaboradores). Tener que comunicar o implementar programas con los que las personas pueden sentirse o reaccionar mal.");
define("STR_PRISMA_CONFLICTOS_INTERPERSONALES"							, "CONFLICTOS INTERPERSONALES");
define("STR_PRISMA_CONFLICTOS_INTERPERSONALES_DEF"						, "Situaciones de discusión o desacuerdo.Ambientes en los que haya relaciones conflictivas o de difícil convivencia. Situaciones en las que hay que enfrentarse o resolver conflictos o desacuerdos con otras personas.");
define("STR_PRISMA_FALTA_DE_PODER_DEF"									, "Falta de poder o autoridad para hacer que las cosas se hagan o para conseguir los objetivos del grupo. Carencia de responsabilidades sobre proyectos o personas.");
define("STR_PRISMA_FALTA_DE_APOYO_SOCIAL_DEF"							, "Situaciones en las que haya que tomar decisiones o iniciar acciones discutibles, impopulares o en las que no existe acuerdo, aprobación del grupo o consenso con otras personas.");
define("STR_PRISMA_FALTA_DE_AUTONOMIA_DEF"								, "Falta de libertad para actuar y/o decidir criterios personales. Situaciones en las que no se puede actuar por uno mismo, teniendo que depender de otros.");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL_BR"					, "FALTA DE PROGRESO<br />PROFESIONAL");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL_BR_DEF"				, "Trabajo donde no se favorece el avance y desarrollo de carrera. Ausencia de promoción y de carrera profesional. Falta de oportunidades de superación.");
define("STR_PRISMA_ESCASOS_RETOS_INTELECTUALES_DEF"						, "Trabajo lineal donde no se exige un esfuerzo intelectual. Pocas posibilidades de profundización en los temas, puestos sin especialización o poco técnicos.");
define("STR_PRISMA_FALTA_DE_RECONOCIMIENTO_DEF"							, "Inexistencia del reconocimiento o falta de reconocimiento formal. Ausencia de premios o recompensas a pesar de conseguir éxitos.");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES_BR"				, "TOMA DE DECISIONES<br />RÁPIDAS/DIFÍCILES");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES_BR_DEF"			, "Situaciones que exigen tomar decisiones inmediatas o actuar con gran rapidez. Tiempo limitado para reflexionar.");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS_BR"					, "SOLUCIÓN DE PROBLEMAS<br />COMPLEJOS");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS_BR_DEF"				, "Puestos con alta exigencia intelectual, manejo de mucha información o análisis de datos, ratios o informes exhaustivos.");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO_BR"					, "FUERTES RESTRICCIONES<br />DE TIEMPO");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO_BR_DEF"				, "Puestos que requieren un ritmo muy alto de actividad, con paralizaciones o interrupciones que dificultan el cumplimiento de los plazos o compromisos.");
define("STR_PRISMA_AMBIENTE_COMPETITIVO_DEF"							, "Trabajos donde haya que competir con otros compañeros, situaciones de venta agresiva, o donde haya comparación continua de resultados.");
define("STR_PRISMA_DIRIGIR_A_OTROS_DEF"									, "Funciones y/o puestos que requieren tener a cargo a personas a las que hay que mandar, controlar y/o supervisar.");
define("STR_PRISMA_INDICADORES_DE_AJUSTE_A_LAS_COMPETENCIAS"			, "INDICADORES DE AJUSTE A LAS COMPETENCIAS");
define("STR_PRISMA_DEFINICION_DE_LAS_COMPETENCIAS"						, "DEFINICIÓN DE LAS COMPETENCIAS");
define("STR_PRISMA_NOMBRE_INFORME_TXT"									, "Perfil de<br /><strong>personalidad<br />laboral</strong>");
define("STR_PRISMA_NOMBRE_INFORME_NARRATIVO_TXT"						, "Informe Narrativo Experto");
define("PRISMA_NARRATIVO_INTP1" 										, "Este informe está basado en las respuestas de el/la Sr/Sra. @usuario@ a un cuestionario de autoevaluación: el cuestionario de competencias y personalidad laboral Prisma. Este cuestionario le invita a describir su comportamiento, preferencias y actitudes en relación a distintos aspectos de su vida laboral.");
define("PRISMA_NARRATIVO_INTP2" 										, "Durante el mismo, ha tenido que elegir la afirmación que más se ajusta, y la que menos, entre bloques de tres comportamientos posibles. Sus respuestas se han comparado con las de un grupo amplio y relevante para obtener un perfil de las preferencias percibidas de el/la Sr/Sra. @usuario@ respecto a las distintas maneras de comportarse en el trabajo, agrupadas en 4 áreas principales: Energías y motivaciones, Control Emocional y Tolerancia al Estrés, Orientación a la relación y a las personas, Estilo de pensamiento y potencial de recursos mentales.");
define("PRISMA_NARRATIVO_INTP3" 										, "Este informe describe el perfil de personalidad de el/la Sr/Sra. @usuario@ y debe tratarse como confidencial. Al considerar los resultados del cuestionario, es importante tener en cuenta que representa su propia visión y el modo en que percibe sus propias conductas, en lugar del modo en que terceras personas podrían describir su personalidad. La precisión de este informe depende de la franqueza y sinceridad con la que se completó el cuestionario, así como de su propio autoconocimiento. Por lo tanto, los comentarios que se realicen en este informe deben considerarse como algo orientativo, fiable, aunque no infalible. Este autoinforme puede proporcionar importantes indicadores acerca del estilo propio del/de la Sr/Sra. @usuario@ en el trabajo, y es probable que nos permita predecir en gran medida su comportamiento en distintas situaciones.");
define("PRISMA_NARRATIVO_INTP4" 										, "Tenga en cuenta que el cuestionario describe el estilo de conducta que prefiere el/la Sr/Sra. @usuario@, pero no sus capacidades. El cuestionario aporta una descripción amplia de su estilo actual y, por lo tanto, el informe es necesariamente general. La vida útil de los datos contenidos en el informe se considera que está entre 18 y 24 meses, en función de las circunstancias personales y el puesto de trabajo. Si se han producido cambios significativos en su vida o si existe un cambio significativo en el puesto, debería volver a completar el cuestionario.");
define("PRISMA_NARRATIVO_INTP5" 										, "Si le preocupa algo con relación al contenido de este informe, diríjase a alguien que haya recibido una formación completa en el uso del cuestionario Prisma.");
define("STR_ESTILO_ORENTACION_NARR_PRISMA" 								, "ESTILO DE ORIENTACIÓN A LA RELACIÓN Y A LAS PERSONAS");
define("STR_ESTILO_PENSAMIENTO_NARR_PRISMA" 							, "ESTILO DE PENSAMIENTO Y RECURSOS MENTALES");
define("STR_NUM_PREGUNTAS_ERRONEAS" 									, "Número de preguntas erróneas");
define("STR_NUM_PREGUNTAS_BLANCO" 										, "Número de preguntas en blanco");
define("STR_VOCABULARIO"		 										, "VOCABULARIO");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_AL_VOCABULARIO"		, "Número total de preguntas referentes al vocabulario");
define("STR_GRAMATICA"													, "GRAMÁTICA");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_GRAMATICA"			, "Número total de preguntas referentes a gramática");
define("STR_COMPRENSION"		 										, "COMPRENSIÓN");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_COMPRENSION_ESCRITA"			, "Número total de preguntas referentes a comprensión escrita");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_COMPRENSION_HABLADA"			, "Número total de preguntas referentes a comprensión hablada");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_COMPRENSION"			, "Número total de preguntas referentes a comprensión");
define("STR_PRISMA_ESCALAS_DIFERENCIALES"								, "ESCALAS DIFERENCIALES");
define("STR_CIP_NOMBRE_INFORME_TXT"									, "<strong>Inventario de<br />Orientación<br />Profesional CIP</strong>");
define("STR_CIP_BIENVENIDO_INFORME_ORIENTACION_PROFESIONAL_TXT"									, "Bienvenido/a  al Informe de Orientación Profesional");
define("STR_CIP_INTRO_P1"						, "Este informe ha sido elaborado a partir de las respuestas y ejercicios realizados por @candidato_prueba@.<br /><br />El objetivo esencial de este informe es apoyar el proceso de orientación para @candidato_prueba@ sobre las profesiones y/o carreras profesionales en las que ha demostrado especial interés y/o preferencia a lo largo de las respuestas dadas en el cuestionario CIP, y ayudarle a conocer mejor las capacidades que podrían favorecer el éxito en su elección o que, por el contrario, podrían implicarle algún grado de dificultad.");
define("STR_SOP_NOMBRE_INFORME_TXT"									, "<strong><font size='+2'>SOP</font> - Sistema de Orientación Profesional</strong>");
define("STR_SOP_BIENVENIDO_INFORME_ORIENTACION_PROFESIONAL_TXT"									, "INFORME DE:");
define("STR_SOP_INTRO_P1"						, "Este informe ha sido elaborado a partir de las respuestas y ejercicios realizados por @candidato_prueba@.<br /><br />El objetivo esencial de este informe es apoyar el proceso de orientación para @candidato_prueba@ sobre las profesiones y/o carreras profesionales en las que ha demostrado especial interés y/o preferencia a lo largo de las respuestas dadas en el cuestionario SOP, y ayudarle a conocer mejor las capacidades que podrían favorecer el éxito en su elección o que, por el contrario, podrían implicarle algún grado de dificultad.");
define("STR_CONTENIDO_DEL_INFORME"						, "Contenidos del informe");
define("STR_APARTADO_1"						, "Apartado 1: ÁREAS PROFESIONALES PREFERENTES");
define("STR_CIP_INTRO_P2"						, "En la primera parte del informe, se representa el gráfico que identifica el grado de interés (en porcentaje) que ha mostrado la persona hacia los campos profesionales y/o carreras profesionales generales asociadas que se han valorado.<br /><br />Este gráfico se acompaña de una breve síntesis escrita  identificando, según los datos cuantitativos obtenidos, las carreras y/o actividades que serían prioritarias y más motivantes para @candidato_prueba@.");
define("STR_SOP_INTRO_P2"						, "En la primera parte del informe, se representa el gráfico que identifica el grado de interés (en porcentaje) que ha mostrado la persona hacia los campos profesionales y/o carreras profesionales generales asociadas que se han valorado.<br /><br />Este gráfico se acompaña de una breve síntesis escrita  identificando, según los datos cuantitativos obtenidos, las carreras y/o actividades que serían prioritarias y más motivantes para @candidato_prueba@.");
define("STR_APARTADO_2"						, "Apartado 2: ÁREA APTITUDES");
define("STR_CIP_INTRO_P3"						, "En este apartado, aparecen representadas las puntuaciones obtenidas en los test de aptitudes realizados por el/la estudiante (rendimiento en la prueba) en una escala de percentiles. Esta puntuación final representa el percentil obtenido (representado  de 0 a 100) o lo que es lo mismo, la comparativa de los resultados obtenidos con una muestra significativa de estudiantes de similar edad y características académicas.");
define("STR_SOP_INTRO_P3"						, "En este apartado, aparecen representadas las puntuaciones obtenidas en los test de aptitudes realizados por el/la estudiante (rendimiento en la prueba) en una escala de percentiles. Esta puntuación final representa el percentil obtenido (representado  de 0 a 100) o lo que es lo mismo, la comparativa de los resultados obtenidos con una muestra significativa de estudiantes de similar edad y características académicas.");
define("STR_APARTADO_3"						, "Apartado 3: ORIENTACIÓN PROFESIONAL");
define("STR_CIP_INTRO_P4"						, "En este apartado se integra la información relativa a las carreras o actividades asociadas a las capacidades en las que @candidato_prueba@ ha demostrado tener especial fortaleza y aquellas que, por el rendimiento obtenido, podrían indicar algún tipo de dificultad.<br /><br />La motivación por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior. Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que querría trabajar a futuro.<br /><br />La integración entre ambos aspectos permite una visión muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_SOP_INTRO_P4"						, "En este apartado se integra la información relativa a las carreras o actividades asociadas a las capacidades en las que @candidato_prueba@ ha demostrado tener especial fortaleza y aquellas que, por el rendimiento obtenido, podrían indicar algún tipo de dificultad.<br /><br />La motivación por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior. Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que querría trabajar a futuro.<br /><br />La integración entre ambos aspectos permite una visión muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_INTEGRACION"						, "Integración");
define("STR_APARTADO_4"						, "Apartado 4: HABILIDADES");
define("STR_CIP_INTRO_P5"						, "Este apartado es opcional y sólo aparecerá en el informe en caso de haber aplicado la prueba que permite su evaluación. ");
define("STR_SOP_INTRO_P5"						, "De cara a la orientación, es importante tener siempre en cuenta que la motivación o interés (vocación) por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior (1ª Parte del Informe o Gráfico de Áreas Profesionales Preferentes del SOP).<br /><br />Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que se deben aplicar.<br /><br />La integración entre ambos aspectos, nos puede dar una orientación muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_CIP_AREAS_PROFESIONALES_PREFERENTES_CIP", "ÁREAS PROFESIONALES PREFERENTES CIP");
define("STR_CIP_AREAS_PROFESIONALES_PREFERENTES_CIP_TXT", "A continuación se presentan los resultados obtenidos a partir de las respuestas dadas al  cuestionario de intereses profesionales realizado:");
define("STR_CIP_SINTESIS_DEL_PERFIL", "SÍNTESIS DEL PERFIL");
define("STR_CIP_SINTESIS_DEL_PERFIL_P1", "A partir de las puntuaciones obtenidas, @candidato_prueba@ demuestra:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P2", "Un interés muy elevado por actividades relacionadas con:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P3", "Un interés elevado por actividades relacionadas con:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P4", "Un interés moderado por actividades relacionadas con:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P5", "Un interés bajo por actividades relacionadas con:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P6", "Poco o ningún interés por actividades relacionadas con:");
define("STR_CIP_NINGUNA", "Ninguna");
define("STR_CIP_AREAS_DE_APTITUDES", "ÁREAS DE APTITUDES");
define("STR_CIP_AREAS_DE_APTITUDES_P1", "Resultados en una escala de 0 a 100 correspondientes al rendimiento obtenido en las pruebas de aptitud realizadas.  La puntuación obtenida en cada test ha sido comparada con una muestra significativa de estudiantes que han respondido también al  CIP.");
define("STR_CIP_ORIENTACION_PROFESIONAL", "ORIENTACIÓN PROFESIONAL");
define("STR_CIP_ORIENTACION_PROFESIONAL_P1", "A continuación, indicamos las carreras que mejor se adecuarían a los resultados obtenidos en los ejercicios de aptitudes realizados:");
define("STR_CIP_AREA_DE_INTERES", "Área de interés");
define("STR_CIP_AREA_DE_INTERES_RV", "<strong style=\"font-weight: bold;\">Razonamiento<br />Verbal</strong><br /><font style=\"font-size:9px;\">Análisis e intepretación<br />de información escrita y hablada.<br />Redacción escritos.<br />Actividades de<br />comunicación.</font>");
define("STR_CIP_AREA_DE_INTERES_RN", "<strong style=\"font-weight: bold;\">Razonamiento<br />Numérico</strong><br /><font style=\"font-size:9px;\">Calcular o chequear<br />datos.<br />Realizar operaciones de cálculo.<br />Manejar cifras,<br />estadísticas, ratios.<br />Analizar financieramente.</font>");
define("STR_CIP_AREA_DE_INTERES_RL", "<strong style=\"font-weight: bold;\">Razonamiento<br />Lógico</strong><br /><font style=\"font-size:9px;\">Crear nuevos conceptos.<br />Desarrollar nuevos<br />enfoques.<br />Responder a preguntas<br />por qué o cómo.<br />Resolución problemas<br />lógicos.</font>");
define("STR_CIP_AREA_DE_INTERES_RE", "<strong style=\"font-weight: bold;\">Razonamiento Espacial</strong><br /><font style=\"font-size:9px;\">Representar figuras o<br />espacios mentalmente.<br />Trabajar en varios planos.<br />Rotar figuras o modelos<br />en el espacio.<br />Manejar mapas, planos<br />y/o diseños gráficos.</font>");
define("STR_CIP_INTERPRETACION", "INTERPRETACIÓN");
define("STR_CIP_INTERPRETACION_P1", "Dispone ya de una capacidad óptima para el desarrollo de contenidos referidos a la carrera indicada.");
define("STR_CIP_INTERPRETACION_P2", "Dispone de potencialidad para el desarrollo	de contenidos referidos a la carrera indicada.");
define("STR_CIP_INTERPRETACION_P3", "Podría tener algunas dificultades o requerir más esfuerzos en algunos contenidos de la carrera indicada.");
define("STR_CIP_INTERPRETACION_P4", "No hay resultados en este test.");
define("STR_CIP_INTERPRETACION_P5", "No es una capacidad crítica en la carrera, aunque pueda facilitar algunos aspectos complementarios.");
define("STR_CIP_ESCALA", "Escala");
define("STR_CIP_VERBAL", "VERBAL");
define("STR_CIP_LOGICO", "LOGICO");
define("STR_CIP_NUMERICO", "NUMERICO");
define("STR_CIP_ESPACIAL", "ESPACIAL");

define("STR_PRUEBAS_ADMISION_NIVEL_GRADO"						, "Pruebas Admisión Nivel Grado");
define("STR_PRISMA_AREA_DE_FORTALEZA","ÁREA DE FORTALEZA");
define("STR_PRISMA_SIEMPRE","SIEMPRE");

define("STR_INFORME_DE_ATENCION_COMERCIAL","INFORME DE ATENCIÓN COMERCIAL");
define("STR_BAJO_POTENCIAL_0_A_35","Bajo Potencial: 0 a 35");
define("STR_MEDIO_POTENCIAL_36_A_70","Medio Potencial: 36 a 70");
define("STR_ALTO_POTENCIAL_71_A_100","Alto Potencial: 71 a 100");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL"			, "PERFIL DE COMPETENCIAS");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario Prisma  con respecto a los comportamientos del Cuestionario Prisma asociados a la definición de los Valores, Competencias Corporativas y Específicas de Corporación Empresarial Pascual.");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P2"	, "Los resultados obtenidos en el perfil, son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario. Para profundizar en los detalles del perfil, recomendamos acudir al informe narrativo o informe de interpretación automática que aparece a continuación.");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P3"	, "Recordar que, el cuestionario al que la persona ha respondido, obliga a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no puede lograr altas puntuaciones en todas las competencias.");
define("STR_PRISMA_DEFINICION_DE_LAS_COMPETENCIAS_PASCUAL"	, "DEFINICIÓN DE LAS COMPETENCIAS Y VALORES GLP");

define("STR_JN36_PERFIL_PSICOLOGICO_HUMANO_DE_JESUS_DE_NAZARET"		, "PERFIL PSICOLÓGICO-HUMANO<br />PERSONAL E INDIVIDUALIZADO");
define("STR_JN36_BAJO"												, "Bajo");
define("STR_JN36_ME_BA"												, "Me.-Ba.");
define("STR_JN36_MEDIO"												, "Medio");
define("STR_JN36_ME_AL"												, "Me.-Al.");
define("STR_JN36_ALTO"												, "Alto");
define("STR_JN36_TU_PERFIL"											, "Tu Perfil");
define("STR_JN36_PUNTOS"											, "puntos");
define("STR_JN36_ZONA_BAJA"											, "ZONA BAJA");
define("STR_JN36_ZONA_MEDIA_BAJA"									, "ZONA MEDIA BAJA");
define("STR_JN36_ZONA_MEDIA"										, "ZONA MEDIA");
define("STR_JN36_ZONA_MEDIA_ALTA"									, "ZONA MEDIA ALTA");
define("STR_JN36_ZONA_ALTA"											, "ZONA ALTA");
define("STR_JN36_COLOR_AZUL"										, "COLOR AZUL");
define("STR_JN36_COLOR_AMARILLO"									, "COLOR AMARILLO");
define("STR_JN36_COLOR_VERDE"										, "COLOR VERDE");
define("STR_JN36_COLOR_NARANJA"										, "COLOR NARANJA");
define("STR_JN36_COLOR_ROSA"										, "COLOR ROSA");
define("STR_JN36_INFORME_PERSONAL_E_INDIVIDUALIZADO"				, "INFORME PERSONAL E INDIVIDUALIZADO");
define("STR_JN36_PIE_INFORMES" 										, "es una marca registrada. La reproducción total o parcial de este Informe por cualquier medio, infringe los derechos de Copyright.");
define("STR_JN36_O_MAS" 											, " o más");

define("STR_INFORME_DE_ORIENTACION_COMERCIAL" 											, "INFORME DE ORIENTACIÓN COMERCIAL");
define("STR_TOC_INFORME_EXPERTO" 											, "TOC INFORME EXPERTO");
define("GRAFICO_DEL_PERFIL_COMPETENCIAL" 											, "GRÁFICO DEL PERFIL COMPETENCIAL");
define("STR_NIVEL_DE_COMPETENCIAS_PRIORITARIAS" 											, "Nivel de competencias prioritarias");
define("STR_NIVEL_DE_TOLERANCIA_AL_ESTRES" 											, "Nivel de tolerancia al estrés");
define("STR_NIVEL_DE_COMPETENCIAS_SECUNDARIAS" 											, "Nivel de competencias secundarias");

define("STR_ORIENTACION_AL_CLIENTE" 											, "Orientación al Cliente");
define("STR_ORIENTACION_A_RESULTADOS" 											, "Orientación a Resultados");
define("STR_COMUNICACION_PERSUASIVA" 											, "Comunicación Persuasiva");
define("STR_DESARROLLO_DE_RELACIONES" 											, "Desarrollo de Relaciones	");
define("STR_TOMA_DE_DECISIONES" 											, "Toma de Decisiones");
define("STR_TOLERANCIA_AL_ESTRES" 											, "Tolerancia al Estrés");
define("STR_ORIENTACION_A_LA_CALIDAD" 											, "Orientación a la Calidad");
define("STR_PLANIFICACION_ORGANIZACION" 											, "Planificación / Organización");
define("STR_ESPECIALIZACION" 											, "Especialización");
define("STR_ANALISIS_Y_SOLUCION_DE_PROBLEMAS" 											, "Análisis y Solución de Problemas");

define("STR_NIVEL_BAJO" 								, "Nivel Bajo");
define("STR_NIVEL_MEDIO" 								, "Nivel Medio");
define("STR_NIVEL_ALTO" 								, "Nivel Alto");

define("STR_CML_INFORME_DE_MOTIVACIONES_LABORALES" 								, "INFORME DE MOTIVACIONES LABORALES");
define("STR_CML_PERFIL_DE_MOTIVACIONES" 								, "PERFIL DE MOTIVACIONES");
define("STR_CML_COMENTARIOS" 								, "COMENTARIOS");

define("STR_SEAS_TEST_CONOCIMIENTOS_P1" 											, "Estas puntuaciones están basadas en las respuestas dadas por el/la candidato/a a una serie de preguntas relacionadas con aspectos técnicos del trabajo de Asesor según la especialidad a la que está optando. No obstante, este resultado sólo es información complementaria al resto de datos contemplados en este informe.");
define("STR_SEAS_TEST_CONOCIMIENTOS_P2" 											, "Las barras indican la autovaloración que el/la candidato/a hace de su nivel de conocimientos en comparación con la puntuación real obtenida tras contestar al Test.");
define("STR_SEAS_TEST_MEMORIA_P1" 											, "Esta prueba tiene como objetivo evaluar la capacidad del candidato/a para memorizar datos relacionados con los clientes, de su vida personal, profesional, datos relacionados con vehículos adquiridos, averías que ha tenido, etc. Los análisis previos del perfil de un Asesor demuestran que son datos utilizados frecuentemente por los asesores en su relación con los clientes, y que correlacionan positivamente con desempeños de éxito.");
define("STR_SEAS_TEST_MEMORIA_P2" 											, "No obstante, este resultado sólo es información complementaria al resto de datos contemplados en este informe.");
define("STR_SEAS_TEST_FLEXIBILIDAD_MENTAL_P1"								, "Esta prueba mide la capacidad de una persona para modificar el enfoque, encontrar alternativas variadas a la hora de resolver problemas y la flexibilidad de comportamiento para la adaptación a cambios de situación. Es un test de dificultad y valor de predicción probado para puestos que impliquen variedad de tareas y necesidad de dar respuesta a imprevistos continuos.");

define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_105"			, "Perfil de Competencias");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_128"			, "Perfil de Competencias");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_105"			, "PERFIL DE COMPETENCIAS");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_105_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario Prisma con respecto a los comportamientos del Cuestionario Prisma asociados a la definición de las Competencias de Banco Hipotecario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_105_INTRO_P2"	, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_105_INTRO_P3"	, "El cuestionario Prisma obliga a la persona que lo responde a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no se puede lograr altas puntuaciones en todas las competencias.");

define("STR_105_AREA_CLAVE_DE_MEJORA_BR"								, "Aún no<br /> desarrollado");
define("STR_105_AREA_DE_POTENCIAL_DESARROLLO"						, "Necesita<br /> mejorar");
define("STR_105_AREA_DE_DESARROLLO_2BR"								, "Alcanza lo <br />esperado");
define("STR_105_AREA_DE_POTENCIAL_FORTALEZA"							, "Supera lo <br /> esperado");
define("STR_105_AREA_DE_FORTALEZA_2BR"								, "Ejemplo a <br />seguir e <br /> influyente");

define("STR_105_AREA_CLAVE_DE_MEJORA"								, "ÁREA CLAVE DE MEJORA");
define("STR_105_AREA_POTENCIAL_DESARROLLO"							, "ÁREA POTENCIAL DESARROLLO");
define("STR_105_AREA_EN_DESARROLLO"									, "ÁREA EN DESARROLLO");
define("STR_105_AREA_POTENCIAL_FORTALEZA"							, "ÁREA POTENCIAL FORTALEZA");
define("STR_105_AREA_DE_FORTALEZA"									, "ÁREA DE FORTALEZA");

define("STR_105_DETALLE DIMENSIONES_COMPETENCIAS"					, "DETALLE DIMENSIONES POR CADA UNA DE LAS COMPETENCIAS");
define("STR_105_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "A continuación, se muestra el detalle de las puntuaciones obtenidas en cada una de las dimensiones que componen a su vez las Competencias de Banco Hipotecario.");

define("STR_128_DETALLE DIMENSIONES_COMPETENCIAS"					, "DETALLE DIMENSIONES POR CADA UNA DE LAS COMPETENCIAS");
define("STR_128_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "A continuación, se muestra el detalle de las puntuaciones obtenidas en cada una de las dimensiones que componen a su vez las Competencias de Asitur.");

define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario CEL16 con respecto a los comportamientos del CEL16 asociados a la definición de las Competencias de Banco Hipotecario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P2"	, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P3"	, "El cuestionario CEL16 obliga a la persona que lo responde a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no se puede lograr altas puntuaciones en todas las competencias.");

define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128"			, "PERFIL DE COMPETENCIAS");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario CEL16 con respecto a los comportamientos del CEL16 asociados a la definición de las Competencias de Asitur.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P2"	, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P3"	, "El cuestionario CEL16 obliga a la persona que lo responde a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no se puede lograr altas puntuaciones en todas las competencias.");

define("STR_DEF_CANDIDATO"                         , "Participante");
define("STR_PD"                         , "PD");
define("STR_PC"                         , "PT");
define("STR_COMPRENSION_ESCRITA"                         , "COMPRENSIÓN ESCRITA");
define("STR_COMPRENSION_HABLADA"                         , "COMPRENSIÓN HABLADA");
define("STR_RESULTADOS_ELT_ESCRITO"                         , "Resultados ELT Advanced (incluye Vocabulario, Gramática y Compresión Escrita)");
define("STR_RESULTADOS_ELT_HABLADA"                         , "Resultados ELT Advanced (incluye Compresión Hablada)");
define("STR_SR_A"                         , "Sr/a");

define("STR_BIP_INTRO_P1" 											, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario Prisma con respecto a los comportamientos del cuestionario asociados a la definición de las Competencias de las Fuerzas Militares de Colombia.");
define("STR_BIP_INTRO_P2" 											, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_BIP_INTRO_P3" 											, "El Cuestionario Prisma obliga a la persona a elegir entre 3 frases, cuál es la que mejor y la que peor describe su manera de ser o de actuar.");
define("STR_BIP_INTRO_P4" 											, "El Perfil General tiene 16 escalas. Estas escalas se agrupan en 9 factores que corresponden a 4 grandes áreas de la personalidad laboral:");
define("STR_BIP_INTRO_P5" 											, "- ENERGÍAS Y MOTIVACIONES.");
define("STR_BIP_INTRO_P6" 											, "- CONTROL EMOCIONAL Y TOLERANCIA AL ESTRÉS.");
define("STR_BIP_INTRO_P7" 											, "- ESTILOS DE RELACIÓN (Orientación a la relación, a las personas e Influencia, ascendencia y mando).");
define("STR_BIP_INTRO_P8" 											, "- ESTILOS DE PROCESAMIENTO MENTAL (Competencias analíticas, Potencial de Recursos Mentales, Flexibilidad y Estilo de Trabajo).");
define("STR_BIP_INTRO_P9" 											, "");

?>
