<?php
//TEXTOS EN INFORMES
define("STR_PIE_INFORMES" 												, "A reprodução total ou parcial deste relatório por qualquer meio, infringe os direitos de Copyright.");
define("STR_PIE_INFORMES_PASCUAL" 										, "Psicólogos Empresariales y Asociados SA.");
define("STR_NOMBRE_APELLIDOS"											, "Nome e sobrenome");
define("STR_FECHA_INFORME"												, "Data do relatório");
define("STR_FECHA_INFORME_DIAN"											, "Fecha finalización");
define("STR_IDENTIFICADOR"												, "Número de Cédula");
define("STR_INTRODUCCION" 												, "INTRODUÇÃO");
define("STR_INTRODUCCION_CAPS" 											, "INTRODUÇÃO");
define("STR_PUNTUACION_DIRECTA" 										, "Pontuação Direta");
define("STR_PUNTUACION_PERCENTIL" 										, "Pontuação Percentual ");
define("STR_INDICE_RAPIDEZ" 											, "Índice de Rapidez");
define("STR_INDICE_PRECISION" 											, "Índice de Precisão");
if (!defined('STR_PRODUCTO_RENDIMIENTO')) {
  define("STR_PRODUCTO_RENDIMIENTO" 										, "Produto de Rendimento");
}
define("STR_ESTILO_PROCESAMIENTO_MENTAL" 								, "Estilos de Processamento Mental");
define("STR_NUM_TOTAL_PREGUNTAS" 										, "Número total de perguntas do Teste");
define("STR_NUM_PREGUNTAS_ACERTADAS" 									, "Número de perguntas certas ");
define("STR_PUNT_INFORMES" 												, "Pontuaçao");
define("STR_BAJO_POTENCIAL" 											, "POTENCIAL BAIXO");
define("STR_MEDIO_POTENCIAL" 											, "POTENCIAL MÉDIO");
define("STR_ALTO_POTENCIAL" 											, "POTENCIAL ALTO");
define("STR_ESTE_INFORME_REPRESENTA" 									, "Este relatório apresenta as seguintes informações a partir dos resultados obtidos depois da realização do Teste:");
define("STR_EXP_PUNT_PECENTIL" 											, "Assinala o percentagem de pessoas com una puntuação inferior. O pertentagem 35, por exemplo, mostra a pontuação abaixo da qual fica o 35% dos individuos do grupo.");
define("STR_EXP_PUNT_DIRECTA" 											, "É referida ao respostas certas.");
define("STR_EXP_INDICE_RAPIDEZ" 										, "A rapidez faz parte da base do aprendizagem e da aptidão. Este índice é obtido a com base no numero de perguntas respondidas em um espaço de tempo limitado.");
define("STR_EXP_INDICE_PRECISION" 										, "Representa a qualidade frente à quantidade o que seria a rapidez. Este índice é obtido em função do número de perguntas certas em um espaço de tempo limitado.");
define("STR_EXP_PRODUCTO_RENDIMIENTO" 									, "Representa a interação entre rapidez - precisão ou precisão - rapidez, dando ênfase a uma ou a outra, de acordo com o estilo ou a atitude de cada um.");
define("STR_EXP_ESTILO_PROCESAMIENTO_MENTAL"		 					, "A partir da análise dos índices de rapidez e precisão é possível determinar qual é o estilo ou mapa mental de uma pessoa. Conhecer seu estilo de processamento mental ajuda a determinar em que classe de tarefas ou atividades vai ter um melhor rendimento.");
define("STR_PRISMA_INTRO_P1" 											, "Este relatório se baseia nas respostas da pessoa que respondeu o questionário PRISM@. Ele foi gerado de maneira automática por meio do Sistema Especialista de correção on-line da Psicólogos Empresariales.");
define("STR_PRISMA_INTRO_P2" 											, "A Psicólogos Empresariales só se responsabiliza pela versão original gerada por esse sistema e não por possíveis modificações ou anexos de outros usuários como versão posterior ou adaptações de acordo com outras percepções sobre a pessoa que respondeu o questionário.");
define("STR_PRISMA_INTRO_P3" 											, "O relatório geral, decorrente de 32 escalas originais, divide-se em nove índices gerais e quatro áreas fundamentais, que são a base da interpretação:");
define("STR_PRISMA_INTRO_P4" 											, "- ENERGIAS E MOTIVAÇÕES.");
define("STR_PRISMA_INTRO_P5" 											, "- CONTROLE EMOCIONAL E TOLERÂNCIA AO ESTRESSE.");
define("STR_PRISMA_INTRO_P6" 											, "- ESTILOS DE RELAÇÃO (Orientaçâo a relaçâo, ás pessoas e Influência, ascendência e comando).");
define("STR_PRISMA_INTRO_P7" 											, "- RECURSOS E ESTILO DE PROCESSAMENTO MENTAL (Competências analíticas, Potencial de recursos mentais, Flexibilidade e Estilo de trabalho).");
define("STR_PRISMA_INTRO_P8" 											, "Os outros relatórios de Competência e Perfis derivados deste são opcionais e descritos de maneira independente.");
define("STR_PRISMA_INTRO_P9" 											, "Recomendamos que, no momento de interpretar os seus resultados, sempre sejam levadas em consideração as pontuações de consistência obtidas.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA"					, "INTERPRETAÇÃO DA ESCALA DE CONSISTÊNCIA");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P1"				, "A Escala de Consistência nos proporciona indicadores gerais do estilo de resposta ou atitude do candidato/a. É um questionário de 'resposta obrigatória', o que delimita bastante a 'distorção motivacional' ou a tendência de revelar um perfil desejado ou conveniente.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P2"				, "A pontuação na escala de 'Consistência' expressa o grau de esforço do candidato/a para manter a coerência ou a congruência entre as respostas dadas no questionário.<br />");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P3A"				, "Consistência de 9-10");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P3B"				, " Um grau de congruência tão alto pode indicar uma possível manipulação ou o desejo de revelar uma imagem determinada de si mesmo/a.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P4A"				, "Consistencia Baja (1-2)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P4B"				, " Um congruência tão baixa pode indicar que a pessoa respondeu sem refletir, por não compreender as instruções, por falta de comprometimento ou por falta de autoconhecimento.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P5A"				, "Consistência de 3-4 e 7-8");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P5B"				, " É um pouco desvio da pontuação ideal, portanto, é possível encontrar algumas distorções em alguns escala, apesar de não afectar para o perfil geral dos resultados.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P6A"				, "Consistência de 5-6");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P6B"				, " Geralmente indica que a pessoa respondeu com motivação ou interesse e não encontrou dificuldades para responder ou compreender o questionário.");
define("STR_PRISMA_PERFIL_DE_PERSONALIDAD_LABORAL"						, "PERFIL DE PERSONALIDADE PROFISSIONAL");
define("STR_PRISMA_BAJO"												, "Baixo");
define("STR_PRISMA_ME_BA"												, "Me.-Ba.");
define("STR_PRISMA_MEDIO"												, "Médio");
define("STR_PRISMA_ME_AL"												, "Me.-Al.");
define("STR_PRISMA_ALTO"												, "Alto");
define("STR_PRISMA_DINAMISMO_Y_ACTIVIDAD"								, "Dinamismo e atividade");
define("STR_PRISMA_DINAMISMO_Y_ACTIVIDAD_TXT"							, "Gostam das atividades que exigem esforço e alto grau de atividade. Mantêm-se sempre ocupados/as.");
define("STR_PRISMA_CONSTANCIA_PERSEVERANCIA"							, "Constância/ Perseverança");
define("STR_PRISMA_CONSTANCIA_PERSEVERANCIA_TXT"						, "Esforçam-se para terminar as tarefas a tempo. Acabam o que começam. São constantes e cumprem os prazos.");
define("STR_PRISMA_AMBICION_DE_METAS_Y_LOGROS"							, "Ambição por metas e conquistas");
define("STR_PRISMA_AMBICION_DE_METAS_Y_LOGROS_TXT"						, "São auto-exigentes. Buscam objetivos e metas difíceis. Sua ambição é se superar e melhorar.");
define("STR_PRISMA_COMPETITIVIDAD"										, "Competitividade");
define("STR_PRISMA_COMPETITIVIDAD_TXT"									, "Gostam das atividades competitivas. Participam para ganhar e ser os melhores quando se comparam aos outros. Não suportam perder.");
define("STR_PRISMA_DECISION"											, "Decisão");
define("STR_PRISMA_DECISION_TXT"										, "Ponderam as alternativas e tomam decisões com rapidez, dispostos a agir.");
define("STR_PRISMA_TENSION_INTERNA"										, "Tensão interna");
define("STR_PRISMA_TENSION_INTERNA_TXT"									, "Internamente tensos. Dificilmente relaxam. Sentem ansiedade diante das pressões e situações difíceis.");
define("STR_PRISMA_AUTODOMINIO"											, "Autocontrole");
define("STR_PRISMA_AUTODOMINIO_TXT"										, "São tranqüilos/as. Mantêm o domínio de si mesmos/as em situações importantes ou diante de problemas. A pressão e/ou as preocupações não lhes afetam. Sabem administrar a ansiedade.");
define("STR_PRISMA_RESISTENCIA_EMOCIONAL"								, "Resistência emocional");
define("STR_PRISMA_RESISTENCIA_EMOCIONAL_TXT"							, "Nao se preocupam com a opinião dos outros. Não reagem a críticas pessoais. E não costumam se sentir ofendidos/as por elas.");
define("STR_PRISMA_CONTROL_EXTERNO"										, "Controle Externo");
define("STR_PRISMA_CONTROL_EXTERNO_TXT"									, "Controlam as suas emoções e não demonstram os seus sentimentos, seja de entusiasmo ou de mal-estar.");
define("STR_PRISMA_CONFIANZA_EN_LOS_DEMAS"								, "Confiança nos outros");
define("STR_PRISMA_CONFIANZA_EN_LOS_DEMAS_TXT"							, "Consideram os outros honestos e confiáveis. Acreditam na palavra e na bondade das pessoas.");
define("STR_PRISMA_ACTITUD_POSITIVA"									, "Atitude Positiva");
define("STR_PRISMA_ACTITUD_POSITIVA_TXT"								, "Acreditam que o futuro será favorável. Tendem a ver o lado positivo de cada situação. São otimistas.");
define("STR_PRISMA_EXTROVERSION"										, "Extroversão");
define("STR_PRISMA_EXTROVERSION_TXT"									, "Gostam de animar os grupos ou as reuniões. São bons de papo. Gostam do protagonismo nas relações sociais.");
define("STR_PRISMA_AFILIACION_SOCIABILIDAD"								, "Afiliação / Sociabilidade");
define("STR_PRISMA_AFILIACION_SOCIABILIDAD_TXT"							, "Precisam estar com pessoas. Gostam da companhia dos outros mesmo que não sejam protagonistas. Não gostam da solidão. Colaboram com os outros e gostam de prestar servicos");
define("STR_PRISMA_HABILIDAD_RELACIONAL"								, "Habilidade de relacionamento");
define("STR_PRISMA_HABILIDAD_RELACIONAL_TXT"							, "Agem com segurança nas reuniões e em público. Sabem controlar as situações e relacionar-se em público. Causam impacto.");
define("STR_PRISMA_EMPATIA"												, "Empatia");
define("STR_PRISMA_EMPATIA_TXT"											, "Interessam-se e têm consideração pelos outros. São tolerantes e compreensivos/as. Preocupam-se em solucionar os problemas das pessoas.");
define("STR_PRISMA_MODESTIA"											, "Modéstia");
define("STR_PRISMA_MODESTIA_TXT"										, "Preferem não se vangloriar das suas conquistas e qualidades. São prudentes e humildes. Não gostam de falar de si mesmos.");
define("STR_PRISMA_CONSENSUADOR"										, "Consenso");
define("STR_PRISMA_CONSENSUADOR_TXT"									, "Consultam e ouvem os outros. Buscam apoio para tomar decisões. Preferem decidir por acordo.");
define("STR_PRISMA_PERSUASION"											, "Persuasão");
define("STR_PRISMA_PERSUASION_TXT"										, "Influentes. Eloqüentes. Tentam convencer os outros a aceitar os seus pontos de vista. Podem ser excelentes vendedores ou negociadores eficazes.");
define("STR_PRISMA_VOLUNTAD_DE_MANDO_Y_DIRECCION"						, "Vontade de comandar e dirigir");
define("STR_PRISMA_VOLUNTAD_DE_MANDO_Y_DIRECCION_TXT"					, "Preferem assumir a liderança nos grupos. Gostam de dirigir, organizar e supervisionar os projetos e/ou as pessoas.");
define("STR_PRISMA_AUTONOMIA_AUTODETERMINACION"							, "Autonomia/ Autodeterminação");
define("STR_PRISMA_AUTONOMIA_AUTODETERMINACION_TXT"						, "Agem e pensam por si mesmos/as. Não seguem as opiniões da maioria. Preferem fazer as coisas à sua maneira. São auto-suficientes.");
define("STR_PRISMA_DIRECTO_ESPONTANEO"									, "Direto / Espontâneo");
define("STR_PRISMA_DIRECTO_ESPONTANEO_TXT"								, "Costumam dizer o que pensam clara e diretamente. São objetivo/as e expressam as suas críticas com segurança.");
define("STR_PRISMA_ANALISIS_OBJETIVO"									, "Análise objetiva");
define("STR_PRISMA_ANALISIS_OBJETIVO_TXT"								, "Baseiam as suas decisões e propostas em dados e fatos objetivos. As informações que mais valorizam são os números e os dados quantitativos.");
define("STR_PRISMA_ANALISIS_DE_RIESGOS"									, "Análise de riscos");
define("STR_PRISMA_ANALISIS_DE_RIESGOS_TXT"								, "Analisam a situação com discernimento, buscando os riscos ou problemas potenciais de cada situação.");
define("STR_PRISMA_ANALISIS_DE_PERSONAS"								, "Análise de pessoas");
define("STR_PRISMA_ANALISIS_DE_PERSONAS_TXT"							, "Quando analisam situações ou tomam decisões, interessam-se pelas razões e/ou motivos do comportamento das pessoas.");
define("STR_PRISMA_PROFUNDIDAD_CONCEPTUAL"								, "Profundidade conceitual");
define("STR_PRISMA_PROFUNDIDAD_CONCEPTUAL_TXT"							, "Gostam de trabalhar com modelos e bases teóricas. Pesquisam e analisam com profundidade os assuntos. São curiosos/as mentalmente.");
define("STR_PRISMA_INNOVACION_Y_SOLUCIONES"								, "Inovação e soluções");
define("STR_PRISMA_INNOVACION_Y_SOLUCIONES_TXT"							, "Contribuem com novas idéias e soluções originais. Propõem melhoras e idéias criativas. Gostam mais de criar do que de realizar.");
define("STR_PRISMA_PREVISION_Y_PLANIFICACION"							, "Previsão e planejamento");
define("STR_PRISMA_PREVISION_Y_PLANIFICACION_TXT"						, "Têm visão a médio e longo prazos. Com perspectiva. Orientam-se para o futuro. Consideram os antecedentes e prevêem as conseqüências.");
define("STR_PRISMA_ADAPTABILIDAD_FLEXIBILIDAD"							, "Adaptabilidade/ Flexibilidade");
define("STR_PRISMA_ADAPTABILIDAD_FLEXIBILIDAD_TXT"						, "Têm facilidade para se adaptar às diversas pessoas e circunstâncias. São abertos a mudanças e inovações.");
define("STR_PRISMA_PRO_CAMBIOS"											, "Pró-mudança");
define("STR_PRISMA_PRO_CAMBIOS_TXT"										, "Preferem mudar constantemente. Buscam a variedade de tarefas e atividades. Gostam de experimentar coisas novas. A rotina é entediante para eles/as.");
define("STR_PRISMA_PRAGMATISMO"											, "Pragmatismo");
define("STR_PRISMA_PRAGMATISMO_TXT"										, "Concentram-se no operacional e viável. Concretizam e se atêm ao possível. Procuram e aplicam diretamente soluções práticas.");
define("STR_PRISMA_ORDEN_ORGANIZACION"									, "Ordem / Organização");
define("STR_PRISMA_ORDEN_ORGANIZACION_TXT"								, "Realizam as tarefas minuciosa e detalhadamente. São organizados/as e sistemáticos/as. Não toleram a bagunça.");
define("STR_PRISMA_DISCIPLINA"											, "Disciplina");
define("STR_PRISMA_DISCIPLINA_TXT"										, "Respeitam as normas e seguem os procedimentos estabelecidos. São muito rigorosos/as no cumprimento das normas.");
define("STR_PRISMA_G_C"													, "G.C.");
define("STR_PRISMA_STR_PRISMA_G_C_TXT"									, "Grau de congruência nas respostas");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL"				, "PERFIL GERAL DE PERSONALIDADE PROFISSIONAL");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL_P1"			, "A partir das respostas dadas pelo/a candidato/a no questionário será obtido o perfil geral das 12 escalas nas quais se integram as 32 contidas no questionário.");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL_P2"			, "Seu conteúdo oferece, portanto, um resumo da tendência habitual de comportamento da pessoa que respondeu o questionário, permitindo obter uma visão rápida e global do seu perfil profissional.");
define("STR_PRISMA_NIVEL_GENERAL_DE"									, "NÍVEL GERAL DE");
define("STR_PRISMA_ENERGIA_Y_MOTIVACIONES"								, "Energia e Motivação");
define("STR_PRISMA_EXTROVERSION_Y_PROTAGONISMO_SOCIAL"					, "Extroversão e <br />Protagonismo Social");
define("STR_PRISMA_INFLUENCIA_MANDO_O_ASCENDENCIA"						, "Influência, comando ou<br /> Ascendência");
define("STR_PRISMA_EMPATIA_Y_ORIENTACION_A_LAS_PERSONAS"				, "Empatia e orientação<br /> às pessoas");
define("STR_PRISMA_ORIENTACION_A_TAREAS_Y_OBJETIVOS"					, "Orientação ao<br /> tarefas e objetivos");
define("STR_PRISMA_POTENCIA_ANALITICA_Y_SOLUCIAON_DE_PROBLEMAS"			, "Potencial analítico e de<br /> Solução de problemas");
define("STR_PRISMA_FLEXIBILIDAD_MENTAL"									, "Flexibilidade Mental");
define("STR_PRISMA_DISCIPLINA_Y_ORDEN"									, "Disciplina e Ordem");
define("STR_PRISMA_PRECISION_Y_CALIDAD"									, "Precisão e Qualidade");
define("STR_PRISMA_RAPIDEZ_Y_OPERATIVIDAD"								, "Rapidez e Operacionalidade");
define("STR_PRISMA_CONTROL_EMOCIONAL"									, "Controle Externo");
define("STR_PRISMA_TOLERANCIA_AL_ESTRES"								, "Tolerância ao Estresse");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS"					, "RELATÓRIO DE COMPETÊNCIAS");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "Abaixo encontra-se informação mais detalhada sobre o perfil de competências.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P2"			, "A coluna da esquerda indica a habilidade. Os comportamentos que aparecem na coluna central são aspectos-chaves que contribuem positiva ou negativamente em cada competência.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P3"			, "O nível de desenvolvimento da competência e o impacto de cada uma no perfil geral aparecem na coluna da direita.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P4"			, "A coluna da esquerda indica a habilidade. Os comportamentos que aparecem na coluna central são aspectos-chaves que contribuem positiva ou negativamente em cada competência.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P5"			, "O nível de desenvolvimento da competência e o impacto de cada uma no perfil geral aparecem na coluna da direita.");
define("STR_PRISMA_COMPETENCIAS_PARA_LA_GESTION"						, "COMPETÊNCIAS PARA A GESTÃO");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_BR"								, "INFLUÊNCIA<br />E<br />LIDERANÇA");
define("STR_PRISMA_A_VECES"												, "ÀS VEZES");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_A_VECES_TXT"						, "Assume a responsabilidade e o controle nas equipes e/ou nos projetos. Responsabiliza-se pela atribuição de objetivos a pessoas ou equipes. Estimula os outros a alcançarem os objetivos. Consegue comandar eficazmente pessoas/equipes.");
define("STR_PRISMA_AREA_EN_DESARROLLO"									, "ÁREA EM DESENVOLVIMENTO");
define("STR_PRISMA_PLANIFICACION"										, "PLANEJAMENTO");
define("STR_PRISMA_CASI_NUNCA"											, "QUASE NUNCA");
define("STR_PRISMA_STR_PRISMA_PLANIFICACION_CASI_NUNCA_TXT"				, "Organiza e distribui os trabalhos das pessoas ou os projetos. Dedica tempo, recursos ou esforços para planejar eficazmente. Realiza previsões realistas dos prazos para realização e entrega. Realiza os trabalhos com ordem e de método.");
define("STR_PRISMA_AREA_POTENCIAL_DESARROLLO"							, "ÁREA DE POTENCIAL DESENVOLVIMENTO");
define("STR_PRISMA_COMUNICACION_SOCIAL_BR"								, "COMUNICAÇÃO<br /> COMUNICAÇÃO SOCIAL");
define("STR_PRISMA_NUNCA"												, "NUNCA");
define("STR_PRISMA_COMUNICACION_SOCIAL_NUNCA_TXT"						, "Sabe se expressar com clareza e eficácia em reuniões ou eventos. Realiza discursos e/ou comunicações com fluência e eficácia. Consegue atrair a atenção do público em palestras ou apresentações. Sente-se seguro/a e à vontade ao intervir em público.");
define("STR_PRISMA_AREA_CLAVE_DE_MEJORA"								, "ÁREA CHAVE DE MELHORIA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_BR"						, "PERSUASÃO E<br />NEGOCIAÇÃO");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_A_VECES_TXT"				, "Convence outras pessoas com eficácia. Negocia com sucesso e eficácia com seus interlocutores ou concorrentes. Consegue fazer com que os outros aceitem os seus projetos, opiniões ou sugestões com facilidade. Induz com eficácia os outros a mudarem de opinião.");
define("STR_PRISMA_COMPETENCIAS_TECNICAS"								, "COMPETÊNCIAS TÉCNICAS");
define("STR_PRISMA_DOMINIO_DE_SU_ESPECIALIDAD"							, "DOMÍNIO<br />DA SUA<br />ESPECIALIDADE");
define("STR_PRISMA_STR_PRISMA_DOMINIO_DE_SU_ESPECIALIDAD_A_VECES_TXT"	, "Demonstra um alto domínio na sua área de especialização. Procura se manter atualizado/a em conhecimentos técnicos da sua especialidade. Assimila rapidamente novas técnicas ou conhecimentos específicos. Domina os aspectos técnicos do seu trabalho ou área.");
define("STR_PRISMA_ANALISIS"											, "ANÁLISE");
define("STR_PRISMA_ANALISIS_A_VECES_TXT"								, "Analisa em profundidade ou atentamente os fatos, dados ou informações. Demonstra eficácia solucionando problemas. Estabelece métodos e/ou processos que ampliam e/ou facilitam soluções. Analisa as causas, os detalhes ou as conseqüências dos problemas ou assuntos.");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_2BR"				, "GARANTIA<br />E PROMOÇÃO<br />QUALIDADE");
define("STR_PRISMA_CASI_SIEMPRE"										, "QUASE SEMPRE");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_CASI_SIEMPRE_TXT"	, "Assume e/ou promove a importância da qualidade. Compromete-se ativamente para atingir objetivos de qualidade. Exige de si mesmo alta qualidade nas suas tarefas. É rigoroso/a no que se refere a manter normas e/ou padrões de qualidade.");
define("STR_PRISMA_AREA_POTENCIAL_FORTALEZA"							, "ÁREA DE POTENCIAIS PONTOS FORTES");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_BR"								, "ORDEM <br />E SISTEMÁTICA");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_A_VECES_TXT"						, "Executa tarefas meticulosamente, prestando antençâo para os detalles Tenta manter ordenado o seu entorno Segue uma estrutura e uma sistemática para enfrentar as tarefas.");
define("STR_PRISMA_COMPETENCIAS_PARA_EL_DESARROLLO_DEL_NEGOCIO"			, "COMPETÊNCIAS PARA O DESENVOLVIMENTO DO NEGÓCIO");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_BR"								, "ORIENTAÇÃO<br />A RESULTADOS");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_CASI_NUNCA_TXT"					, "Concentra-se com energia em atingir objetivos e resultados. Dirige os seus trabalhos e atividades para o crescimento do negócio. Demonstra uma forte aptidão ou enfoque no aspecto comercial. Está atento às vendas, ao faturamento e/ou à rentabilidade da organização.");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_2BR"						, "INOVAÇÃO<br />E<br />CRIATIVIDADE");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_A_VECES_TXT"				, "É capaz de produzir idéias ou enfoques originais. É inovador/a introduzindo melhoras. Contribui com novas idéias ou pontos de vista. Propõe novas idéias, produtos, serviços ou procedimentos.");
define("STR_PRISMA_ORIENTACIÓN_A_LA_ACCION_Y_DECISION"					, "ORIENTAÇÃO<br />À AÇÃO<br />E À DECISÃO");
define("STR_PRISMA_ORIENTACIÓN_A_LA_ACCION_Y_DECISION_CASI_NUNCA_TXT"	, "Toma decisões com facilidade ou rapidez. Demonstra energia ou determinação no trabalho. Toma a iniciativa nas decisões. Estimula com entusiasmo a realização dos trabalhos.");
define("STR_PRISMA_VISION_ESTRATEGICA_BR"								, "VISÃO<br />ESTRATÉGICA");
define("STR_PRISMA_VISION_ESTRATEGICA_CASI_NUNCA_TXT"					, "Leva em conta os objetivos gerais da empresa/do negócio. Pensa e age com uma visão a médio/longo prazo. Toma decisões que supõem mudanças estratégicas na empresa. Elabora ou estabelece objetivos de longo prazo para a empresa.");
define("STR_PRISMA_COMPETENCIAS_INTERPERSONALES"						, "COMPETÊNCIAS INTERPESSOAIS");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_BR"							, "HABILIDADE<br />INTERPESSOAL");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_CASI_NUNCA_TXT"				, "Demonstra habilidade para se relacionar com os outros e fazer parte de equipes. Ajuda e facilita o trabalho dos outros. Demonstra interesse e sensibilidade em relação aos outros. Demonstra ser capaz de obter o melhor de cada colaborador/a ou colega.");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_BR"						, "FLEXIBILIDADE<br />E<br />ADAPTAÇÃO");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_NUNCA_TXT"					, "Aceita positivamente as mudanças. Adapta-se facilmente às novas pessoas ou situações. Demonstra boa disposição para assimilar novos métodos ou procedimentos. Apóia as iniciativas de mudança ou melhorias.");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_2BR"				, "RESISTÊNCIA<br />AO CANSAÇO<br />E AO ESTRESSE");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_CASI_SIEMPRE_TXT", "Mantém a calma em situações tensas. Recupera-se com facilidade depois dos contratempos. Tolera facilmente críticas ou atrevimentos. Sobrepõe-se ou mantém o controle diante de exigências ou pressões.");
define("STR_PRISMA_MOTIVACION_PERSONAL_POR_EL_TRABAJO"					, "MOTIVAÇÃO<br />PESSOAL<br />NO TRABALHO");
define("STR_PRISMA_MOTIVACION_PERSONAL_POR_EL_TRABAJO_CASI_NUNCA_TXT"	, "Assume com intensidade suas responsabilidades profissionais. Busca a promoção na empresa. Supera os erros passados com disposição ou energia. Demonstra grande vontade de fazer as coisas de um modo cada vez melhor.");
define("STR_PRISMA_AREA_CLAVE_DE_MEJORA_BR"								, "ÁREA<br />CHAVE<br />DE<br />MELHORIA");
define("STR_PRISMA_AREA_DE_POTENCIAL_DESARROLLO"						, "ÁREA<br />DE<br />POTENCIAL<br />DESENVOLVIMENTO");
define("STR_PRISMA_AREA_DE_DESARROLLO_2BR"								, "ÁREA<br />EM<br />DESENVOLVIMENTO");
define("STR_PRISMA_AREA_DE_POTENCIAL_FORTALEZA"							, "ÁREA DE<br />POTENCIAIS<br />PONTOS<br />FORTES");
define("STR_PRISMA_AREA_DE_FORTALEZA_2BR"								, "ÁREA<br />DE<br />PONTOS<br />FORTES");
define("STR_PRISMA_NUNCA_SE_COMPORTA_ASI"								, "<strong>Nunca</strong><br />se comporta assim");
define("STR_PRISMA_CASI_NUNCA_SE_COMPORTA_ASI"							, "<strong>Quase nunca</strong><br />se comporta assim");
define("STR_PRISMA_A_VECES_SE_COMPORTA_ASI"								, "<strong>Às vezes</strong><br />se comporta assim");
define("STR_PRISMA_CASI_SIEMPRE_SE_COMPORTA_ASI"						, "<strong>Quase sempre</strong><br />se comporta assim");
define("STR_PRISMA_SIEMPRE_SE_COMPORTA_ASI"								, "<strong>Sempre</strong><br />se comporta assim");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR"									, "DIRIGIR E LIDERAR");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_TXT"								, "Delega tarefas e motiva o grupo eficazmente para atingir os objetivos da organização.");
define("STR_PRISMA_PLANIFICACION_TXT"									, "Organiza e programa atividades, processos e recursos.");
define("STR_PRISMA_COMUNICACION_SOCIAL"									, "COMUNICAÇÃO SOCIAL");
define("STR_PRISMA_COMUNICACION_SOCIAL_TXT"								, "Fala com clareza, fluência e convicção, tanto individualmente quanto em grupo.");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA"							, "PERSUASÃO E INFLUÊNCIA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_TXT"						, "Influi, convence e gera impacto nos outros para melhorar ou alterar resultados, pontos de vista ou comportamentos.");
define("STR_PRISMA_DOMINIO_DE_LA_ESPECIALIDAD"							, "DOMÍNIO DA ESPECIALIDADE");
define("STR_PRISMA_DOMINIO_DE_LA_ESPECIALIDAD_TXT"						, "Domínio técnico ou profissional do trabalho. Curiosidade ou interesse em se atualizar.");
define("STR_PRISMA_ANALISIS_TXT"										, "Analisa aspectos e problemas detalhadamente, de maneira sistemática, emitindo julgamentos sólidos baseados em informações relevantes.");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_1BR"				, "GARANTIA E PROMOÇÃO DA QUALIDADE");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_TXT"				, "Demonstra interesse pelos objetivos e critérios de qualidade. Garante a produtividade e a qualidade.");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA"									, "ORDEM E SISTEMÁTICA");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_TXT"								, "Enfrenta as tarefas de modo organizado e estruturado, tentado manter ordenado o seu entorno");
define("STR_PRISMA_ORIENTACION_AL_LOGRO"								, "ORIENTAÇÃO A RESULTADOS");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_TXT"							, "Compreende e aplica pontos de vista comerciais e financeiros. Pensa e age em termos de custos, benefícios, mercados e valor agregado.");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_CAMBIOS_Y_MEJORAS"			, "INOVAÇÃO E CRIATIVIDADE");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_CAMBIOS_Y_MEJORAS_TXT"		, "Aporta pontos de vista novos e criativos no trabalho. Identifica aspectos originais e tende a superar as resistências tradicionais.");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION_BR"				, "ORIENTAÇÃO À AÇÃO<br />E DECISÃO");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION_TXT"				, "Demonstra estar disposto a decidir, a tomar a iniciativa e a ser pró-ativo.");
define("STR_PRISMA_VISION_ESTRATEGICA"									, "VISÃO ESTRATÉGICA");
define("STR_PRISMA_VISION_ESTRATEGICA_TXT"								, "Apresenta pontos de vista amplos, transcendentes e de perspectiva a médio a longo prazos.");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL"								, "HABILIDADE INTERPESSOAL");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_TXT"							, "Tem um relacionamento positivo e construtivo com os outros. É estimado e trabalha eficazmente em equipe.");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION"							, "FLEXIBILIDADE E ADAPTAÇÃO");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_TXT"						, "Adapta-se com facilidade e positivamente às demandas de mudança e a períodos de pressão.");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_1BR"				, "RESISTÊNCIA AO CANSAÇO<br />E AO ESTRESSE");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_TXT"				, "Mantém linhas de conduta estáveis diante das dificuldades e pressões. Tem um controle eficaz de si mesmo.");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO_BR"				, "ENERGIA INTERNA");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO_TXT"				, "Motivação interna para enfrentar os reptos com energia, otimismo, perseverança e ambição.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA"			, "SÍNTESE DO PERFIL DE COMPETÊNCIAS PRISM@");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P1"	, "Este Perfil descreve como se comporta um/a candidato/a nas principais situações de trabalho, com base em uma série de habilidades.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P2"	, "O tipo de Questionário de Personalidade Profissional que o/a candidato/a respondeu fez com que ele/a escolhesse, entre três frases que refletem comportamentos ou situações de trabalho, a que melhor e a que pior o descrevem. Com este método, é impossível obter altas pontuações em todas as competências.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P3"	, "O perfil que apresentamos a seguir deverá ser considerado um indicador das suas maiores habilidades e das que poderia desenvolver, com base nas priorizações reveladas pelas suas respostas.");
define("STR_PRISMA_CLAVE_DE_MEJORA"										, "Chave de br />Melhoria");
define("STR_PRISMA_POTENCIAL_DESARROLLO"								, "Potencial<br />Desenvolvimento");
define("STR_PRISMA_AREA_DE_DESARROLLO_BR"								, "Área em<br />Desenvolvimento");
define("STR_PRISMA_POTENCIAL_FORTALEZA"									, "Potenciais<br />Pontos Fortes");
define("STR_PRISMA_AREA_DE_BR_FORTALEZA"								, "Área de<br />Pontos<br />Fortes");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD"					, "GARANTIA E PROMOÇÃO DA QUALIDADE");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD"							, "INOVAÇÃO E CRIATIVIDADE (Mudanças e Melhorias)");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION"					, "ORIENTAÇÃO À AÇÃO E À DECISÃO");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES"					, "RESISTÊNCIA AO CANSAÇO E AO ESTRESSE");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO"					, "ENERGIA INTERNA");
define("STR_PRISMA_PERFIL_DE_ESTILOS"									, "PERFIL DE ESTILOS");
define("STR_PRISMA_PERFIL_DE_ESTILOS_TXT"								, "Este relatório reúne as características predominantes do estilo ou dos estilos da pessoa que respondeu o questionário, quando comanda uma equipe, quando se relaciona com o chefe e quando trabalha em grupo, de acordo com o perfil profissional definido.");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO"								, "ESTILOS DE LIDERANÇA");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO_P1"								, "Kenneth Blanchard, por meio do estudo do comportamento dos líderes em diversas situações, criou a teoria da Liderança Situacional. Esta teoria se baseia em duas dimensões fundamentais do comportamento do líder: nível de direção (comportamento de tarefa) e nível de apoio sócio-emocional (comportamento de relacionamento) que o líder deve proporcionar em uma situação de acordo com a 'maturidade dos seus colaboradores'.");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO_P2"								, "Este relatório mostra quais são os estilos preferidos de comando a partir do perfil profissional definido. Identificam-se os estilos que costumam ser adotados para mandar, coordenar ou comandar os colaboradores. Além disso, explica em que consiste cada um destes estilos predominantes, levando em conta outros casos similares, principalmente aqueles em que pode ser mais eficaz.");
define("STR_PRISMA_ESTILOS_DE_COLABORACION"								, "ESTILOS DE COLABORAÇÃO");
define("STR_PRISMA_ESTILOS_DE_COLABORACION_P1"							, "Para cada um dos estilos de liderança é possível definir um estilo de colaboração complementar. Por exemplo, um colaborador submisso provavelmente se adequará em maior grau a um líder diretivo do que alguém que é mais auto-suficiente.");
define("STR_PRISMA_ESTILOS_DE_COLABORACION_P2"							, "Este relatório descreve o ou os estilos preferidos ou mais freqüentes de colaboração baseados no perfil  profissional definido. Também identifica os estilos com menos preferência ou freqüência quando o candidato é comandado por outras pessoas ou em certas circunstâncias.");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO"					, "ESTILOS DE COMPORTAMENTO EM EQUIPE");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO_P1"				, "Dentro das equipes, diferentes papéis ou estilos de comportamento podem ser adotados, sendo cada um deles importante para garantir um bom desempenho do grupo.");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO_P2"				, "Este relatório reflete o ou os estilos preferidos ou mais freqüentes de comportamento em equipe baseados no perfil profissional do/a candidato/a. Também identifica os estilos com menos preferência quando trabalha com outros ou em certas circunstâncias.");
define("STR_PRISMA_LIDERAZGO"											, "LIDERANÇA");
define("STR_PRISMA_CASI_NUNCA_SERA"										, "Quase<br />nunca<br />será");
define("STR_PRISMA_RARAS_VECES_SERA"									, "Rarame<br />nte<br />será");
define("STR_PRISMA_PUEDE_SER"											, "Pode<br />ser");
define("STR_PRISMA_ALGUNAS_VECES_SERA"									, "Algumas<br />vezes<br />será");
define("STR_PRISMA_CASI_SIEMPRE_SERA"									, "Quase<br />sempre<br />será");
define("STR_PRISMA_DIRECTIVO"											, "Diretivo");
define("STR_PRISMA_DIRECTIVO_P1"										, "- Assume toda a responsabilidade por tomar decisões.");
define("STR_PRISMA_DIRECTIVO_P2"										, "- Planeja, estabelece prioridades, distribui as tarefas e controla.");
define("STR_PRISMA_DIRECTIVO_P3"										, "- Orientado a metas e resultados.");
define("STR_PRISMA_DELEGADOR"											, "Delegante");
define("STR_PRISMA_DELEGADOR_P1"										, "- Delega à equipe as tarefas e decisões.");
define("STR_PRISMA_DELEGADOR_P2"										, "- Entrega os trabalhos e deixa que a equipe assuma a responsabilidade.");
define("STR_PRISMA_DELEGADOR_P3"										, "- Supervisiona apenas os resultados.");
define("STR_PRISMA_NEGOCIADOR"											, "Negociador");
define("STR_PRISMA_NEGOCIADOR_P1"										, "- Negocia e convence seus colaboradores para obter deles compromisso e colaboração.");
define("STR_PRISMA_NEGOCIADOR_P2"										, "- Oferece compensações para obter acordos.");
define("STR_PRISMA_NEGOCIADOR_P3"										, "- Vende as decisões à sua equipe.");
define("STR_PRISMA_CONSULTIVO"											, "Consultivo");
define("STR_PRISMA_CONSULTIVO_P1"										, "- Consulta e sonda as opiniões dos outros, mas decide com independência e segurança.");
define("STR_PRISMA_CONSULTIVO_P2"										, "- Leva em conta as contribuições da equipe, mas não delega as decisões.");
define("STR_PRISMA_DEMOCRATICO"											, "Democrático");
define("STR_PRISMA_DEMOCRATICO_P1"										, "- Orientado ao grupo, dá coesão, apóia e motiva os seus colaboradores.");
define("STR_PRISMA_DEMOCRATICO_P2"										, "- Estimula a participação da equipe nas decisões.");
define("STR_PRISMA_DEMOCRATICO_P3"										, "- Prefere chegar a um consenso a tomar decisões sozinho.");
define("STR_PRISMA_COLABORACION"										, "COLABORAÇÃO");
define("STR_PRISMA_AUTOSUFICIENTE"										, "Auto-suficiente");
define("STR_PRISMA_AUTOSUFICIENTE_P1"									, "- Gosta de trabalhar com autonomia e alto grau de liberdade.");
define("STR_PRISMA_AUTOSUFICIENTE_P2"									, "- Tem as suas idéias e gosta de colocá-las em prática.");
define("STR_PRISMA_AUTOSUFICIENTE_P3"									, "- Age sem necessidade de consultar os outros.");
define("STR_PRISMA_SUMISO"												, "Submisso");
define("STR_PRISMA_SUMISO_P1"											, "- Gosta de receber diretrizes, procedimentos e instruções concretas para realizar o trabalho.");
define("STR_PRISMA_SUMISO_P2"											, "- Prefere que decidam por ele.");
define("STR_PRISMA_SUMISO_P3"											, "- Apega-se às normas, à disciplina e ao que foi determinado.");
define("STR_PRISMA_COMPLICE"											, "Cúmplice");
define("STR_PRISMA_COMPLICE_P1"											, "- Para fazer seu trabalho precisa de argumentos que o convençam.");
define("STR_PRISMA_COMPLICE_P2"											, "- Reage com segurança às propostas que recebe.");
define("STR_PRISMA_COMPLICE_P3"											, "- Negocia com os chefes as alternativas e soluções, buscando a situação mais vantajosa.");
define("STR_PRISMA_INFORMADOR"											, "Informador");
define("STR_PRISMA_INFORMADOR_P1"										, "- Gosta de ser consultado/a e levado em conta como especialista, embora procure não tomar a decisão final.");
define("STR_PRISMA_INFORMADOR_P2"										, "- Analisa com critério, oferecendo o seu assessoramento com independência.");
define("STR_PRISMA_PARTICIPATIVO"										, "Participativo");
define("STR_PRISMA_PARTICIPATIVO_P1"									, "- Gosta de contribuir com idéias para o grupo e de colaborar com os seus chefes quando é requisitado ou consultado.");
define("STR_PRISMA_PARTICIPATIVO_P2"									, "- Envolve-se na solução de problemas e na tomada de decisões.");
define("STR_PRISMA_COMPORTAMIENTO_EN_EQUIPO"							, "COMPORTAMENTO EM EQUIPE");
define("STR_PRISMA_COORDINADOR"											, "Coordenador");
define("STR_PRISMA_COORDINADOR_P1"										, "- Calmo/a, seguro/a de si mesmo/a, controlado/a, maduro/a e confiante.");
define("STR_PRISMA_COORDINADOR_P2"										, "- Estabelece objetivos e define tarefas. Coordena os esforços e contribuições da equipe, promovendo a tomada de decisões e esclarecendo as metas.");
define("STR_PRISMA_COORDINADOR_P3"										, "- Tende a delegar tarefas e pode ser considerado um pouco manipulador ou ineficiente.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS"								, "Construtor<br />de equipes");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P1"							, "- Cooperador/a, agradável, perceptivo/a, diplomático/a, sociável, sensível.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P2"							, "- Promove a harmonia entre as equipes. É habilidoso/a para responder às pessoas e reagir às situações. Promove o espírito de equipe.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P3"							, "- Pode ser indeciso/a em situações de crise. Pode demonstrar pouca auto-afirmação.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS"							, "Caçador<br />de recursos");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P1"							, "- Extrovertido/a, entusiasmado, comercial, curioso/a, comunicativo/a.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P2"							, "- Busca novas oportunidades e desenvolve contatos. Tem grande capacidade para se relacionar e para explorar o novo. É hábil para reagir aos desafios");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P3"							, "- Perde facilmente o interesse quando o entusiasmo inicial desaparece.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P4"							, "- Pode chegar a ser excessivamente otimista.");
define("STR_PRISMA_IMPULSOR_ENERGETICO"									, "Impulsor de energia");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P1"								, "- Dinâmico/a, enérgico/a, tenso/a, simpático/a e com muita energia.");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P2"								, "- Desafia as pessoas e trabalha bem sob pressão. Tem força e coragem para superar os obstáculos. Questiona a inércia e a ineficiência.");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P3"								, "- Pode ser provocador/a, ter falta de tato ou tratar as pessoas de modo duro. Pode demonstrar irritação ou impaciência. Pode ser considerado/a uma pessoa autocrítica.");
define("STR_PRISMA_APLICADOR"											, "Aplicador");
define("STR_PRISMA_APLICADOR_P1"										, "- Metódico/a, constante, cumpridor/a do dever, conservador/a, previsível.");
define("STR_PRISMA_APLICADOR_P2"										, "- Transforma as decisões ou políticas em objetivos concretos, faz um acompanhamento para atingir os objetivos.");
define("STR_PRISMA_APLICADOR_P3"										, "- Um pouco inflexível. Pode ser lento na hora de reagir às mudanças ou inovações.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR"								, "Analisador<br />Avaliador");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P1"								, "- Sério/a, tranqüilo/a, prudente, perspicaz, estrategista.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P2"								, "- Oferece ponderação, reflexão e análise, critério e discrição. Pode perceber as diversas opções e julgar com exatidão.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P3"								, "- Pode sofrer de falta de iniciativa ou de habilidade para inspirar ou motivar os outros. Pode ser excessivamente crítico/a.");
define("STR_PRISMA_CREATIVO"											, "Criativo");
define("STR_PRISMA_CREATIVO_P1"											, "- Imaginativo/a, independiente, heterodoxo/a, generador/a de ideas.");
define("STR_PRISMA_CREATIVO_P2"											, "- Pode ser brilhante e profundo/a nos seus enfoques. Resolve problemas difíceis com genialidade e/ou inteligência.");
define("STR_PRISMA_CREATIVO_P3"											, "- Pode se descuidar com facilidade dos detalhes e/ou do protocolo. Pode ser disperso/a ou pouco constante.");
define("STR_PRISMA_PERFECCIONISTA"										, "Perfeccionista");
define("STR_PRISMA_PERFECCIONISTA_P1"									, "- Detalhista, minucioso/a, cumpridor/a do dever, dedicado/a, consciente.");
define("STR_PRISMA_PERFECCIONISTA_P2"									, "- Costuma aplicar conhecimentos e técnicas especializadas. Tem alta capacidade e interesse para concluir trabalhos. É intolerante com a negligência ou falta de qualidade.");
define("STR_PRISMA_PERFECCIONISTA_P3"									, "- Preocupa-se muito quando as coisas não vão bem. É bastante resistente a delegar.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL"						, "PERFIL COMPETÊNCIA EMOCIONAL");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P1"						, "A tolerância geral ao estresse e o gerenciamento eficaz em relacionamentos profissionais e, portanto, na adaptação de um profissional a seu trabalho ou ambiente profissional.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P2"						, "Negociações, relações com clientes, colaboradores, gerenciamento de conflitos e possíveis pressões normais de trabalho exigem uma série de habilidades e controles emocionais que, dependendo do perfil pessoal do profissional, poderão ser mais ou menos eficazes.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P3"						, "No gráfico, as áreas sombreadas indicam a necessidade de realizar uma análise mais profunda do perfil e do contexto do cargo ocupado.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P4"						, "As combinações entre escores extremos (zonas sombreadas), indicam que existe a necessidade de realizar uma análise mais aprofundada da entrevista de seleção e/ou do desenvolvimento profissional, com vista a analisar possíveis repercussões,  em função das exigências do contexto profissional ou das responsabilidades do cargo ou função.");
define("STR_PRISMA_CONFIANZA_EN_OTROS"									, "Confianza en otros");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES"					, "PERFIL DE POSSÍVEIS GERADORES DE ESTRESSE");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P1"					, "Esse relatório fornece orientações sobre atividades, circunstâncias ou condições específicas susceptíveis de serem geradores de estresse para o profissional que respondeu ao questionário Prism@.");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P2"					, "No perfil, aparecem os fatores que podem ser geradores de maior estresse (9-10) ou de probabilidade relativamente alta (7-8).");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P3"					, "Os escores médios (4,5,6) ou baixos (1,2) não são indicadores de indiferença por parte do profissional. Simplesmente eles não parecem ser uma fonte provável de estresse no momento.");
define("STR_PRISMA_FACTORES_ORGANIZATIVOS"								, "FATORES ORGANIZACIONAIS");
define("STR_PRISMA_TRABAJO_RUTINARIO_Y_REPETITIVO"						, "TRABALHO ROTINEIRO E REPETITIVO");
define("STR_PRISMA_CAMBIOS_FRECUENTES"									, "MUDANÇAS FREQUENTES");
define("STR_PRISMA_ESTRUCTURAS_BUROCRATICAS"							, "ESTRUTURAS BUROCRÁTICAS");
define("STR_PRISMA_ENTORNOS_REACTIVOS"									, "AMBIENTES REATIVOS");
define("STR_PRISMA_FACTORES_RELACIONALES"								, "FATORES DE RELACIONAMENTO");
define("STR_PRISMA_HABLAR_EN_PUBLICO"									, "FALAR EM PÚBLICO");
define("STR_PRISMA_VENDER_NEGOCIAR"										, "VENDA / NEGOCIAÇÕES");
define("STR_PRISMA_DAR_MALAS_NOTICIAS"									, "TRANSMITIR MÁS NOTÍCIAS");
define("STR_PRISMA_FACTORES_MOTIVACIONALES"								, "FATORES MOTIVACIONAIS");
define("STR_PRISMA_FALTA_DE_PODER"										, "FALTA DE PODER");
define("STR_PRISMA_FALTA_DE_APOYO_SOCIAL"								, "FALTA DE APOIO SOCIAL");
define("STR_PRISMA_FALTA_DE_AUTONOMIA"									, "FALTA DE AUTONOMIA");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL"						, "FALTA DE PROGRESSO PROFISSIONAL");
define("STR_PRISMA_ESCASOS_RETOS_INTELECTUALES"							, "POUCOS DESAFIOS INTELECTUAIS");
define("STR_PRISMA_FALTA_DE_RECONOCIMIENTO"								, "FALTA DE RECONHECIMENTO");
define("STR_PRISMA_FACTORES_DEL_PUESTO_DE_TRABAJO"						, "FATORES DO CARGO");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES"				, "TOMADA DE DECISÕES RÁPIDAS / DIFÍCEIS");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS"						, "SOLUÇÃO DE PROBLEMAS COMPLEXOS");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO"						, "PRAZOS MUITO APERTADOS ");
define("STR_PRISMA_AMBIENTE_COMPETITIVO"								, "AMBIENTE COMPETITIVO");
define("STR_PRISMA_DIRIGIR_A_OTROS"										, "LIDERANÇA DE OUTROS");
define("STR_PRISMA_DEFINICION_DE_LOS_FACTORES_ESTRESORES"				, "DEFINIÇÃO DE GERADORES DE ESTRESSE ");
define("STR_PRISMA_TRABAJO_RUTINARIO_Y_REPETITIVO_DEF"					, "Trabalhos sem variedade de tarefas, previsíveis, sem mudanças, em que sempre se faz o mesmo ou da mesma maneira");
define("STR_PRISMA_CAMBIOS_FRECUENTES_DEF"								, "Mudanças frequentes ou inesperadas em conteúdos, sistemas ou práticas de trabalho.  Incerteza associada a mudanças em responsabilidades, funções ou requisitos do cargo.");
define("STR_PRISMA_ESTRUCTURAS_BUROCRATICAS_DEF"						, "Excesso de regras e/ou procedimentos. Exigências em termos de regulamentos, controles, burocracias ou documentação.");
define("STR_PRISMA_ENTORNOS_REACTIVOS_DEF"								, "Necessidade de resposta urgente ou reação imediata, sem oportunidade de realizar um planejamento prévio. Ambientes imprevisíveis ou ambientes que exigem a resolução imediata de problemas à medida que eles vão surgindo. Mudanças constantes em prioridades.");
define("STR_PRISMA_HABLAR_EN_PUBLICO_DEF"								, "Ter de comunicar ou fazer apresentações diante em público ou  auditório. Situações que exigem lidar ou interagir com pessoas desconhecidas ou grupos de grande dimensão.");
define("STR_PRISMA_VENDER_NEGOCIAR_DEF"									, "Situações que exigem a venda de ideias, produtos ou serviços. Ter de enfrentar ou convencer outras pessoas ou conduzir negociações difíceis com clientes, fornecedores, sindicatos, etc.");
define("STR_PRISMA_DAR_MALAS_NOTICIAS_DEF"								, "Ter de dar más notícias, informações negativas ou desagradáveis (a clientes, colegas ou colaboradores). Ter de comunicar ou implementar programas aos quais as pessoas se podem sentir inconfortáveis ou reagir mal.");
define("STR_PRISMA_CONFLICTOS_INTERPERSONALES"							, "CONFLITOS INTERPESSOAIS");
define("STR_PRISMA_CONFLICTOS_INTERPERSONALES_DEF"						, "Situações de discussão ou discordância. Ambientes em que existem relacionamentos conflitivos ou onde a convivência é difícil.  Situações em que é necessário resolver conflitos ou desacordos com outras pessoas.");
define("STR_PRISMA_FALTA_DE_PODER_DEF"									, "Falta de poder ou autoridade para exigir a execução de tarefas ou  alcançar os objetivos do grupo. Carência de responsabilidades para controlar projetos e pessoas.");
define("STR_PRISMA_FALTA_DE_APOYO_SOCIAL_DEF"							, "Situações em que é necessário tomar decisões ou iniciar ações que são discutíveis, pouco populares ou onde não há acordo, a aprovação do grupo ou consenso com outras pessoas.");
define("STR_PRISMA_FALTA_DE_AUTONOMIA_DEF"								, "Falta de liberdade para agir e/ou decidir sobre critérios pessoais.  Situações que não permitem agir por iniciativa própria, onde se depende de outras pessoas.");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL_BR"					, "FALTA DE PROGRESSO<br />PROFISSIONAL");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL_BR_DEF"				, "Cargos onde não se incentiva o avanço e o desenvolvimento profissional.  Falta de promoção e desenvolvimento profissional.  Falta de oportunidades de autoaperfeiçoamento.");
define("STR_PRISMA_ESCASOS_RETOS_INTELECTUALES_DEF"						, "Trabalho linear que não requer nenhum esforço intelectual. Poucas oportunidades de aprofundar em assuntos, trabalhos não especializados ou pouco técnicos. ");
define("STR_PRISMA_FALTA_DE_RECONOCIMIENTO_DEF"							, "Reconhecimento inexistente ou falta de reconhecimento. Falta de prêmios de incentivo ou recompensa por êxitos alcançados.");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES_BR"				, "TOMADA DE DECISÕES<br />RÁPIDAS / DIFÍCEIS ");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES_BR_DEF"			, "Situações que exigem uma tomada de decisão rápida ou ações rápidas. Tempo limitado para refletir.");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS_BR"					, "SOLUÇÃO DE PROBLEMAS<br />COMPLEXOS");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS_BR_DEF"				, "Cargos intelectualmente exigentes, que lidam com muitas informações ou analisam dados, índices ou relatórios extensos.");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO_BR"					, "PRAZOS MUITO<br />APERTADOS");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO_BR_DEF"				, "Cargos que requerem um ritmo muito alto de atividade, com paradas ou interrupções que dificultam o cumprimento de prazos ou compromissos.");
define("STR_PRISMA_AMBIENTE_COMPETITIVO_DEF"							, "Cargos em que há concorrência com outros colegas, situações de vendas agressivas, ou onde existe uma comparação constante de resultados.");
define("STR_PRISMA_DIRIGIR_A_OTROS_DEF"									, "Funções e/ou cargos que envolvem gerir pessoas que devem ser comandadas, controladas e/ou supervisionadas.");
define("STR_PRISMA_INDICADORES_DE_AJUSTE_A_LAS_COMPETENCIAS"			, "INDICADORES DE AJUSTE ÀS COMPETÊNCIAS");
define("STR_PRISMA_DEFINICION_DE_LAS_COMPETENCIAS"						, "DEFINIÇÃO DAS COMPETÊNCIAS");
define("STR_PRISMA_NOMBRE_INFORME_TXT"									, "Perfil de<br /><strong>personalidad<br />laboral</strong>");
define("STR_PRISMA_NOMBRE_INFORME_NARRATIVO_TXT"						, "Relatório narrativo");
define("PRISMA_NARRATIVO_INTP1" 										, "Esse relatório se baseia nas respostas do/a Sr./Sra. @usuario@ a um questionário de autoavaliação: o questionário de personalidade e competência profissional Prisma. Neste questionário você é convidado/a a descrever seu comportamento, preferências e atitudes relacionadas com diferentes aspetos de sua vida profissional.");
define("PRISMA_NARRATIVO_INTP2" 										, "Neste, você teve que escolher a afirmação que mais, e a que menos, se ajusta a seu perfil, de entre os blocos de três possíveis comportamentos.  Suas respostas foram comparadas com as de um grupo grande e relevante para obter um perfil de preferências do/da Sr./Sra. @usuario@ em relação a diferentes formas de se comportar no trabalho, agrupadas em quatro áreas principais: Energia e motivações, Controle Emocional e Tolerância ao Estresse, Orientação para relacionamentos e pessoas, Estilo de pensamento e potencial em recursos mentais.");
define("PRISMA_NARRATIVO_INTP3" 										, "Esse relatório descreve o perfil de personalidade do/a Sr./Sra. @usuario@ e, por isso, é confidencial. Ao analisar os resultados do questionário, é importante considerar que representam sua própria visão e o modo como entende seus próprios comportamentos, e não o modo como os outros poderão descrever sua personalidade.  A precisão do relatório depende da franqueza e da sinceridade com que respondeu ao perguntas do questionário, assim como seu próprio autoconhecimento.  Por esse motivo, os comentários que efetue nesse relatório se devem considerar como orientativos, fiáveis, embora não infalíveis. Este autorrelato pode proporcionar importantes indicadores sobre o estilo profissional do/da Sr./Sra. @usuario@, e provavelmente nos permitirá prever, em grande parte, seu comportamento perante diferentes situações.");
define("PRISMA_NARRATIVO_INTP4" 										, "Observe que o questionário descreve o estilo de comportamento preferido do/da Sr./Sra. @usuario@, mas não suas habilidades. O questionário fornece uma descrição completa de seu estilo atual e, portanto, o relatório é inevitavelmente genérico. A vida útil dos dados contidos no relatório é estimada que seja de entre 18 e 24 meses, dependendo das circunstâncias pessoais do inquirido e do cargo ocupado.  Surgindo mudanças significativas em sua vida ou uma mudança significativa no cargo ocupado, o questionário terá de ser preenchido novamente.");
define("PRISMA_NARRATIVO_INTP5" 										, "Se tiver alguma dúvida sobre o conteúdo desse relatório, contate com a pessoa que tenha recebido treinamento completo no uso do questionário Prisma.");
define("STR_ESTILO_ORENTACION_NARR_PRISMA" 								, "ESTILO DE ORIENTAÇÃO PARA RELACIONAMENTOS E PESSOAS");
define("STR_ESTILO_PENSAMIENTO_NARR_PRISMA" 							, "ESTILO DE PENSAMENTO E RECURSOS MENTAIS");
define("STR_NUM_PREGUNTAS_ERRONEAS" 									, "Número de perguntas erradas");
define("STR_NUM_PREGUNTAS_BLANCO" 										, "Número de perguntas em branco");
define("STR_VOCABULARIO"		 										, "VOCABULÁRIO");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_AL_VOCABULARIO"		, "Número total de perguntas referidas ao vocabulário");
define("STR_GRAMATICA"													, "GRAMÁTICA");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_GRAMATICA"			, "Número total de perguntas referidas ao gramática");
define("STR_COMPRENSION"		 										, "COMPREENSÃO");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_COMPRENSION_ESCRITA"			, "Número total de preguntas referentes a comprensión escrita");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_COMPRENSION_HABLADA"			, "Número total de preguntas referentes a comprensión hablada");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_COMPRENSION"			, "Número total de perguntas referidas ao compreensão");
define("STR_PRISMA_ESCALAS_DIFERENCIALES"								, "ESCALAS DIFERENCIAIS");
define("STR_CIP_NOMBRE_INFORME_TXT"									, "<strong>Inventario de<br />Orientación<br />Profesional CIP</strong>");
define("STR_CIP_BIENVENIDO_INFORME_ORIENTACION_PROFESIONAL_TXT"									, "Bienvenido/a  al Informe de Orientación Profesional");
define("STR_CIP_INTRO_P1"						, "Este informe ha sido elaborado a partir de las respuestas y ejercicios realizados por @candidato_prueba@.<br /><br />El objetivo esencial de este informe es apoyar el proceso de orientación para @candidato_prueba@ sobre las profesiones y/o carreras profesionales en las que ha demostrado especial interés y/o preferencia a lo largo de las respuestas dadas en el cuestionario CIP, y ayudarle a conocer mejor las capacidades que podrían favorecer el éxito en su elección o que, por el contrario, podrían implicarle algún grado de dificultad.");
define("STR_SOP_NOMBRE_INFORME_TXT"									, "<strong><font size='+2'>SOP</font> - Sistema de Orientación Profesional</strong>");
define("STR_SOP_BIENVENIDO_INFORME_ORIENTACION_PROFESIONAL_TXT"									, "INFORME DE:");
define("STR_SOP_INTRO_P1"						, "Este informe ha sido elaborado a partir de las respuestas y ejercicios realizados por @candidato_prueba@.<br /><br />El objetivo esencial de este informe es apoyar el proceso de orientación para @candidato_prueba@ sobre las profesiones y/o carreras profesionales en las que ha demostrado especial interés y/o preferencia a lo largo de las respuestas dadas en el cuestionario SOP, y ayudarle a conocer mejor las capacidades que podrían favorecer el éxito en su elección o que, por el contrario, podrían implicarle algún grado de dificultad.");
define("STR_CONTENIDO_DEL_INFORME"						, "Contenidos del informe");
define("STR_APARTADO_1"						, "Apartado 1: ÁREAS PROFESIONALES PREFERENTES");
define("STR_CIP_INTRO_P2"						, "En la primera parte del informe, se representa el gráfico que identifica el grado de interés (en porcentaje) que ha mostrado la persona hacia los campos profesionales y/o carreras profesionales generales asociadas que se han valorado.<br /><br />Este gráfico se acompaña de una breve síntesis escrita  identificando, según los datos cuantitativos obtenidos, las carreras y/o actividades que serían prioritarias y más motivantes para @candidato_prueba@.");
define("STR_SOP_INTRO_P2"						, "En la primera parte del informe, se representa el gráfico que identifica el grado de interés (en porcentaje) que ha mostrado la persona hacia los campos profesionales y/o carreras profesionales generales asociadas que se han valorado.<br /><br />Este gráfico se acompaña de una breve síntesis escrita  identificando, según los datos cuantitativos obtenidos, las carreras y/o actividades que serían prioritarias y más motivantes para @candidato_prueba@.");
define("STR_APARTADO_2"						, "Apartado 2: ÁREA APTITUDES");
define("STR_CIP_INTRO_P3"						, "En este apartado, aparecen representadas las puntuaciones obtenidas en los test de aptitudes realizados por el/la estudiante (rendimiento en la prueba) en una escala de percentiles. Esta puntuación final representa el percentil obtenido (representado  de 0 a 100) o lo que es lo mismo, la comparativa de los resultados obtenidos con una muestra significativa de estudiantes de similar edad y características académicas.");
define("STR_SOP_INTRO_P3"						, "En este apartado, aparecen representadas las puntuaciones obtenidas en los test de aptitudes realizados por el/la estudiante (rendimiento en la prueba) en una escala de percentiles. Esta puntuación final representa el percentil obtenido (representado  de 0 a 100) o lo que es lo mismo, la comparativa de los resultados obtenidos con una muestra significativa de estudiantes de similar edad y características académicas.");
define("STR_APARTADO_3"						, "Apartado 3: ORIENTACIÓN PROFESIONAL");
define("STR_CIP_INTRO_P4"						, "En este apartado se integra la información relativa a las carreras o actividades asociadas a las capacidades en las que @candidato_prueba@ ha demostrado tener especial fortaleza y aquellas que, por el rendimiento obtenido, podrían indicar algún tipo de dificultad.<br /><br />La motivación por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior. Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que querría trabajar a futuro.<br /><br />La integración entre ambos aspectos permite una visión muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_SOP_INTRO_P4"						, "En este apartado se integra la información relativa a las carreras o actividades asociadas a las capacidades en las que @candidato_prueba@ ha demostrado tener especial fortaleza y aquellas que, por el rendimiento obtenido, podrían indicar algún tipo de dificultad.<br /><br />La motivación por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior. Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que querría trabajar a futuro.<br /><br />La integración entre ambos aspectos permite una visión muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_INTEGRACION"						, "Integración");
define("STR_APARTADO_4"						, "Section 4: SKILLS");
define("STR_CIP_INTRO_P5"						, "De cara a la orientación, es importante tener siempre en cuenta que la motivación o interés (vocación) por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior (1ª Parte del Informe o Gráfico de Áreas Profesionales Preferentes del CIP).<br /><br />Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que se deben aplicar.<br /><br />La integración entre ambos aspectos, nos puede dar una orientación muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_SOP_INTRO_P5"						, "De cara a la orientación, es importante tener siempre en cuenta que la motivación o interés (vocación) por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior (1ª Parte del Informe o Gráfico de Áreas Profesionales Preferentes del SOP).<br /><br />Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que se deben aplicar.<br /><br />La integración entre ambos aspectos, nos puede dar una orientación muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_CIP_AREAS_PROFESIONALES_PREFERENTES_CIP", "FAVOURITE PROFESSIONAL AREAS QPI");
define("STR_CIP_AREAS_PROFESIONALES_PREFERENTES_CIP_TXT", "Below follow the results obtained from the answers provided in Questionnaire of Professional Interests carried out:");
define("STR_CIP_SINTESIS_DEL_PERFIL", "PROFILE SYNTHESIS");
define("STR_CIP_SINTESIS_DEL_PERFIL_P1", "Based on the scores obtained we can safely concluded that @candidato_prueba@:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P2", "Shows a very high interest in undertaking activities related to:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P3", "Shows a high interest in undertaking activities related to:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P4", "Shows a moderate interest in undertaking activities related to:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P5", "Shows a low interest in undertaking activities related to:");
define("STR_CIP_SINTESIS_DEL_PERFIL_P6", "None or very little interest in undertaking activities related to:");
define("STR_CIP_NINGUNA", "Any");
define("STR_CIP_AREAS_DE_APTITUDES", "AREA OF APTITUDES");
define("STR_CIP_AREAS_DE_APTITUDES_P1", "Resulting scores in a scale of 0 to 100 relate to the performance obtained in the aptitude tests carried out. The scores obtained in each test were compared with a significant sample from students who also answered QPI.");
define("STR_CIP_ORIENTACION_PROFESIONAL", "PROFESSIONAL GUIDANCE");
define("STR_CIP_ORIENTACION_PROFESIONAL_P1", "Presented below are listed the careers that best suit the results obtained in the aptitude exercises carried out:");
define("STR_CIP_AREA_DE_INTERES", "Area of interest");
define("STR_CIP_AREA_DE_INTERES_RV", "<strong style=\"font-weight: bold;\">Verbal<br />reasoning</strong><br /><font style=\"font-size:9px;\">Analysis and interpretation<br />of written and spoken information.<br />Draft documents.<br />Communication<br />activities.</font>");
define("STR_CIP_AREA_DE_INTERES_RN", "<strong style=\"font-weight: bold;\">Numerical<br />reasoning</strong><br /><font style=\"font-size:9px;\">Calculate or check<br />data.<br />Perform calculations.<br />Handle figures,<br />statistics, ratios.<br />Financial analyses.</font>");
define("STR_CIP_AREA_DE_INTERES_RL", "<strong style=\"font-weight: bold;\">Logic<br />reasoning</strong><br /><font style=\"font-size:9px;\">Create new concepts.<br />Develop new<br />approaches.<br />Answer why<br />and how questions.<br />Resolve logical<br />problems.</font>");
define("STR_CIP_AREA_DE_INTERES_RE", "<strong style=\"font-weight: bold;\">Spatial reasoning</strong><br /><font style=\"font-size:9px;\">Mentally recreate<br />figures or spaces.<br />Work in several plans.<br />Rotate figures or models<br />in space.<br />Handle maps, drawings<br />and/or graphic designs.</font>");
define("STR_CIP_INTERPRETACION", "INTERPRETATION");
define("STR_CIP_INTERPRETACION_P1", "Already has the optimal capabilities for content development in the career indicated.");
define("STR_CIP_INTERPRETACION_P2", "Has the potential for content development in the career indicated.");
define("STR_CIP_INTERPRETACION_P3", "May encounter some difficulties or need reinforcements in some of the contents in the career indicated.");
define("STR_CIP_INTERPRETACION_P4", "There are no results in this test.");
define("STR_CIP_INTERPRETACION_P5", "It is not a critical capability in this career, although it may make it easier to tackle some complementary aspects.");
define("STR_CIP_ESCALA", "Scale");
define("STR_CIP_VERBAL", "VERBAL");
define("STR_CIP_LOGICO", "LOGIC");
define("STR_CIP_NUMERICO", "NUMERICAL");
define("STR_CIP_ESPACIAL", "SPATIAL");

define("STR_PRUEBAS_ADMISION_NIVEL_GRADO"		, "Pruebas Admisión Nivel Grado");
define("STR_PRISMA_AREA_DE_FORTALEZA", "STRENGTH AREA");
define("STR_PRISMA_SIEMPRE","SEMPRE");

define("STR_INFORME_DE_ATENCION_COMERCIAL","INFORME DE ATENCIÓN COMERCIAL");
define("STR_BAJO_POTENCIAL_0_A_35","Bajo Potencial: 0 a 35");
define("STR_MEDIO_POTENCIAL_36_A_70","Medio Potencial: 36 a 70");
define("STR_ALTO_POTENCIAL_71_A_100","Alto Potencial: 71 a 100");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL"			, "PERFIL DE COMPETENCIAS");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario Prisma  con respecto a los comportamientos del Cuestionario Prisma asociados a la definición de los Valores, Competencias Corporativas y Específicas de Corporación Empresarial Pascual.");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P2"	, "Los resultados obtenidos en el perfil, son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario. Para profundizar en los detalles del perfil, recomendamos acudir al informe narrativo o informe de interpretación automática que aparece a continuación.");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P3"	, "Recordar que, el cuestionario al que la persona ha respondido, obliga a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no puede lograr altas puntuaciones en todas las competencias.");
define("STR_PRISMA_DEFINICION_DE_LAS_COMPETENCIAS_PASCUAL"	, "DEFINICIÓN DE LAS COMPETENCIAS Y VALORES GLP");

define("STR_JN36_PERFIL_PSICOLOGICO_HUMANO_DE_JESUS_DE_NAZARET"		, "PERFIL PSICOLÓGICO-HUMANO<br />DE JESUS DE NAZARÉ");
define("STR_JN36_BAJO"												, "Bajo");
define("STR_JN36_ME_BA"												, "Me.-Ba.");
define("STR_JN36_MEDIO"												, "Medio");
define("STR_JN36_ME_AL"												, "Me.-Al.");
define("STR_JN36_ALTO"												, "Alto");
define("STR_JN36_TU_PERFIL"											, "Seu Perfil");
define("STR_JN36_PUNTOS"											, "pontos");
define("STR_JN36_ZONA_BAJA"											, "ZONA BAIXA");
define("STR_JN36_ZONA_MEDIA_BAJA"									, "ZONA MÉDIA-BAIXA");
define("STR_JN36_ZONA_MEDIA"										, "ZONA MÉDIA");
define("STR_JN36_ZONA_MEDIA_ALTA"									, "ZONA MÉDIA-ALTA");
define("STR_JN36_ZONA_ALTA"											, "ZONA ALTA");
define("STR_JN36_COLOR_AZUL"										, "COR AZUL");
define("STR_JN36_COLOR_AMARILLO"									, "COR AMARELO");
define("STR_JN36_COLOR_VERDE"										, "COR VERDE");
define("STR_JN36_COLOR_NARANJA"										, "COR LARANJA");
define("STR_JN36_COLOR_ROSA"										, "COR-DE-ROSA");
define("STR_JN36_INFORME_PERSONAL_E_INDIVIDUALIZADO"				, "RELATÓRIO PESSOAL E INDIVIDUALIZADO");
define("STR_JN36_PIE_INFORMES" 										, "é uma marca registrada. A reprodução total ou parcial deste relatório, por qualquer meio, infringe os direitos de Copyright.");
define("STR_JN36_O_MAS" 											, " ou mais");

define("STR_INFORME_DE_ORIENTACION_COMERCIAL" 											, "RELATÓRIO DE ORIENTAÇÃO COMERCIAL");
define("STR_TOC_INFORME_EXPERTO" 											, "TOC RELATÓRIO ESPECIALISTA");
define("GRAFICO_DEL_PERFIL_COMPETENCIAL" 											, "GRÁFICO DO PERFIL DE COMPETÊNCIA");
define("STR_NIVEL_DE_COMPETENCIAS_PRIORITARIAS" 											, "Nível de competências prioritárias");
define("STR_NIVEL_DE_TOLERANCIA_AL_ESTRES" 											, "Nível de tolerância ao stress");
define("STR_NIVEL_DE_COMPETENCIAS_SECUNDARIAS" 											, "Nível de competências secundárias");

define("STR_ORIENTACION_AL_CLIENTE" 											, "Orientação ao cliente");
define("STR_ORIENTACION_A_RESULTADOS" 											, "Orientação a Resultados");
define("STR_COMUNICACION_PERSUASIVA" 											, "Comunicação Persuasiva");
define("STR_DESARROLLO_DE_RELACIONES" 											, "Desenvolvimento de relações");
define("STR_TOMA_DE_DECISIONES" 											, "Toma de decisões");
define("STR_TOLERANCIA_AL_ESTRES" 											, "Tolerância ao stress");
define("STR_ORIENTACION_A_LA_CALIDAD" 											, "Orientação a qualidade");
define("STR_PLANIFICACION_ORGANIZACION" 											, "Planejamento /organização");
define("STR_ESPECIALIZACION" 											, "Especialização");
define("STR_ANALISIS_Y_SOLUCION_DE_PROBLEMAS" 											, "Análise e solução de problemas");

define("STR_NIVEL_BAJO" 								, "Nível baixo");
define("STR_NIVEL_MEDIO" 								, "Nível médio");
define("STR_NIVEL_ALTO" 								, "Nível alto");

define("STR_CML_INFORME_DE_MOTIVACIONES_LABORALES" 		, "RELATÓRIO DE MOTIVAÇÕES LABORAIS");
define("STR_CML_PERFIL_DE_MOTIVACIONES" 				, "PERFIL DE MOTIVAÇÕES");
define("STR_CML_COMENTARIOS" 							, "COMENTÁRIOS");

define("STR_SEAS_TEST_CONOCIMIENTOS_P1" 											, "Estas puntuaciones están basadas en las respuestas dadas por el/la candidato/a a una serie de preguntas relacionadas con aspectos técnicos del trabajo de Asesor según la especialidad a la que está optando. No obstante, este resultado sólo es información complementaria al resto de datos contemplados en este informe.");
define("STR_SEAS_TEST_CONOCIMIENTOS_P2" 											, "Las barras indican la autovaloración que el/la candidato/a hace de su nivel de conocimientos en comparación con la puntuación real obtenida tras contestar al Test.");
define("STR_SEAS_TEST_MEMORIA_P1" 											, "Esta prueba tiene como objetivo evaluar la capacidad del candidato/a para memorizar datos relacionados con los clientes, de su vida personal, profesional, datos relacionados con vehículos adquiridos, averías que ha tenido, etc. Los análisis previos del perfil de un Asesor demuestran que son datos utilizados frecuentemente por los asesores en su relación con los clientes, y que correlacionan positivamente con desempeños de éxito.");
define("STR_SEAS_TEST_MEMORIA_P2" 											, "No obstante, este resultado sólo es información complementaria al resto de datos contemplados en este informe.");
define("STR_SEAS_TEST_FLEXIBILIDAD_MENTAL_P1"								, "Esta prueba mide la capacidad de una persona para modificar el enfoque, encontrar alternativas variadas a la hora de resolver problemas y la flexibilidad de comportamiento para la adaptación a cambios de situación. Es un test de dificultad y valor de predicción probado para puestos que impliquen variedad de tareas y necesidad de dar respuesta a imprevistos continuos.");

define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_105"			, "Perfil de Competências");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_128"			, "Perfil de Competências");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_105"			, "PERFIL DE COMPETENCIAS");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_105_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario Prisma con respecto a los comportamientos del Cuestionario Prisma asociados a la definición de las Competencias de Banco Hipotecario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_105_INTRO_P2"	, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_105_INTRO_P3"	, "El cuestionario Prisma obliga a la persona que lo responde a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no se puede lograr altas puntuaciones en todas las competencias.");

define("STR_105_AREA_CLAVE_DE_MEJORA_BR"								, "Aún no<br /> desarrollado");
define("STR_105_AREA_DE_POTENCIAL_DESARROLLO"						, "Necesita<br /> mejorar");
define("STR_105_AREA_DE_DESARROLLO_2BR"								, "Alcanza lo <br />esperado");
define("STR_105_AREA_DE_POTENCIAL_FORTALEZA"							, "Supera lo <br /> esperado");
define("STR_105_AREA_DE_FORTALEZA_2BR"								, "Ejemplo a <br />seguir e <br /> influyente");

define("STR_105_AREA_CLAVE_DE_MEJORA"								, "ÁREA CLAVE DE MEJORA");
define("STR_105_AREA_POTENCIAL_DESARROLLO"							, "ÁREA POTENCIAL DESARROLLO");
define("STR_105_AREA_EN_DESARROLLO"									, "ÁREA EN DESARROLLO");
define("STR_105_AREA_POTENCIAL_FORTALEZA"							, "ÁREA POTENCIAL FORTALEZA");
define("STR_105_AREA_DE_FORTALEZA"									, "ÁREA DE FORTALEZA");

define("STR_105_DETALLE DIMENSIONES_COMPETENCIAS"					, "DETALLE DIMENSIONES POR CADA UNA DE LAS COMPETENCIAS");
define("STR_105_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "A continuación, se muestra el detalle de las puntuaciones obtenidas en cada una de las dimensiones que componen a su vez las Competencias de Banco Hipotecario.");

define("STR_128_DETALLE DIMENSIONES_COMPETENCIAS"					, "DETALLE DIMENSIONES POR CADA UNA DE LAS COMPETENCIAS");
define("STR_128_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "A continuación, se muestra el detalle de las puntuaciones obtenidas en cada una de las dimensiones que componen a su vez las Competencias de Asitur.");

define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario CEL16 con respecto a los comportamientos del CEL16 asociados a la definición de las Competencias de Banco Hipotecario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P2"	, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_106_INTRO_P3"	, "El cuestionario CEL16 obliga a la persona que lo responde a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no se puede lograr altas puntuaciones en todas las competencias.");

define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario CEL16 con respecto a los comportamientos del CEL16 asociados a la definición de las Competencias de Asitur.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P2"	, "Los resultados obtenidos en el perfil son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_128_INTRO_P3"	, "El cuestionario CEL16 obliga a la persona que lo responde a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no se puede lograr altas puntuaciones en todas las competencias.");

define("STR_DEF_CANDIDATO"                         , "Nome");
define("STR_PD"                         , "DS");
define("STR_PC"                         , "PT");
define("STR_COMPRENSION_ESCRITA"                         , "READING COMPREHENSION");
define("STR_COMPRENSION_HABLADA"                         , "LISTENING COMPREHENSION");
define("STR_RESULTADOS_ELT_ESCRITO"                         , "ELT Advanced Score (includes Vocabulary, Grammar and Reading Comprehension)");
define("STR_RESULTADOS_ELT_HABLADA"                         , "ELT Advanced Score (includes Listening Comprehension)");
define("STR_SR_A"                         , "Mr/Ms");
?>
