<?php
//TEXTOS EN INFORMES
define("STR_PIE_INFORMES" 												, "é uma marca registrada pelos Psicólogos Empresariales. A reprodução total ou parcial deste relatório, por qualquer meio, infringe os direitos de Copyright.");
define("STR_NOMBRE_APELLIDOS"											, "Nome completo");
define("STR_FECHA_INFORME"												, "Data do relatório");
define("STR_INTRODUCCION" 												, "INTRODUÇÃO");
define("STR_INTRODUCCION_CAPS" 											, "INTRODUÇÃO");
define("STR_PUNTUACION_DIRECTA" 										, "Pontuação Direta");
define("STR_PUNTUACION_PERCENTIL" 										, "Pontuação Percentil");
define("STR_INDICE_RAPIDEZ" 											, "Índice de Rapidez");
define("STR_INDICE_PRECISION" 											, "Índice de Precisão");
define("STR_PRODUCTO_RENDIMIENTO" 										, "Produto de Rendimento");
define("STR_ESTILO_PROCESAMIENTO_MENTAL" 								, "Estilos de Processamento Mental");
define("STR_NUM_TOTAL_PREGUNTAS" 										, "Número total de perguntas do Teste");
define("STR_NUM_PREGUNTAS_ACERTADAS" 									, "Número de perguntas corretas");
define("STR_PUNT_INFORMES" 												, "Pontuaçao");
define("STR_BAJO_POTENCIAL" 											, "POTENCIAL BAIXO");
define("STR_MEDIO_POTENCIAL" 											, "POTENCIAL MÉDIO");
define("STR_ALTO_POTENCIAL" 											, "POTENCIAL ALTO");
define("STR_ESTE_INFORME_REPRESENTA" 									, "Este relatório apresenta as seguintes informações a partir dos resultados obtidos com o Teste:");
define("STR_EXP_PUNT_PECENTIL" 											, "Indica a porcentagem de pessoas que fizeram menos pontos. O percentil 35, por exemplo, indica a pontuação abaixo da qual ficaram 35% das pessoas do grupo.");
define("STR_EXP_PUNT_DIRECTA" 											, "Baseada no número de perguntas respondidas corretamente.");
define("STR_EXP_INDICE_RAPIDEZ" 										, "A rapidez faz parte da base do aprendizado e da aptidão. Este índice é obtido a partir do número de perguntas respondidas em um período de tempo limitado.");
define("STR_EXP_INDICE_PRECISION" 										, "Representa a qualidade em relação à quantidade, que seria a rapidez. Este índice é obtido em função do número de perguntas acertadas em um período de tempo limitado.");
define("STR_EXP_PRODUCTO_RENDIMIENTO" 									, "Representa a interação entre rapidez-precisão ou precisão-rapidez, dando ênfase a uma ou a outra, de acordo com o estilo ou a atitude de cada um.");
define("STR_EXP_ESTILO_PROCESAMIENTO_MENTAL"		 					, "A partir da análise dos índices de rapidez e precisão é possível determinar qual é o estilo ou mapa mental de uma pessoa. Conhecer seu estilo de processamento mental ajuda a determinar em que tipo de tarefas ou atividades ela renderá mais.");
define("STR_PRISMA_INTRO_P1" 											, "Este relatório se baseia nas respostas da pessoa que respondeu o questionário PRISM@. Ele foi gerado de maneira automática por meio do Sistema Especialista de correção on-line da Psicólogos Empresariales.");
define("STR_PRISMA_INTRO_P2" 											, "A Psicólogos Empresariales só se responsabiliza pela versão original gerada por esse sistema e não por possíveis modificações ou anexos de outros usuários como versão posterior ou adaptações de acordo com outras percepções sobre a pessoa que respondeu o questionário.");
define("STR_PRISMA_INTRO_P3" 											, "O relatório geral, decorrente de 32 escalas originais, divide-se em nove índices gerais e quatro áreas fundamentais, que são a base da interpretação:");
define("STR_PRISMA_INTRO_P4" 											, "- ENERGIAS E MOTIVAÇÕES.");
define("STR_PRISMA_INTRO_P5" 											, "- CONTROLE EMOCIONAL E TOLERÂNCIA AO ESTRESSE.");
define("STR_PRISMA_INTRO_P6" 											, "- ESTILOS DE RELAÇÃO (Orientaçâo a relaçâo, ás pessoas e Influência, ascendência e comando).");
define("STR_PRISMA_INTRO_P7" 											, "- RECURSOS E ESTILO DE PROCESSAMENTO MENTAL (Competências analíticas, Potencial de recursos mentais, Flexibilidade e Estilo de trabalho).");
define("STR_PRISMA_INTRO_P8" 											, "Os outros relatórios de Competência e Perfis derivados deste são opcionais e descritos de maneira independente.");
define("STR_PRISMA_INTRO_P9" 											, "Recomendamos que, no momento de interpretar os seus resultados, sempre sejam levadas em consideração as pontuações de consistência obtidas.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA"					, "INTERPRETAÇÃO DA ESCALA DE CONSISTÊNCIA");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P1"				, "A Escala de Consistência nos proporciona indicadores gerais do estilo de resposta ou atitude do candidato/a. É um questionário de 'resposta obrigatória', o que delimita bastante a 'distorção motivacional' ou a tendência de revelar um perfil desejado ou conveniente.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P2"				, "A pontuação na escala de 'Consistência' expressa o grau de esforço do candidato/a para manter a coerência ou a congruência entre as respostas dadas no questionário.<br />");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P3A"				, "Consistência de 9-10");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P3B"				, " Um grau de congruência tão alto pode indicar uma possível manipulação ou o desejo de revelar uma imagem determinada de si mesmo/a. Recomendamos estudar especialmente as escalas com pontuações muito altas (9, 10) e muito baixas (1, 2).");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P4A"				, "Consistencia Baja (1-2)");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P4B"				, " Um congruência tão baixa pode indicar que a pessoa respondeu sem refletir, por não compreender as instruções, por falta de comprometimento ou por falta de autoconhecimento.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P5A"				, "Consistência de 3-4 e 7-8");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P5B"				, " É um pouco desvio da pontuação ideal, portanto, é possível encontrar algumas distorções em alguns escala, apesar de não afectar para o perfil geral dos resultados.");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P6A"				, "Consistência de 5-6");
define("STR_PRISMA_INTERPRETACION_ESCALA_CONSISTENCIA_P6B"				, " Geralmente indica que a pessoa respondeu com motivação ou interesse e não encontrou dificuldades para responder ou compreender o questionário.");
define("STR_PRISMA_PERFIL_DE_PERSONALIDAD_LABORAL"						, "PERFIL DE PERSONALIDADE PROFISSIONAL");
define("STR_PRISMA_BAJO"												, "Baixo");
define("STR_PRISMA_ME_BA"												, "Me.-Ba.");
define("STR_PRISMA_MEDIO"												, "Médio");
define("STR_PRISMA_ME_AL"												, "Me.-Al.");
define("STR_PRISMA_ALTO"												, "Alto");
define("STR_PRISMA_DINAMISMO_Y_ACTIVIDAD"								, "Dinamismo e atividade");
define("STR_PRISMA_DINAMISMO_Y_ACTIVIDAD_TXT"							, "Gostam das atividades que exigem esforço e alto grau de atividade. Mantêm-se sempre ocupados/as.");
define("STR_PRISMA_CONSTANCIA_PERSEVERANCIA"							, "Constância/ Perseverança");
define("STR_PRISMA_CONSTANCIA_PERSEVERANCIA_TXT"						, "Esforçam-se para terminar as tarefas a tempo. Acabam o que começam. São constantes e cumprem os prazos.");
define("STR_PRISMA_AMBICION_DE_METAS_Y_LOGROS"							, "Ambição por metas e conquistas");
define("STR_PRISMA_AMBICION_DE_METAS_Y_LOGROS_TXT"						, "São auto-exigentes. Buscam objetivos e metas difíceis. Sua ambição é se superar e melhorar.");
define("STR_PRISMA_COMPETITIVIDAD"										, "Competitividade");
define("STR_PRISMA_COMPETITIVIDAD_TXT"									, "Gostam das atividades competitivas. Participam para ganhar e ser os melhores quando se comparam aos outros. Não suportam perder.");
define("STR_PRISMA_DECISION"											, "Decisão");
define("STR_PRISMA_DECISION_TXT"										, "Ponderam as alternativas e tomam decisões com rapidez, dispostos a agir.");
define("STR_PRISMA_TENSION_INTERNA"										, "Tensão interna");
define("STR_PRISMA_TENSION_INTERNA_TXT"									, "Internamente tensos. Dificilmente relaxam. Sentem ansiedade diante das pressões e situações difíceis.");
define("STR_PRISMA_AUTODOMINIO"											, "Autocontrole");
define("STR_PRISMA_AUTODOMINIO_TXT"										, "São tranqüilos/as. Mantêm o domínio de si mesmos/as em situações importantes ou diante de problemas. A pressão e/ou as preocupações não lhes afetam. Sabem administrar a ansiedade.");
define("STR_PRISMA_RESISTENCIA_EMOCIONAL"								, "Resistência emocional");
define("STR_PRISMA_RESISTENCIA_EMOCIONAL_TXT"							, "Nao se preocupam com a opinião dos outros. Não reagem a críticas pessoais. E não costumam se sentir ofendidos/as por elas.");
define("STR_PRISMA_CONTROL_EXTERNO"										, "Controle Externo");
define("STR_PRISMA_CONTROL_EXTERNO_TXT"									, "Controlam as suas emoções e não demonstram os seus sentimentos, seja de entusiasmo ou de mal-estar.");
define("STR_PRISMA_CONFIANZA_EN_LOS_DEMAS"								, "Confiança nos outros");
define("STR_PRISMA_CONFIANZA_EN_LOS_DEMAS_TXT"							, "Consideram os outros honestos e confiáveis. Acreditam na palavra e na bondade das pessoas.");
define("STR_PRISMA_ACTITUD_POSITIVA"									, "Atitude Positiva");
define("STR_PRISMA_ACTITUD_POSITIVA_TXT"								, "Acreditam que o futuro será favorável. Tendem a ver o lado positivo de cada situação. São otimistas.");
define("STR_PRISMA_EXTROVERSION"										, "Extroversão");
define("STR_PRISMA_EXTROVERSION_TXT"									, "Gostam de animar os grupos ou as reuniões. São bons de papo. Gostam do protagonismo nas relações sociais.");
define("STR_PRISMA_AFILIACION_SOCIABILIDAD"								, "Afiliação / Sociabilidade");
define("STR_PRISMA_AFILIACION_SOCIABILIDAD_TXT"							, "Precisam estar com pessoas. Gostam da companhia dos outros mesmo que não sejam protagonistas. Não gostam da solidão. Colaboram com os outros e gostam de prestar servicos");
define("STR_PRISMA_HABILIDAD_RELACIONAL"								, "Habilidade de relacionamento");
define("STR_PRISMA_HABILIDAD_RELACIONAL_TXT"							, "Agem com segurança nas reuniões e em público. Sabem controlar as situações e relacionar-se em público. Causam impacto.");
define("STR_PRISMA_EMPATIA"												, "Empatia");
define("STR_PRISMA_EMPATIA_TXT"											, "Interessam-se e têm consideração pelos outros. São tolerantes e compreensivos/as. Preocupam-se em solucionar os problemas das pessoas.");
define("STR_PRISMA_MODESTIA"											, "Modéstia");
define("STR_PRISMA_MODESTIA_TXT"										, "Preferem não se vangloriar das suas conquistas e qualidades. São prudentes e humildes. Não gostam de falar de si mesmos.");
define("STR_PRISMA_CONSENSUADOR"										, "Consenso");
define("STR_PRISMA_CONSENSUADOR_TXT"									, "Consultam e ouvem os outros. Buscam apoio para tomar decisões. Preferem decidir por acordo.");
define("STR_PRISMA_PERSUASION"											, "Persuasão");
define("STR_PRISMA_PERSUASION_TXT"										, "Influentes. Eloqüentes. Tentam convencer os outros a aceitar os seus pontos de vista. Podem ser excelentes vendedores ou negociadores eficazes.");
define("STR_PRISMA_VOLUNTAD_DE_MANDO_Y_DIRECCION"						, "Vontade de comandar e dirigir");
define("STR_PRISMA_VOLUNTAD_DE_MANDO_Y_DIRECCION_TXT"					, "Preferem assumir a liderança nos grupos. Gostam de dirigir, organizar e supervisionar os projetos e/ou as pessoas.");
define("STR_PRISMA_AUTONOMIA_AUTODETERMINACION"							, "Autonomia/ Autodeterminação");
define("STR_PRISMA_AUTONOMIA_AUTODETERMINACION_TXT"						, "Agem e pensam por si mesmos/as. Não seguem as opiniões da maioria. Preferem fazer as coisas à sua maneira. São auto-suficientes.");
define("STR_PRISMA_DIRECTO_ESPONTANEO"									, "Direto / Espontâneo");
define("STR_PRISMA_DIRECTO_ESPONTANEO_TXT"								, "Costumam dizer o que pensam clara e diretamente. São objetivo/as e expressam as suas críticas com segurança.");
define("STR_PRISMA_ANALISIS_OBJETIVO"									, "Análise objetiva");
define("STR_PRISMA_ANALISIS_OBJETIVO_TXT"								, "Baseiam as suas decisões e propostas em dados e fatos objetivos. As informações que mais valorizam são os números e os dados quantitativos.");
define("STR_PRISMA_ANALISIS_DE_RIESGOS"									, "Análise de riscos");
define("STR_PRISMA_ANALISIS_DE_RIESGOS_TXT"								, "Analisam a situação com discernimento, buscando os riscos ou problemas potenciais de cada situação.");
define("STR_PRISMA_ANALISIS_DE_PERSONAS"								, "Análise de pessoas");
define("STR_PRISMA_ANALISIS_DE_PERSONAS_TXT"							, "Quando analisam situações ou tomam decisões, interessam-se pelas razões e/ou motivos do comportamento das pessoas.");
define("STR_PRISMA_PROFUNDIDAD_CONCEPTUAL"								, "Profundidade conceitual");
define("STR_PRISMA_PROFUNDIDAD_CONCEPTUAL_TXT"							, "Gostam de trabalhar com modelos e bases teóricas. Pesquisam e analisam com profundidade os assuntos. São curiosos/as mentalmente.");
define("STR_PRISMA_INNOVACION_Y_SOLUCIONES"								, "Inovação e soluções");
define("STR_PRISMA_INNOVACION_Y_SOLUCIONES_TXT"							, "Contribuem com novas idéias e soluções originais. Propõem melhoras e idéias criativas. Gostam mais de criar do que de realizar.");
define("STR_PRISMA_PREVISION_Y_PLANIFICACION"							, "Previsão e planejamento");
define("STR_PRISMA_PREVISION_Y_PLANIFICACION_TXT"						, "Têm visão a médio e longo prazos. Com perspectiva. Orientam-se para o futuro. Consideram os antecedentes e prevêem as conseqüências.");
define("STR_PRISMA_ADAPTABILIDAD_FLEXIBILIDAD"							, "Adaptabilidade/ Flexibilidade");
define("STR_PRISMA_ADAPTABILIDAD_FLEXIBILIDAD_TXT"						, "Têm facilidade para se adaptar às diversas pessoas e circunstâncias. São abertos a mudanças e inovações.");
define("STR_PRISMA_PRO_CAMBIOS"											, "Pró-mudança");
define("STR_PRISMA_PRO_CAMBIOS_TXT"										, "Preferem mudar constantemente. Buscam a variedade de tarefas e atividades. Gostam de experimentar coisas novas. A rotina é entediante para eles/as.");
define("STR_PRISMA_PRAGMATISMO"											, "Pragmatismo");
define("STR_PRISMA_PRAGMATISMO_TXT"										, "Concentram-se no operacional e viável. Concretizam e se atêm ao possível. Procuram e aplicam diretamente soluções práticas.");
define("STR_PRISMA_ORDEN_ORGANIZACION"									, "Ordem / Organização");
define("STR_PRISMA_ORDEN_ORGANIZACION_TXT"								, "Realizam as tarefas minuciosa e detalhadamente. São organizados/as e sistemáticos/as. Não toleram a bagunça.");
define("STR_PRISMA_DISCIPLINA"											, "Disciplina");
define("STR_PRISMA_DISCIPLINA_TXT"										, "Respeitam as normas e seguem os procedimentos estabelecidos. São muito rigorosos/as no cumprimento das normas.");
define("STR_PRISMA_G_C"													, "G.C.");
define("STR_PRISMA_STR_PRISMA_G_C_TXT"									, "Grau de congruência nas respostas");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL"				, "PERFIL GERAL DE PERSONALIDADE PROFISSIONAL");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL_P1"			, "A partir das respostas dadas pelo/a candidato/a no questionário será obtido o perfil geral das 12 escalas nas quais se integram as 32 contidas no questionário.");
define("STR_PRISMA_PERFIL_GENERAL_DE_PERSONALIDAD_LABORAL_P2"			, "Seu conteúdo oferece, portanto, um resumo da tendência habitual de comportamento da pessoa que respondeu o questionário, permitindo obter uma visão rápida e global do seu perfil profissional.");
define("STR_PRISMA_NIVEL_GENERAL_DE"									, "NÍVEL GERAL DE");
define("STR_PRISMA_ENERGIA_Y_MOTIVACIONES"								, "Energia e Motivação");
define("STR_PRISMA_EXTROVERSION_Y_PROTAGONISMO_SOCIAL"					, "Extroversão e <br />Protagonismo Social");
define("STR_PRISMA_INFLUENCIA_MANDO_O_ASCENDENCIA"						, "Influência, comando ou<br /> Ascendência");
define("STR_PRISMA_EMPATIA_Y_ORIENTACION_A_LAS_PERSONAS"				, "Empatia e orientação<br /> às pessoas");
define("STR_PRISMA_ORIENTACION_A_TAREAS_Y_OBJETIVOS"					, "Orientação ao<br /> tarefas e objetivos");
define("STR_PRISMA_POTENCIA_ANALITICA_Y_SOLUCIAON_DE_PROBLEMAS"			, "Potencial analítico e de<br /> Solução de problemas");
define("STR_PRISMA_FLEXIBILIDAD_MENTAL"									, "Flexibilidade Mental");
define("STR_PRISMA_DISCIPLINA_Y_ORDEN"									, "Disciplina e Ordem");
define("STR_PRISMA_PRECISION_Y_CALIDAD"									, "Precisão e Qualidade");
define("STR_PRISMA_RAPIDEZ_Y_OPERATIVIDAD"								, "Rapidez e Operacionalidade");
define("STR_PRISMA_CONTROL_EMOCIONAL"									, "Controle Externo");
define("STR_PRISMA_TOLERANCIA_AL_ESTRES"								, "Tolerância ao Estresse");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS"					, "RELATÓRIO DE COMPETÊNCIAS");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P1"			, "Abaixo encontra-se informação mais detalhada sobre o perfil de competências.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P2"			, "A coluna da esquerda indica a habilidade. Os comportamentos que aparecem na coluna central são aspectos-chaves que contribuem positiva ou negativamente em cada competência.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P3"			, "O nível de desenvolvimento da competência e o impacto de cada uma no perfil geral aparecem na coluna da direita.");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P4"			, "");
define("STR_PRISMA_INFORME_ORIENTADO_A_COMPETENCIAS_INTRO_P5"			, "");
define("STR_PRISMA_COMPETENCIAS_PARA_LA_GESTION"						, "COMPETÊNCIAS PARA A GESTÃO");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_BR"								, "INFLUÊNCIA<br />E<br />LIDERANÇA");
define("STR_PRISMA_A_VECES"												, "ÀS VEZES");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_A_VECES_TXT"						, "Assume a responsabilidade e o controle nas equipes e/ou nos projetos. Responsabiliza-se pela atribuição de objetivos a pessoas ou equipes. Estimula os outros a alcançarem os objetivos. Consegue comandar eficazmente pessoas/equipes.");
define("STR_PRISMA_AREA_EN_DESARROLLO"									, "ÁREA EM DESENVOLVIMENTO");
define("STR_PRISMA_PLANIFICACION"										, "PLANEJAMENTO");
define("STR_PRISMA_CASI_NUNCA"											, "QUASE NUNCA");
define("STR_PRISMA_STR_PRISMA_PLANIFICACION_CASI_NUNCA_TXT"				, "Organiza e distribui os trabalhos das pessoas ou os projetos. Dedica tempo, recursos ou esforços para planejar eficazmente. Realiza previsões realistas dos prazos para realização e entrega. Realiza os trabalhos com ordem e de método.");
define("STR_PRISMA_AREA_POTENCIAL_DESARROLLO"							, "ÁREA DE POTENCIAL DESENVOLVIMENTO");
define("STR_PRISMA_COMUNICACION_SOCIAL_BR"								, "COMUNICAÇÃO<br /> COMUNICAÇÃO SOCIAL");
define("STR_PRISMA_NUNCA"												, "NUNCA");
define("STR_PRISMA_COMUNICACION_SOCIAL_NUNCA_TXT"						, "Sabe se expressar com clareza e eficácia em reuniões ou eventos. Realiza discursos e/ou comunicações com fluência e eficácia. Consegue atrair a atenção do público em palestras ou apresentações. Sente-se seguro/a e à vontade ao intervir em público.");
define("STR_PRISMA_AREA_CLAVE_DE_MEJORA"								, "ÁREA CHAVE DE MELHORIA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_BR"						, "PERSUASÃO E<br />NEGOCIAÇÃO");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_A_VECES_TXT"				, "Convence outras pessoas com eficácia. Negocia com sucesso e eficácia com seus interlocutores ou concorrentes. Consegue fazer com que os outros aceitem os seus projetos, opiniões ou sugestões com facilidade. Induz com eficácia os outros a mudarem de opinião.");
define("STR_PRISMA_COMPETENCIAS_TECNICAS"								, "COMPETÊNCIAS TÉCNICAS");
define("STR_PRISMA_DOMINIO_DE_SU_ESPECIALIDAD"							, "DOMÍNIO<br />DA SUA<br />ESPECIALIDADE");
define("STR_PRISMA_STR_PRISMA_DOMINIO_DE_SU_ESPECIALIDAD_A_VECES_TXT"	, "Demonstra um alto domínio na sua área de especialização. Procura se manter atualizado/a em conhecimentos técnicos da sua especialidade. Assimila rapidamente novas técnicas ou conhecimentos específicos. Domina os aspectos técnicos do seu trabalho ou área.");
define("STR_PRISMA_ANALISIS"											, "ANÁLISE");
define("STR_PRISMA_ANALISIS_A_VECES_TXT"								, "Analisa em profundidade ou atentamente os fatos, dados ou informações. Demonstra eficácia solucionando problemas. Estabelece métodos e/ou processos que ampliam e/ou facilitam soluções. Analisa as causas, os detalhes ou as conseqüências dos problemas ou assuntos.");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_2BR"				, "GARANTIA<br />E PROMOÇÃO<br />QUALIDADE");
define("STR_PRISMA_CASI_SIEMPRE"										, "QUASE SEMPRE");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_CASI_SIEMPRE_TXT"	, "Assume e/ou promove a importância da qualidade. Compromete-se ativamente para atingir objetivos de qualidade. Exige de si mesmo alta qualidade nas suas tarefas. É rigoroso/a no que se refere a manter normas e/ou padrões de qualidade.");
define("STR_PRISMA_AREA_POTENCIAL_FORTALEZA"							, "ÁREA DE POTENCIAIS PONTOS FORTES");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_BR"								, "ORDEM <br />E SISTEMÁTICA");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_A_VECES_TXT"						, "Executa tarefas meticulosamente, prestando antençâo para os detalles Tenta manter ordenado o seu entorno Segue uma estrutura e uma sistemática para enfrentar as tarefas.");
define("STR_PRISMA_COMPETENCIAS_PARA_EL_DESARROLLO_DEL_NEGOCIO"			, "COMPETÊNCIAS PARA O DESENVOLVIMENTO DO NEGÓCIO");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_BR"								, "ORIENTAÇÃO<br />A RESULTADOS");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_CASI_NUNCA_TXT"					, "Concentra-se com energia em atingir objetivos e resultados. Dirige os seus trabalhos e atividades para o crescimento do negócio. Demonstra uma forte aptidão ou enfoque no aspecto comercial. Está atento às vendas, ao faturamento e/ou à rentabilidade da organização.");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_2BR"						, "INOVAÇÃO<br />E<br />CRIATIVIDADE");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_A_VECES_TXT"				, "É capaz de produzir idéias ou enfoques originais. É inovador/a introduzindo melhoras. Contribui com novas idéias ou pontos de vista. Propõe novas idéias, produtos, serviços ou procedimentos.");
define("STR_PRISMA_ORIENTACIÓN_A_LA_ACCION_Y_DECISION"					, "ORIENTAÇÃO<br />À AÇÃO<br />E À DECISÃO");
define("STR_PRISMA_ORIENTACIÓN_A_LA_ACCION_Y_DECISION_CASI_NUNCA_TXT"	, "Toma decisões com facilidade ou rapidez. Demonstra energia ou determinação no trabalho. Toma a iniciativa nas decisões. Estimula com entusiasmo a realização dos trabalhos.");
define("STR_PRISMA_VISION_ESTRATEGICA_BR"								, "VISÃO<br />ESTRATÉGICA");
define("STR_PRISMA_VISION_ESTRATEGICA_CASI_NUNCA_TXT"					, "Leva em conta os objetivos gerais da empresa/do negócio. Pensa e age com uma visão a médio/longo prazo. Toma decisões que supõem mudanças estratégicas na empresa. Elabora ou estabelece objetivos de longo prazo para a empresa.");
define("STR_PRISMA_COMPETENCIAS_INTERPERSONALES"						, "COMPETÊNCIAS INTERPESSOAIS");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_BR"							, "HABILIDADE<br />INTERPESSOAL");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_CASI_NUNCA_TXT"				, "Demonstra habilidade para se relacionar com os outros e fazer parte de equipes. Ajuda e facilita o trabalho dos outros. Demonstra interesse e sensibilidade em relação aos outros. Demonstra ser capaz de obter o melhor de cada colaborador/a ou colega.");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_BR"						, "FLEXIBILIDADE<br />E<br />ADAPTAÇÃO");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_NUNCA_TXT"					, "Aceita positivamente as mudanças. Adapta-se facilmente às novas pessoas ou situações. Demonstra boa disposição para assimilar novos métodos ou procedimentos. Apóia as iniciativas de mudança ou melhorias.");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_2BR"				, "RESISTÊNCIA<br />AO CANSAÇO<br />E AO ESTRESSE");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_CASI_SIEMPRE_TXT", "Mantém a calma em situações tensas. Recupera-se com facilidade depois dos contratempos. Tolera facilmente críticas ou atrevimentos. Sobrepõe-se ou mantém o controle diante de exigências ou pressões.");
define("STR_PRISMA_MOTIVACION_PERSONAL_POR_EL_TRABAJO"					, "MOTIVAÇÃO<br />PESSOAL<br />NO TRABALHO");
define("STR_PRISMA_MOTIVACION_PERSONAL_POR_EL_TRABAJO_CASI_NUNCA_TXT"	, "Assume com intensidade suas responsabilidades profissionais. Busca a promoção na empresa. Supera os erros passados com disposição ou energia. Demonstra grande vontade de fazer as coisas de um modo cada vez melhor.");
define("STR_PRISMA_AREA_CLAVE_DE_MEJORA_BR"								, "ÁREA<br />CHAVE<br />DE<br />MELHORIA");
define("STR_PRISMA_AREA_DE_POTENCIAL_DESARROLLO"						, "ÁREA<br />DE<br />POTENCIAL<br />DESENVOLVIMENTO");
define("STR_PRISMA_AREA_DE_DESARROLLO_2BR"								, "ÁREA<br />EM<br />DESENVOLVIMENTO");
define("STR_PRISMA_AREA_DE_POTENCIAL_FORTALEZA"							, "ÁREA DE<br />POTENCIAIS<br />PONTOS<br />FORTES");
define("STR_PRISMA_AREA_DE_FORTALEZA_2BR"								, "ÁREA<br />DE<br />PONTOS<br />FORTES");
define("STR_PRISMA_NUNCA_SE_COMPORTA_ASI"								, "<strong>Nunca</strong><br />se comporta assim");
define("STR_PRISMA_CASI_NUNCA_SE_COMPORTA_ASI"							, "<strong>Quase nunca</strong><br />se comporta assim");
define("STR_PRISMA_A_VECES_SE_COMPORTA_ASI"								, "<strong>Às vezes</strong><br />se comporta assim");
define("STR_PRISMA_CASI_SIEMPRE_SE_COMPORTA_ASI"						, "<strong>Quase sempre</strong><br />se comporta assim");
define("STR_PRISMA_SIEMPRE_SE_COMPORTA_ASI"								, "<strong>Sempre</strong><br />se comporta assim");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR"									, "DIRIGIR E LIDERAR");
define("STR_PRISMA_DIRIGIR_Y_LIDERAR_TXT"								, "Delega tarefas e motiva o grupo eficazmente para atingir os objetivos da organização.");
define("STR_PRISMA_PLANIFICACION_TXT"									, "Organiza e programa atividades, processos e recursos.");
define("STR_PRISMA_COMUNICACION_SOCIAL"									, "COMUNICAÇÃO SOCIAL");
define("STR_PRISMA_COMUNICACION_SOCIAL_TXT"								, "Fala com clareza, fluência e convicção, tanto individualmente quanto em grupo.");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA"							, "PERSUASÃO E INFLUÊNCIA");
define("STR_PRISMA_PERSUASIVIDAD_E_INFLUENCIA_TXT"						, "Influi, convence e gera impacto nos outros para melhorar ou alterar resultados, pontos de vista ou comportamentos.");
define("STR_PRISMA_DOMINIO_DE_LA_ESPECIALIDAD"							, "DOMÍNIO DA ESPECIALIDADE");
define("STR_PRISMA_DOMINIO_DE_LA_ESPECIALIDAD_TXT"						, "Domínio técnico ou profissional do trabalho. Curiosidade ou interesse em se atualizar.");
define("STR_PRISMA_ANALISIS_TXT"										, "Analisa aspectos e problemas detalhadamente, de maneira sistemática, emitindo julgamentos sólidos baseados em informações relevantes.");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_1BR"				, "GARANTIA E PROMOÇÃO DA QUALIDADE");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD_TXT"				, "Demonstra interesse pelos objetivos e critérios de qualidade. Garante a produtividade e a qualidade.");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA"									, "ORDEM E SISTEMÁTICA");
define("STR_PRISMA_ORDEN_Y_SISTEMATICA_TXT"								, "Enfrenta as tarefas de modo organizado e estruturado, tentado manter ordenado o seu entorno");
define("STR_PRISMA_ORIENTACION_AL_LOGRO"								, "ORIENTAÇÃO A RESULTADOS");
define("STR_PRISMA_ORIENTACION_AL_LOGRO_TXT"							, "Compreende e aplica pontos de vista comerciais e financeiros. Pensa e age em termos de custos, benefícios, mercados e valor agregado.");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_CAMBIOS_Y_MEJORAS"			, "INOVAÇÃO E CRIATIVIDADE");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD_CAMBIOS_Y_MEJORAS_TXT"		, "Aporta pontos de vista novos e criativos no trabalho. Identifica aspectos originais e tende a superar as resistências tradicionais.");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION_BR"				, "ORIENTAÇÃO À AÇÃO<br />E DECISÃO");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION_TXT"				, "Demonstra estar disposto a decidir, a tomar a iniciativa e a ser pró-ativo.");
define("STR_PRISMA_VISION_ESTRATEGICA"									, "VISÃO ESTRATÉGICA");
define("STR_PRISMA_VISION_ESTRATEGICA_TXT"								, "Apresenta pontos de vista amplos, transcendentes e de perspectiva a médio a longo prazos.");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL"								, "HABILIDADE INTERPESSOAL");
define("STR_PRISMA_HABILIDAD_INTERPERSONAL_TXT"							, "Tem um relacionamento positivo e construtivo com os outros. É estimado e trabalha eficazmente em equipe.");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION"							, "FLEXIBILIDADE E ADAPTAÇÃO");
define("STR_PRISMA_FLEXIBILIDAD_Y_ADAPTACION_TXT"						, "Adapta-se com facilidade e positivamente às demandas de mudança e a períodos de pressão.");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_1BR"				, "RESISTÊNCIA AO CANSAÇO<br />E AO ESTRESSE");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES_TXT"				, "Mantém linhas de conduta estáveis diante das dificuldades e pressões. Tem um controle eficaz de si mesmo.");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO_BR"				, "MOTIVAÇÃO PESSOAL<br />NO TRABALHO");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO_TXT"				, "Compromete-se no trabalho para alcançar os objetivos estabelecidos. Demonstra entusiasmo e ambição de sucesso.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA"			, "SÍNTESE DO PERFIL DE COMPETÊNCIAS PRISM@");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P1"	, "Este Perfil descreve como se comporta um/a candidato/a nas principais situações de trabalho, com base em uma série de habilidades.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P2"	, "O tipo de Questionário de Personalidade Profissional que o/a candidato/a respondeu fez com que ele/a escolhesse, entre três frases que refletem comportamentos ou situações de trabalho, a que melhor e a que pior o descrevem. Com este método, é impossível obter altas pontuações em todas as competências.");
define("STR_PRISMA_SINTESIS_DEL_PERFIL_DE_COMPETENCIAS_PRISMA_INTRO_P3"	, "O perfil que apresentamos a seguir deverá ser considerado um indicador das suas maiores habilidades e das que poderia desenvolver, com base nas priorizações reveladas pelas suas respostas.");
define("STR_PRISMA_CLAVE_DE_MEJORA"										, "CHAVE DE<br />MELHORIA");
define("STR_PRISMA_POTENCIAL_DESARROLLO"								, "POTENCIAL<br />DESENVOLVIMENTO");
define("STR_PRISMA_AREA_DE_DESARROLLO_BR"								, "ÁREA EM<br />DESENVOLVIMENTO");
define("STR_PRISMA_POTENCIAL_FORTALEZA"									, "POTENCIAIS<br />PONTOS FORTES");
define("STR_PRISMA_AREA_DE_FORTALEZA"									, "ÁREA DE<br />PONTOS<br />FORTES");
define("STR_PRISMA_AREA_DE_BR_FORTALEZA"								, "ÁREA DE<br />PONTOS<br />FORTES");
define("STR_PRISMA_GARANTIA_Y_PROMOCION_DE_LA_CALIDAD"					, "GARANTIA E PROMOÇÃO DA QUALIDADE");
define("STR_PRISMA_INNOVACION_Y_CREATIVIDAD"							, "INOVAÇÃO E CRIATIVIDADE (Mudanças e Melhorias)");
define("STR_PRISMA_ORIENTACION_A_LA_ACCION_Y_DECISION"					, "ORIENTAÇÃO À AÇÃO E À DECISÃO");
define("STR_PRISMA_RESISTENCIA_A_LA_FATIGA_Y_AL_ESTRES"					, "RESISTÊNCIA AO CANSAÇO E AO ESTRESSE");
define("STR_PRISMA_MOTIVACION_PERSONAL_EN_EL_TRABAJO"					, "MOTIVAÇÃO PESSOAL NO TRABALHO");
define("STR_PRISMA_PERFIL_DE_ESTILOS"									, "PERFIL DE ESTILOS");
define("STR_PRISMA_PERFIL_DE_ESTILOS_TXT"								, "Este relatório reúne as características predominantes do estilo ou dos estilos da pessoa que respondeu o questionário, quando comanda uma equipe, quando se relaciona com o chefe e quando trabalha em grupo, de acordo com o perfil profissional definido.");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO"								, "ESTILOS DE LIDERANÇA");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO_P1"								, "Kenneth Blanchard, por meio do estudo do comportamento dos líderes em diversas situações, criou a teoria da Liderança Situacional. Esta teoria se baseia em duas dimensões fundamentais do comportamento do líder: nível de direção (comportamento de tarefa) e nível de apoio sócio-emocional (comportamento de relacionamento) que o líder deve proporcionar em uma situação de acordo com a 'maturidade dos seus colaboradores'.");
define("STR_PRISMA_ESTILOS_DE_LIDERAZGO_P2"								, "Este relatório mostra quais são os estilos preferidos de comando a partir do perfil profissional definido. Identificam-se os estilos que costumam ser adotados para mandar, coordenar ou comandar os colaboradores. Além disso, explica em que consiste cada um destes estilos predominantes, levando em conta outros casos similares, principalmente aqueles em que pode ser mais eficaz.");
define("STR_PRISMA_ESTILOS_DE_COLABORACION"								, "ESTILOS DE COLABORAÇÃO");
define("STR_PRISMA_ESTILOS_DE_COLABORACION_P1"							, "Para cada um dos estilos de liderança é possível definir um estilo de colaboração complementar. Por exemplo, um colaborador submisso provavelmente se adequará em maior grau a um líder diretivo do que alguém que é mais auto-suficiente.");
define("STR_PRISMA_ESTILOS_DE_COLABORACION_P2"							, "Este relatório descreve o ou os estilos preferidos ou mais freqüentes de colaboração baseados no perfil  profissional definido. Também identifica os estilos com menos preferência ou freqüência quando o candidato é comandado por outras pessoas ou em certas circunstâncias.");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO"					, "ESTILOS DE COMPORTAMENTO EM EQUIPE");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO_P1"				, "Dentro das equipes, diferentes papéis ou estilos de comportamento podem ser adotados, sendo cada um deles importante para garantir um bom desempenho do grupo.");
define("STR_PRISMA_ESTILOS_DE_COMPORTAMIENTO_EN_EQUIPO_P2"				, "Este relatório reflete o ou os estilos preferidos ou mais freqüentes de comportamento em equipe baseados no perfil profissional do/a candidato/a. Também identifica os estilos com menos preferência quando trabalha com outros ou em certas circunstâncias.");
define("STR_PRISMA_LIDERAZGO"											, "LIDERANÇA");
define("STR_PRISMA_CASI_NUNCA_SERA"										, "Quase<br />nunca<br />será");
define("STR_PRISMA_RARAS_VECES_SERA"									, "Rarame<br />nte<br />será");
define("STR_PRISMA_PUEDE_SER"											, "Pode<br />ser");
define("STR_PRISMA_ALGUNAS_VECES_SERA"									, "Algumas<br />vezes<br />será");
define("STR_PRISMA_CASI_SIEMPRE_SERA"									, "Quase<br />sempre<br />será");
define("STR_PRISMA_DIRECTIVO"											, "Diretivo");
define("STR_PRISMA_DIRECTIVO_P1"										, "- Assume toda a responsabilidade por tomar decisões.");
define("STR_PRISMA_DIRECTIVO_P2"										, "- Planeja, estabelece prioridades, distribui as tarefas e controla.");
define("STR_PRISMA_DIRECTIVO_P3"										, "- Orientado a metas e resultados.");
define("STR_PRISMA_DELEGADOR"											, "Delegante");
define("STR_PRISMA_DELEGADOR_P1"										, "- Delega à equipe as tarefas e decisões.");
define("STR_PRISMA_DELEGADOR_P2"										, "- Entrega os trabalhos e deixa que a equipe assuma a responsabilidade.");
define("STR_PRISMA_DELEGADOR_P3"										, "- Supervisiona apenas os resultados.");
define("STR_PRISMA_NEGOCIADOR"											, "Negociador");
define("STR_PRISMA_NEGOCIADOR_P1"										, "- Negocia e convence seus colaboradores para obter deles compromisso e colaboração.");
define("STR_PRISMA_NEGOCIADOR_P2"										, "- Oferece compensações para obter acordos.");
define("STR_PRISMA_NEGOCIADOR_P3"										, "- Vende as decisões à sua equipe.");
define("STR_PRISMA_CONSULTIVO"											, "Consultivo");
define("STR_PRISMA_CONSULTIVO_P1"										, "- Consulta e sonda as opiniões dos outros, mas decide com independência e segurança.");
define("STR_PRISMA_CONSULTIVO_P2"										, "- Leva em conta as contribuições da equipe, mas não delega as decisões.");
define("STR_PRISMA_DEMOCRATICO"											, "Democrático");
define("STR_PRISMA_DEMOCRATICO_P1"										, "- Orientado ao grupo, dá coesão, apóia e motiva os seus colaboradores.");
define("STR_PRISMA_DEMOCRATICO_P2"										, "- Estimula a participação da equipe nas decisões.");
define("STR_PRISMA_DEMOCRATICO_P3"										, "- Prefere chegar a um consenso a tomar decisões sozinho.");
define("STR_PRISMA_COLABORACION"										, "COLABORAÇÃO");
define("STR_PRISMA_AUTOSUFICIENTE"										, "Auto-suficiente");
define("STR_PRISMA_AUTOSUFICIENTE_P1"									, "- Gosta de trabalhar com autonomia e alto grau de liberdade.");
define("STR_PRISMA_AUTOSUFICIENTE_P2"									, "- Tem as suas idéias e gosta de colocá-las em prática.");
define("STR_PRISMA_AUTOSUFICIENTE_P3"									, "- Age sem necessidade de consultar os outros.");
define("STR_PRISMA_SUMISO"												, "Submisso");
define("STR_PRISMA_SUMISO_P1"											, "- Gosta de receber diretrizes, procedimentos e instruções concretas para realizar o trabalho.");
define("STR_PRISMA_SUMISO_P2"											, "- Prefere que decidam por ele.");
define("STR_PRISMA_SUMISO_P3"											, "- Apega-se às normas, à disciplina e ao que foi determinado.");
define("STR_PRISMA_COMPLICE"											, "Cúmplice");
define("STR_PRISMA_COMPLICE_P1"											, "- Para fazer seu trabalho precisa de argumentos que o convençam.");
define("STR_PRISMA_COMPLICE_P2"											, "- Reage com segurança às propostas que recebe.");
define("STR_PRISMA_COMPLICE_P3"											, "- Negocia com os chefes as alternativas e soluções, buscando a situação mais vantajosa.");
define("STR_PRISMA_INFORMADOR"											, "Informador");
define("STR_PRISMA_INFORMADOR_P1"										, "- Gosta de ser consultado/a e levado em conta como especialista, embora procure não tomar a decisão final.");
define("STR_PRISMA_INFORMADOR_P2"										, "- Analisa com critério, oferecendo o seu assessoramento com independência.");
define("STR_PRISMA_PARTICIPATIVO"										, "Participativo");
define("STR_PRISMA_PARTICIPATIVO_P1"									, "- Gosta de contribuir com idéias para o grupo e de colaborar com os seus chefes quando é requisitado ou consultado.");
define("STR_PRISMA_PARTICIPATIVO_P2"									, "- Envolve-se na solução de problemas e na tomada de decisões.");
define("STR_PRISMA_COMPORTAMIENTO_EN_EQUIPO"							, "COMPORTAMENTO EM EQUIPE");
define("STR_PRISMA_COORDINADOR"											, "Coordenador");
define("STR_PRISMA_COORDINADOR_P1"										, "- Calmo/a, seguro/a de si mesmo/a, controlado/a, maduro/a e confiante.");
define("STR_PRISMA_COORDINADOR_P2"										, "- Estabelece objetivos e define tarefas. Coordena os esforços e contribuições da equipe, promovendo a tomada de decisões e esclarecendo as metas.");
define("STR_PRISMA_COORDINADOR_P3"										, "- Tende a delegar tarefas e pode ser considerado um pouco manipulador ou ineficiente.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS"								, "Construtor<br />de equipes");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P1"							, "- Cooperador/a, agradável, perceptivo/a, diplomático/a, sociável, sensível.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P2"							, "- Promove a harmonia entre as equipes. É habilidoso/a para responder às pessoas e reagir às situações. Promove o espírito de equipe.");
define("STR_PRISMA_CONSTRUCTOR_DE_EQUIPOS_P3"							, "- Pode ser indeciso/a em situações de crise. Pode demonstrar pouca auto-afirmação.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS"							, "Caçador<br />de recursos");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P1"							, "- Extrovertido/a, entusiasmado, comercial, curioso/a, comunicativo/a.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P2"							, "- Busca novas oportunidades e desenvolve contatos. Tem grande capacidade para se relacionar e para explorar o novo. É hábil para reagir aos desafios");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P3"							, "- Perde facilmente o interesse quando o entusiasmo inicial desaparece.");
define("STR_PRISMA_INVESTIGADOR_DE_RECURSOS_P4"							, "- Pode chegar a ser excessivamente otimista.");
define("STR_PRISMA_IMPULSOR_ENERGETICO"									, "Impulsor de energia");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P1"								, "- Dinâmico/a, enérgico/a, tenso/a, simpático/a e com muita energia.");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P2"								, "- Desafia as pessoas e trabalha bem sob pressão. Tem força e coragem para superar os obstáculos. Questiona a inércia e a ineficiência.");
define("STR_PRISMA_IMPULSOR_ENERGETICO_P3"								, "- Pode ser provocador/a, ter falta de tato ou tratar as pessoas de modo duro. Pode demonstrar irritação ou impaciência. Pode ser considerado/a uma pessoa autocrítica.");
define("STR_PRISMA_APLICADOR"											, "Aplicador");
define("STR_PRISMA_APLICADOR_P1"										, "- Metódico/a, constante, cumpridor/a do dever, conservador/a, previsível.");
define("STR_PRISMA_APLICADOR_P2"										, "- Transforma as decisões ou políticas em objetivos concretos, faz um acompanhamento para atingir os objetivos.");
define("STR_PRISMA_APLICADOR_P3"										, "- Um pouco inflexível. Pode ser lento na hora de reagir às mudanças ou inovações.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR"								, "Analisador<br />Avaliador");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P1"								, "- Sério/a, tranqüilo/a, prudente, perspicaz, estrategista.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P2"								, "- Oferece ponderação, reflexão e análise, critério e discrição. Pode perceber as diversas opções e julgar com exatidão.");
define("STR_PRISMA_ANALIZADOR_EVALUADOR_P3"								, "- Pode sofrer de falta de iniciativa ou de habilidade para inspirar ou motivar os outros. Pode ser excessivamente crítico/a.");
define("STR_PRISMA_CREATIVO"											, "Criativo");
define("STR_PRISMA_CREATIVO_P1"											, "- Imaginativo/a, independiente, heterodoxo/a, generador/a de ideas.");
define("STR_PRISMA_CREATIVO_P2"											, "- Pode ser brilhante e profundo/a nos seus enfoques. Resolve problemas difíceis com genialidade e/ou inteligência.");
define("STR_PRISMA_CREATIVO_P3"											, "- Pode se descuidar com facilidade dos detalhes e/ou do protocolo. Pode ser disperso/a ou pouco constante.");
define("STR_PRISMA_PERFECCIONISTA"										, "Perfeccionista");
define("STR_PRISMA_PERFECCIONISTA_P1"									, "- Detalhista, minucioso/a, cumpridor/a do dever, dedicado/a, consciente.");
define("STR_PRISMA_PERFECCIONISTA_P2"									, "- Costuma aplicar conhecimentos e técnicas especializadas. Tem alta capacidade e interesse para concluir trabalhos. É intolerante com a negligência ou falta de qualidade.");
define("STR_PRISMA_PERFECCIONISTA_P3"									, "- Preocupa-se muito quando as coisas não vão bem. É bastante resistente a delegar.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL"						, "PERFIL COMPETENCIA EMOCIONAL");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P1"						, "La tolerancia general del estrés y la gestión eficaz de emociones, son dos elementos críticos en las relaciones profesionales y por tanto, en la adaptación de un profesional a su puesto o entorno profesional.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P2"						, "Las negociaciones, las relaciones con clientes, colaboradores, la gestión de conflictos, las posibles presiones normales del trabajo requieren de una serie de competencias y controles emocionales, que, en dependecia del perfil personal laboral ser más o menos efectivos.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P3"						, "En el gráfico, las zonas sombreadas nos indican la necesidad de hacer un análisis más profundo del perfil y contexto del puesto.");
define("STR_PRISMA_PERFIL_COMPETENCIA_EMOCIONAL_P4"						, "Las combinaciones entre puntuaciones extremas (zonas sombreadas), nos indican la necesidad de profundizar en la entrevista de selección y/o desarrollo profesional para analizar posibles repercusiones según las exigencias del contexto laboral o de las responsabilidades del puesto o función.");
define("STR_PRISMA_CONFIANZA_EN_OTROS"									, "Confianza en otros");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES"					, "PERFIL DE ESTRESORES POTENCIALES");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P1"					, "Este informe nos orienta acerca de las posibles actividades, circunstancias o condiciones específicas que pueden suponer una fuente más importante de estrés para el profesional que ha respondido al cuestionario Prism@.");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P2"					, "En el perfil, aparecerán los factores que pueden generar mayor probabilidad de estrés (9-10), o probabilidad relativamente alta (7-8).");
define("STR_PRISMA_PERFIL_DE_ESTRESORES_POTENCIALES_P3"					, "Las puntuaciones medias (4,5,6) o bajas (1,2) no implican indiferencia por parte del profesional. Simplemente no parecen ser en la actualidad fuente probable de estrés.");
define("STR_PRISMA_FACTORES_ORGANIZATIVOS"								, "FACTORES ORGANIZATIVOS");
define("STR_PRISMA_TRABAJO_RUTINARIO_Y_REPETITIVO"						, "TRABAJO RUTINARIO Y REPETITIVO");
define("STR_PRISMA_CAMBIOS_FRECUENTES"									, "CAMBIOS FRECUENTES");
define("STR_PRISMA_ESTRUCTURAS_BUROCRATICAS"							, "ESTRUCTURAS BUROCRÁTICAS");
define("STR_PRISMA_ENTORNOS_REACTIVOS"									, "ENTORNOS REACTIVOS");
define("STR_PRISMA_FACTORES_RELACIONALES"								, "FACTORES RELACIONALES");
define("STR_PRISMA_HABLAR_EN_PUBLICO"									, "HABLAR EN PÚBLICO");
define("STR_PRISMA_VENDER_NEGOCIAR"										, "VENDER / NEGOCIAR");
define("STR_PRISMA_DAR_MALAS_NOTICIAS"									, "DAR MALAS NOTICIAS");
define("STR_PRISMA_FACTORES_MOTIVACIONALES"								, "FACTORES MOTIVACIONALES");
define("STR_PRISMA_FALTA_DE_PODER"										, "FALTA DE PODER");
define("STR_PRISMA_FALTA_DE_APOYO_SOCIAL"								, "FALTA DE APOYO SOCIAL");
define("STR_PRISMA_FALTA_DE_AUTONOMIA"									, "FALTA DE AUTONOMÍA");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL"						, "FALTA DE PROGRESO PROFESIONAL");
define("STR_PRISMA_ESCASOS_RETOS_INTELECTUALES"							, "ESCASOS RETOS INTELECTUALES");
define("STR_PRISMA_FALTA_DE_RECONOCIMIENTO"								, "FALTA DE RECONOCIMIENTO");
define("STR_PRISMA_FACTORES_DEL_PUESTO_DE_TRABAJO"						, "FACTORES DEL PUESTO DE TRABAJO");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES"				, "TOMA DE DECISIONES RÁPIDAS/DIFÍCILES");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS"						, "SOLUCIÓN DE PROBLEMAS COMPLEJOS");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO"						, "FUERTES RESTRICCIONES DE TIEMPO");
define("STR_PRISMA_AMBIENTE_COMPETITIVO"								, "AMBIENTE COMPETITIVO");
define("STR_PRISMA_DIRIGIR_A_OTROS"										, "DIRIGIR A OTROS");
define("STR_PRISMA_DEFINICION_DE_LOS_FACTORES_ESTRESORES"				, "DEFINICIÓN DE LOS FACTORES ESTRESORES");
define("STR_PRISMA_TRABAJO_RUTINARIO_Y_REPETITIVO_DEF"					, "Trabajos sin variedad de tareas, predecible, sin cambios, en el que siempre se hace lo mismo o de la misma manera.");
define("STR_PRISMA_CAMBIOS_FRECUENTES_DEF"								, "Cambios frecuentes o inesperados en los contenidos, sistemas o prácticas de trabajo. Incertidumbre asociada a cambios en responsabilidades, en funciones o requerimientos del puesto de trabajo.");
define("STR_PRISMA_ESTRUCTURAS_BUROCRATICAS_DEF"						, "Exceso de normas y/o procedimientos. Normativas exigentes, controles, burocracia o papeleos exigidos.");
define("STR_PRISMA_ENTORNOS_REACTIVOS_DEF"								, "Necesidad de respuesta urgente o reacción inmediata, sin oportunidad de planificación previa. Entornos impredecibles o que exigen solución de problemas conforme surgen. Cambios constantes en las prioridades.");
define("STR_PRISMA_HABLAR_EN_PUBLICO_DEF"								, "Tener que comunicar o realizar presentaciones ante un público o auditorio. Situaciones que exijan manejarse o relacionarse ante gente desconocida o ante grupos grandes.");
define("STR_PRISMA_VENDER_NEGOCIAR_DEF"									, "Situaciones que exijan vender ideas, productos o servicios. Tener que defender o convencer a otros o llevar a cabo negociaciones difíciles con clientes, proveedores, sindicatos, etc.");
define("STR_PRISMA_DAR_MALAS_NOTICIAS_DEF"								, "Tener que dar malas noticias, informaciones negativas o desagradables(a clientes, colegas o colaboradores). Tener que comunicar o implementar programas con los que las personas pueden sentirse o reaccionar mal.");
define("STR_PRISMA_CONFLICTOS_INTERPERSONALES"							, "CONFLICTOS INTERPERSONALES");
define("STR_PRISMA_CONFLICTOS_INTERPERSONALES_DEF"						, "Situaciones de discusión o desacuerdo.Ambientes en los que haya relaciones conflictivas o de difícil convivencia. Situaciones en las que hay que enfrentarse o resolver conflictos o desacuerdos con otras personas.");
define("STR_PRISMA_FALTA_DE_PODER_DEF"									, "Falta de poder o autoridad para hacer que las cosas se hagan o para conseguir los objetivos del grupo. Carencia de responsabilidades sobre proyectos o personas.");
define("STR_PRISMA_FALTA_DE_APOYO_SOCIAL_DEF"							, "Situaciones en las que haya que tomar decisiones o iniciar acciones discutibles, impopulares o en las que no existe acuerdo, aprobación del grupo o consenso con otras personas.");
define("STR_PRISMA_FALTA_DE_AUTONOMIA_DEF"								, "Falta de libertad para actuar y/o decidir criterios personales. Situaciones en las que no se puede actuar por uno mismo, teniendo que depender de otros.");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL_BR"					, "FALTA DE PROGRESO<br />PROFESIONAL");
define("STR_PRISMA_FALTA_DE_PROGRESO_PROFESIONAL_BR_DEF"				, "Trabajo donde no se favorece el avance y desarrollo de carrera. Ausencia de promoción y de carrera profesional. Falta de oportunidades de superación.");
define("STR_PRISMA_ESCASOS_RETOS_INTELECTUALES_DEF"						, "Trabajo lineal donde no se exige un esfuerzo intelectual. Pocas posibilidades de profundización en los temas, puestos sin especialización o poco técnicos.");
define("STR_PRISMA_FALTA_DE_RECONOCIMIENTO_DEF"							, "Inexistencia del reconocimiento o falta de reconocimiento formal. Ausencia de premios o recompensas a pesar de conseguir éxitos.");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES_BR"				, "TOMA DE DECISIONES<br />RÁPIDAS/DIFÍCILES");
define("STR_PRISMA_TOMA_DE_DECISIONES_RAPIDAS_DIFICILES_BR_DEF"			, "Situaciones que exigen tomar decisiones inmediatas o actuar con gran rapidez. Tiempo limitado para reflexionar.");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS_BR"					, "SOLUCIÓN DE PROBLEMAS<br />COMPLEJOS");
define("STR_PRISMA_SOLUCION_DE_PROBLEMAS_COMPLEJOS_BR_DEF"				, "Puestos con alta exigencia intelectual, manejo de mucha información o análisis de datos, ratios o informes exhaustivos.");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO_BR"					, "FUERTES RESTRICCIONES<br />DE TIEMPO");
define("STR_PRISMA_FUERTES_RESTRICCIONES_DE_TIEMPO_BR_DEF"				, "Puestos que requieren un ritmo muy alto de actividad, con paralizaciones o interrupciones que dificultan el cumplimiento de los plazos o compromisos.");
define("STR_PRISMA_AMBIENTE_COMPETITIVO_DEF"							, "Trabajos donde haya que competir con otros compañeros, situaciones de venta agresiva, o donde haya comparación continua de resultados.");
define("STR_PRISMA_DIRIGIR_A_OTROS_DEF"									, "Funciones y/o puestos que requieren tener a cargo a personas a las que hay que mandar, controlar y/o supervisar.");
define("STR_PRISMA_INDICADORES_DE_AJUSTE_A_LAS_COMPETENCIAS"			, "INDICADORES DE AJUSTE ÀS COMPETÊNCIAS");
define("STR_PRISMA_DEFINICION_DE_LAS_COMPETENCIAS"						, "DEFINIÇÃO DAS COMPETÊNCIAS");
define("STR_PRISMA_NOMBRE_INFORME_TXT"									, "Perfil de<br /><strong>personalidad<br />laboral</strong>");
define("STR_PRISMA_NOMBRE_INFORME_NARRATIVO_TXT"						, "Informe Narrativo Experto");
define("PRISMA_NARRATIVO_INTP1" 										, "Este informe está basado en las respuestas de el/la Sr/Sra. @usuario@ a un cuestionario de autoevaluación: el cuestionario de competencias y personalidad laboral Prisma. Este cuestionario le invita a describir su comportamiento, preferencias y actitudes en relación a distintos aspectos de su vida laboral."); 
define("PRISMA_NARRATIVO_INTP2" 										, "Durante el mismo, ha tenido que elegir la afirmación que más se ajusta, y la que menos, entre bloques de tres comportamientos posibles. Sus respuestas se han comparado con las de un grupo amplio y relevante para obtener un perfil de las preferencias percibidas de el/la Sr/Sra. @usuario@ respecto a las distintas maneras de comportarse en el trabajo, agrupadas en 4 áreas principales: Energías y motivaciones, Control Emocional y Tolerancia al Estrés, Orientación a la relación y a las personas, Estilo de pensamiento y potencial de recursos mentales.");
define("PRISMA_NARRATIVO_INTP3" 										, "Este informe describe el perfil de personalidad de el/la Sr/Sra. @usuario@ y debe tratarse como confidencial. Al considerar los resultados del cuestionario, es importante tener en cuenta que representa su propia visión y el modo en que percibe sus propias conductas, en lugar del modo en que terceras personas podrían describir su personalidad. La precisión de este informe depende de la franqueza y sinceridad con la que se completó el cuestionario, así como de su propio autoconocimiento. Por lo tanto, los comentarios que se realicen en este informe deben considerarse como algo orientativo, fiable, aunque no infalible. Este autoinforme puede proporcionar importantes indicadores acerca del estilo propio del/de la Sr/Sra. @usuario@ en el trabajo, y es probable que nos permita predecir en gran medida su comportamiento en distintas situaciones.");
define("PRISMA_NARRATIVO_INTP4" 										, "Tenga en cuenta que el cuestionario describe el estilo de conducta que prefiere el/la Sr/Sra. @usuario@, pero no sus capacidades. El cuestionario aporta una descripción amplia de su estilo actual y, por lo tanto, el informe es necesariamente general. La vida útil de los datos contenidos en el informe se considera que está entre 18 y 24 meses, en función de las circunstancias personales y el puesto de trabajo. Si se han producido cambios significativos en su vida o si existe un cambio significativo en el puesto, debería volver a completar el cuestionario.");
define("PRISMA_NARRATIVO_INTP5" 										, "Si le preocupa algo con relación al contenido de este informe, diríjase a alguien que haya recibido una formación completa en el uso del cuestionario Prisma.");
define("STR_ESTILO_ORENTACION_NARR_PRISMA" 								, "ESTILO DE ORIENTACIÓN A LA RELACIÓN Y A LAS PERSONAS");
define("STR_ESTILO_PENSAMIENTO_NARR_PRISMA" 							, "ESTILO DE PENSAMIENTO Y RECURSOS MENTALES");
define("STR_NUM_PREGUNTAS_ERRONEAS" 									, "Nº de questões erradas");
define("STR_NUM_PREGUNTAS_BLANCO" 										, "Nº de questões em branco");
define("STR_VOCABULARIO"		 										, "VOCABULÁRIO");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_AL_VOCABULARIO"		, "Número total de questões referidas ao vocabulário");
define("STR_GRAMATICA"													, "GRAMÁTICA");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_GRAMATICA"			, "Total number of questions referring to grammar");
define("STR_COMPRENSION"		 										, "COMPREENSÃO");
define("STR_NUMERO_TOTAL_DE_PREGUNTAS_REFERENTES_A_COMPRENSION"			, "Número total de questões referidas à compreensão");
define("STR_PRISMA_ESCALAS_DIFERENCIALES"								, "ESCALAS DIFERENCIALES");
define("STR_CIP_NOMBRE_INFORME_TXT"									, "<strong>Inventario de<br />Orientación<br />Profesional CIP</strong>");
define("STR_CIP_BIENVENIDO_INFORME_ORIENTACION_PROFESIONAL_TXT"									, "Bienvenido/a  al Informe de Orientación Profesional");
define("STR_CIP_INTRO_P1"						, "Este informe ha sido elaborado a partir de las respuestas y ejercicios realizados por @candidato_prueba@.<br /><br />El objetivo esencial de este informe es apoyar el proceso de orientación para @candidato_prueba@ sobre las profesiones y/o carreras profesionales en las que ha demostrado especial interés y/o preferencia a lo largo de las respuestas dadas en el cuestionario CIP, y ayudarle a conocer mejor las capacidades que podrían favorecer el éxito en su elección o que, por el contrario, podrían implicarle algún grado de dificultad.");
define("STR_CONTENIDO_DEL_INFORME"						, "Contenidos del informe");
define("STR_APARTADO_1"						, "Apartado 1: ÁREAS PROFESIONALES PREFERENTES");
define("STR_CIP_INTRO_P2"						, "En la primera parte del informe, se representa el gráfico que identifica el grado de interés (en porcentaje) que ha mostrado la persona hacia los campos profesionales y/o carreras profesionales generales asociadas que se han valorado.<br /><br />Este gráfico se acompaña de una breve síntesis escrita  identificando, según los datos cuantitativos obtenidos, las carreras y/o actividades que serían prioritarias y más motivantes para @candidato_prueba@.");
define("STR_APARTADO_2"						, "Apartado 2: ÁREA APTITUDES");
define("STR_CIP_INTRO_P3"						, "En este apartado, aparecen representadas las puntuaciones obtenidas en los test de aptitudes realizados por el/la estudiante (rendimiento en la prueba) en una escala de percentiles. Esta puntuación final representa el percentil obtenido (representado  de 0 a 100) o lo que es lo mismo, la comparativa de los resultados obtenidos con una muestra significativa de estudiantes de similar edad y características académicas.");
define("STR_APARTADO_3"						, "Apartado 3: ORIENTACIÓN PROFESIONAL");
define("STR_CIP_INTRO_P4"						, "En este apartado se integra la información relativa a las carreras o actividades asociadas a las capacidades en las que @candidato_prueba@ ha demostrado tener especial fortaleza y aquellas que, por el rendimiento obtenido, podrían indicar algún tipo de dificultad.<br /><br />La motivación por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior. Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que querría trabajar a futuro.<br /><br />La integración entre ambos aspectos permite una visión muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_INTEGRACION"						, "Integración");
define("STR_CIP_INTRO_P5"						, "De cara a la orientación, es importante tener siempre en cuenta que la motivación o interés (vocación) por un ámbito concreto de actividad profesional constituye un elemento esencial para el éxito posterior (1ª Parte del Informe o Gráfico de Áreas Profesionales Preferentes del CPI).<br /><br />Sin embargo, el que la persona cuente con determinadas capacidades o aptitudes, favorece e incrementa las posibilidades de rápida asimilación y aprendizaje de conceptos y/o habilidades asociadas a las carreras y profesiones en las que se deben aplicar.<br /><br />La integración entre ambos aspectos, nos puede dar una orientación muy rica para poder tomar decisiones adecuadas.  Por ello, el informe nos aporta una interpretación cualitativa que asocia ambos parámetros (Interés + Capacidad) para conocer con mayor exactitud las potencialidades de @candidato_prueba@.");
define("STR_PRUEBAS_ADMISION_NIVEL_GRADO"		, "Pruebas Admisión Nivel Grado");
define("STR_PRISMA_SIEMPRE"						, "SEMPRE");
define("STR_INFORME_DE_ATENCION_COMERCIAL","INFORME DE ATENCIÓN COMERCIAL");
define("STR_BAJO_POTENCIAL_0_A_35","Bajo Potencial: 0 a 35");
define("STR_MEDIO_POTENCIAL_36_A_70","Medio Potencial: 36 a 70");
define("STR_ALTO_POTENCIAL_71_A_100","Alto Potencial: 71 a 100");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL"			, "PERFIL DE COMPETENCIAS");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P1"	, "Este Perfil describe cómo se ha definido la persona que ha respondido al cuestionario Prisma  con respecto a los comportamientos del Cuestionario Prisma asociados a la definición de los Valores, Competencias Corporativas y Específicas de Grupo Leche Pascual.");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P2"	, "Los resultados obtenidos en el perfil, son una puntuación global, y por tanto deben ser considerados como un indicador orientativo de los aspectos más destacados y de las áreas de desarrollo, en base a las respuestas que se han dado en el cuestionario. Para profundizar en los detalles del perfil, recomendamos acudir al informe narrativo o informe de interpretación automática que aparece a continuación.");
define("STR_PRISMA_PERFIL_DE_COMPETENCIAS_PASCUAL_INTRO_P3"	, "Recordar que, el cuestionario al que la persona ha respondido, obliga a elegir entre 3 frases que reflejan conductas o situaciones laborales, la que mejor y peor le describe. Con este método, no puede lograr altas puntuaciones en todas las competencias.");
define("STR_PRISMA_DEFINICION_DE_LAS_COMPETENCIAS_PASCUAL"	, "DEFINICIÓN DE LAS COMPETENCIAS Y VALORES GLP");

define("STR_JN36_PERFIL_PSICOLOGICO_HUMANO_DE_JESUS_DE_NAZARET"	, "PERFIL PSICOLÓGICO-HUMANO DE JESÚS DE NAZARET");
define("STR_JN36_BAJO"												, "Bajo");
define("STR_JN36_ME_BA"												, "Me.-Ba.");
define("STR_JN36_MEDIO"												, "Medio");
define("STR_JN36_ME_AL"												, "Me.-Al.");
define("STR_JN36_ALTO"												, "Alto");
?>