<?php
/*
	$sql="";
	$sql = "DELETE FROM `ejemplos` ";
	if($oconn->Execute($sql) === false){
		$sTypeError	=	date('d/m/Y H:i:s') . " Error SQL [" . constant("MNT_BORRAR") . "][ProcesoTablas]";
		error_log($sTypeError . " ->\t" . $sql . "\n", 3, constant("DIR_FS_PATH_NAME_LOG"));
		echo(constant("ERR"));
		exit;
	}
*/
	$sql="";
	$sql="INSERT INTO `ejemplos` (`idEjemplo`, `codIdiomaIso2`, `idPrueba`, `enunciado`, `descripcion`, `path1`, `path2`, `path3`, `path4`, `correcto`, `orden`, `bajaLog`, `fecAlta`, `fecMod`, `usuAlta`, `usuMod`) VALUES";
	$sql.="(1, 'es', 26, 'Colombia y Perú desean renovar los Tratados de Libre Comercio.', 'La percepción mayoritaria entre los iberoamericanos es que los demócratas son más proteccionistas que los republicanos, así que para países como Colombia y Perú, que aguardan con ansiedad la ratificación de sus Tratados de Libre Comercio (TLC) con los Estados Unidos, la posibilidad de una victoria demócrata resulta angustiosa. Si el triunfo demócrata es modesto, existe una leve posibilidad de que el Congreso saliente sea capaz de ratificarlos antes de enero. Pero si es abultada, como dicen los anglosajones, en provocador castellano: “Hasta la vista, baby”.', '', '', '', '', 'A', 1, 0, '2011-02-22 14:01:29', '2011-04-05 14:21:15', 0, 0),";
	$sql.="(2, 'es', 26, 'Los demócratas de EEUU favorecerían la firma de estos tratados para países como Colombia o Perú.', 'La percepción mayoritaria entre los iberoamericanos es que los demócratas son más proteccionistas que los republicanos, así que para países como Colombia y Perú, que aguardan con ansiedad la ratificación de sus Tratados de Libre Comercio (TLC) con los Estados Unidos, la posibilidad de una victoria demócrata resulta angustiosa. Si el triunfo demócrata es modesto, existe una leve posibilidad de que el Congreso saliente sea capaz de ratificarlos antes de enero. Pero si es abultada, como dicen los anglosajones, en provocador castellano: “Hasta la vista, baby”.', '', '', '', '', 'B', 2, 0, '2011-04-05 14:22:59', '2011-04-05 14:23:13', 0, 0),";
	$sql.="(3, 'es', 26, 'Los anglosajones ofenden a los pueblos iberoamericanos con el uso provocador del castellano.', 'La percepción mayoritaria entre los iberoamericanos es que los demócratas son más proteccionistas que los republicanos, así que para países como Colombia y Perú, que aguardan con ansiedad la ratificación de sus Tratados de Libre Comercio (TLC) con los Estados Unidos, la posibilidad de una victoria demócrata resulta angustiosa. Si el triunfo demócrata es modesto, existe una leve posibilidad de que el Congreso saliente sea capaz de ratificarlos antes de enero. Pero si es abultada, como dicen los anglosajones, en provocador castellano: “Hasta la vista, baby”.', '', '', '', '', 'C', 3, 0, '2011-04-05 14:24:01', '2011-04-05 14:24:16', 0, 0),";
	$sql.="(4, 'es', 26, 'Hay una alta probabilidad de que ganen los republicanos en las próximas elecciones.', 'La percepción mayoritaria entre los iberoamericanos es que los demócratas son más proteccionistas que los republicanos, así que para países como Colombia y Perú, que aguardan con ansiedad la ratificación de sus Tratados de Libre Comercio (TLC) con los Estados Unidos, la posibilidad de una victoria demócrata resulta angustiosa. Si el triunfo demócrata es modesto, existe una leve posibilidad de que el Congreso saliente sea capaz de ratificarlos antes de enero. Pero si es abultada, como dicen los anglosajones, en provocador castellano: “Hasta la vista, baby”.', '', '', '', '', 'C', 4, 0, '2011-04-05 14:24:47', '2011-04-05 14:25:35', 0, 0),";
	$sql.="(1, 'es', 16, 'El indicador medio más bajo, de crecimiento entre los años x-3 y x, con respecto al óptimo, se ha dado en:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'B', 1, 0, '2011-04-05 16:01:32', '2011-04-05 19:12:05', 0, 0),";
	$sql.="(2, 'es', 16, 'Comparando bancos con cajas de ahorros, la relación entre aumento de productividad y aumento de rentabilidad es:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'B', 2, 0, '2011-04-05 16:09:25', '2011-04-05 19:14:55', 0, 0),";
	$sql.="(3, 'es', 16, 'Comparando las cifras medias de bancos y cajas se puede deducir que los aumentos entre x-3 y x son:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'D', 3, 0, '2011-04-05 16:10:17', '2011-04-05 19:43:32', 0, 0),";
	$sql.="(1, 'en', 16, 'The lowest average indicator of growth between x-3 x, with respect to the optimum, it has been given to:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'B', 1, 0, '2011-04-07 08:33:31', '2011-04-07 08:33:54', 0, 0),";
	$sql.="(2, 'en', 16, 'Comparing savings banks, the relationship between increased productivity and increased profitability is:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'B', 2, 0, '2011-04-07 08:35:13', '2011-04-07 08:35:13', 0, 0),";
	$sql.="(3, 'en', 16, 'Comparing the average numbers of banks and can be deduced that the increases between x-3 x are:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'D', 3, 0, '2011-04-07 08:36:06', '2011-04-07 08:36:28', 0, 0),";
	$sql.="(1, 'en', 26, 'Colombia and Peru want to renew the FTAs.', 'The prevailing perception among Latin Americans is that Democrats are more protectionist than Republicans, so for countries like Colombia and Peru, anxiously awaiting the ratification of the Free Trade Agreements (FTA) with the United States, the possibility of a Democratic victory is distressing. If the Democratic victory is modest, there is a slight possibility that the outgoing Congress will be able to ratify it before January. But if it is bulky, as they say whites in Castilian provocative: \"Hasta la vista, baby.\"', '', '', '', '', 'A', 1, 0, '2011-04-07 08:38:47', '2011-04-07 08:42:46', 0, 0),";
	$sql.="(2, 'en', 26, 'U.S. Democrats favor the signing of these treaties for countries like Colombia or Peru.', 'The prevailing perception among Latin Americans is that Democrats are more protectionist than Republicans, so for countries like Colombia and Peru, anxiously awaiting the ratification of the Free Trade Agreements (FTA) with the United States, the possibility of a Democratic victory is distressing. If the Democratic victory is modest, there is a slight possibility that the outgoing Congress will be able to ratify it before January. But if it is bulky, as they say whites in Castilian provocative: \"Hasta la vista, baby.\"', '', '', '', '', 'B', 2, 0, '2011-04-07 08:40:40', '2011-04-07 08:42:52', 0, 0),";
	$sql.="(3, 'en', 26, 'Whites offend the Latin American countries with the provocative use of Castilian.', 'The prevailing perception among Latin Americans is that Democrats are more protectionist than Republicans, so for countries like Colombia and Peru, anxiously awaiting the ratification of the Free Trade Agreements (FTA) with the United States, the possibility of a Democratic victory is distressing. If the Democratic victory is modest, there is a slight possibility that the outgoing Congress will be able to ratify it before January. But if it is bulky, as they say whites in Castilian provocative: \"Hasta la vista, baby.\"', '', '', '', '', 'C', 3, 0, '2011-04-07 08:41:38', '2011-04-07 08:42:57', 0, 0),";
	$sql.="(4, 'en', 26, 'There is a high probability that the Republicans win the next election.', 'The prevailing perception among Latin Americans is that Democrats are more protectionist than Republicans, so for countries like Colombia and Peru, anxiously awaiting the ratification of the Free Trade Agreements (FTA) with the United States, the possibility of a Democratic victory is distressing. If the Democratic victory is modest, there is a slight possibility that the outgoing Congress will be able to ratify it before January. But if it is bulky, as they say whites in Castilian provocative: \"Hasta la vista, baby.\"', '', '', '', '', 'C', 4, 0, '2011-04-07 08:42:15', '2011-04-07 08:43:04', 0, 0),";
	$sql.="(1, 'ca', 16, 'L''indicador mitjà més baix, de creixement entre els anys x-3 ix, pel que fa a l''òptim, s''ha donat en:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'B', 1, 0, '2011-04-07 08:45:15', '2011-04-07 08:45:15', 0, 0),";
	$sql.="(2, 'ca', 16, 'Comparant bancs amb caixes d''estalvis, la relació entre augment de productivitat i augment de rendibilitat és:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'B', 2, 0, '2011-04-07 08:45:55', '2011-04-07 08:46:59', 0, 0),";
	$sql.="(3, 'ca', 16, 'Comparant les xifres mitjanes de bancs i caixes es pot deduir que els augments entre x-3 ix són:', '', 'imgEjemplos/img01.jpg', 'imgEjemplos/img02.jpg', '', '', 'D', 3, 0, '2011-04-07 08:47:51', '2011-04-07 08:47:51', 0, 0),";
	$sql.="(1, 'pt', 26, 'Colombia y Perú desean renovar los Tratados de Libre Comercio.', 'A percepção predominante entre os latino-americanos é que os democratas são mais protecionistas que os republicanos, de modo que países como a Colômbia eo Peru, ansiosamente aguardando a ratificação dos Acordos de Livre Comércio (TLC) com os Estados Unidos, a possibilidade de Vitória democrata é angustiante. Se a vitória democrata é modesto, há uma pequena possibilidade de que o Congresso de saída será capaz de ratificá-lo antes de janeiro. Mas se ele é volumoso, como dizem os brancos em castelhano provocativa: \"Hasta la vista baby.\"', '', '', '', '', 'A', 1, 0, '2011-04-07 08:49:41', '2011-04-07 08:53:15', 0, 0),";
	$sql.="(2, 'pt', 26, 'U. S. Democratas favor a assinatura destes tratados para países como a Colômbia ou o Peru.', 'A percepção predominante entre os latino-americanos é que os democratas são mais protecionistas que os republicanos, de modo que países como a Colômbia eo Peru, ansiosamente aguardando a ratificação dos Acordos de Livre Comércio (TLC) com os Estados Unidos, a possibilidade de Vitória democrata é angustiante. Se a vitória democrata é modesto, há uma pequena possibilidade de que o Congresso de saída será capaz de ratificá-lo antes de janeiro. Mas se ele é volumoso, como dizem os brancos em castelhano provocativa: \"Hasta la vista baby.\"', '', '', '', '', 'B', 2, 0, '2011-04-07 08:50:20', '2011-04-07 08:53:22', 0, 0),";
	$sql.="(3, 'pt', 26, 'Brancos ofender os países latino-americanos com o uso do castelhano provocativo.', 'A percepção predominante entre os latino-americanos é que os democratas são mais protecionistas que os republicanos, de modo que países como a Colômbia eo Peru, ansiosamente aguardando a ratificação dos Acordos de Livre Comércio (TLC) com os Estados Unidos, a possibilidade de Vitória democrata é angustiante. Se a vitória democrata é modesto, há uma pequena possibilidade de que o Congresso de saída será capaz de ratificá-lo antes de janeiro. Mas se ele é volumoso, como dizem os brancos em castelhano provocativa: \"Hasta la vista baby.\"', '', '', '', '', 'C', 3, 0, '2011-04-07 08:51:18', '2011-04-07 08:53:28', 0, 0),";
	$sql.="(4, 'pt', 26, 'Existe uma grande probabilidade de que os republicanos ganharem a próxima eleição.', 'A percepção predominante entre os latino-americanos é que os democratas são mais protecionistas que os republicanos, de modo que países como a Colômbia eo Peru, ansiosamente aguardando a ratificação dos Acordos de Livre Comércio (TLC) com os Estados Unidos, a possibilidade de Vitória democrata é angustiante. Se a vitória democrata é modesto, há uma pequena possibilidade de que o Congresso de saída será capaz de ratificá-lo antes de janeiro. Mas se ele é volumoso, como dizem os brancos em castelhano provocativa: \"Hasta la vista baby.\"', '', '', '', '', 'C', 4, 0, '2011-04-07 08:52:26', '2011-04-07 08:53:34', 0, 0);";
	if($oconn->Execute($sql) === false){
		$sTypeError	=	date('d/m/Y H:i:s') . " Error SQL [" . constant("MNT_NUEVO") . "][ProcesoTablas]";
		error_log($sTypeError . " ->\t" . $sql . "\n", 3, constant("DIR_FS_PATH_NAME_LOG"));
		echo(constant("ERR"));
		exit;
	}
?>